import {test,expect} from '@playwright/test';
import {writeFile,readFile} from 'node:fs/promises';
import {startPwaServer} from '../pwa-server.mjs';
import {minimalPackage} from '../../js/editor/minimal-package.js';
const open=async(page,url='/')=>{await page.goto(url);await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();const start=Date.now();await page.getByRole('button',{name:'Criar pacote',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0',{timeout:20000});const mountMs=Date.now()-start;await page.getByRole('button',{name:'Compor',exact:true}).click();return mountMs;};
const add=async(page,type,name)=>{const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption(type);await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill(name);return box;};
const confirm=async page=>{await page.locator('.editor-toolbox').getByRole('button',{name:'Revisar inclusão',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();};
test('T10 visual: teclado/toque, seis paletas nos dois temas, larguras e zoom',async({browser},testInfo)=>{
 test.setTimeout(120000);const context=await browser.newContext({hasTouch:true,viewport:{width:360,height:900}}),page=await context.newPage();try{const mountMs=await open(page),before=await page.locator('#editor-json').inputValue(),metrics=[];
 for(const palette of ['classic','editorial','forest','ruby','monochrome','petals'])for(const theme of ['light','dark']){
  const width=palette==='classic'||palette==='editorial'?360:palette==='forest'||palette==='ruby'?768:1280;await page.setViewportSize({width,height:900});await page.evaluate(({palette,theme})=>{document.documentElement.dataset.palette=palette;document.documentElement.dataset.theme=theme;},{palette,theme});if(width<=900)await page.getByRole('button',{name:'Prévia',exact:true}).tap();await page.getByRole('combobox',{name:'Tema do ensaio',exact:true}).selectOption(theme);await expect(page.frameLocator('.editor-preview-frame:not([hidden])').locator('html')).toHaveAttribute('data-theme',theme);await expect(page.frameLocator('.editor-preview-frame:not([hidden])').locator('html')).toHaveAttribute('data-palette',palette);if(width<=900)await page.getByRole('button',{name:'Composição',exact:true}).tap();await page.locator('[role=treeitem][data-pointer="/layouts/0/tabs/0/sections/0/containers/0/components/0"]').tap();
  const move=page.locator('.editor-movement');await move.getByLabel('Posição entre os blocos',{exact:true}).selectOption({label:'No fim'});await move.getByRole('button',{name:'Revisar movimento',exact:true}).press('Enter');await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).tap();expect(await page.locator('#editor-json').inputValue()).toBe(before);
  const measurement=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,buttons:[...document.querySelectorAll('.editor-movement button')].map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})),palette:document.documentElement.dataset.palette,theme:document.documentElement.dataset.theme}));expect(measurement.overflow).toBeLessThanOrEqual(1);for(const b of measurement.buttons)expect(b.height).toBeGreaterThanOrEqual(44);metrics.push({...measurement,width});await page.screenshot({path:testInfo.outputPath('visual-'+palette+'-'+theme+'.png')});
 }
 await page.evaluate(()=>document.documentElement.style.zoom='2');await page.setViewportSize({width:768,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await page.getByRole('treeitem',{name:'Componente · Nome',exact:true}).press('ArrowDown');await expect(page.getByRole('treeitem',{name:'Componente · Base',exact:true})).toBeFocused();await writeFile(testInfo.outputPath('visual-access-metrics.json'),JSON.stringify({mountMs,metrics,zoom:2},null,2));
 }finally{await context.close();}
});
test('T09 arrasto: Escape, pointercancel, saída do frame e modo cancelam sem escrita',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue(),frame=page.frameLocator('.editor-preview-frame:not([hidden])');await frame.getByLabel('Nome',{exact:true}).click();const handle=frame.getByRole('button',{name:'Arrastar definição deste bloco',exact:true});
 const start=async()=>{await frame.getByLabel('Nome',{exact:true}).click();const from=await handle.boundingBox(),to=await frame.getByLabel('Base',{exact:true}).boundingBox();await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:5});};
 await start();await frame.getByLabel('Nome',{exact:true}).press('Escape');await page.mouse.up();await expect(page.getByRole('dialog')).toHaveCount(0);
 await start();await frame.locator('body').dispatchEvent('pointercancel',{pointerId:1,pointerType:'mouse'});await page.mouse.up();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(frame.locator('[data-composition-hover]')).toHaveCount(0);
 await start();await page.mouse.move(5,5);await page.mouse.up();await expect(page.getByRole('dialog')).toHaveCount(0);
 await start();await page.getByRole('button',{name:'Experimentar',exact:true}).click();await page.mouse.up();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.editor-forms')).toBeHidden();expect(await page.locator('#editor-json').inputValue()).toBe(before);
});
test('T07 campos de coleção conservam entradas auxiliares ao recuperar o rascunho',async({page})=>{
 await open(page);await add(page,'list','Contatos');await confirm(page);const pointer='/layouts/0/tabs/0/sections/0/containers/0/components/4/itemSchema';await page.locator('[data-nested="'+pointer+'"] > summary').click();await page.getByLabel('Nome do campo da coleção',{exact:true}).fill('Vínculo pendente');await page.getByLabel('Tipo do campo da coleção',{exact:true}).selectOption('reference');await page.getByLabel('Coleção de destino da referência',{exact:true}).selectOption('contatos');const before=await page.locator('#editor-json').inputValue();
 await page.getByRole('button',{name:'Experimentar',exact:true}).click();await page.getByRole('button',{name:'Compor',exact:true}).click();await expect(page.getByLabel('Nome do campo da coleção',{exact:true})).toHaveValue('Vínculo pendente');await expect(page.getByLabel('Tipo do campo da coleção',{exact:true})).toHaveValue('reference');await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.reload();await page.getByRole('button',{name:'Recuperar rascunho',exact:true}).click();await expect(page.getByLabel('Coleção de destino da referência',{exact:true})).toHaveValue('contatos');expect(await page.locator('#editor-json').inputValue()).toBe(before);await page.getByRole('button',{name:'Criar campo da coleção',exact:true}).click();await expect(page.locator('#editor-validation-summary')).toContainText('Contrato válido');
});
test('T10 subpasta offline: autoria visual, pending, recuperação, exportação e aplicação',async({page,context})=>{
 test.setTimeout(90000);const server=await startPwaServer();try{await page.goto(server.url);await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await context.setOffline(true);await open(page,server.url);const box=await add(page,'resource','Reserva sem rede');await box.getByLabel('Valor atual inicial',{exact:true}).fill('0');await box.getByLabel('Valor máximo inicial',{exact:true}).fill('8');await confirm(page);const before=await page.locator('#editor-json').inputValue();await box.getByLabel('O que adicionar',{exact:true}).selectOption('slotTracker');await box.getByLabel('Máximo de usos 1',{exact:true}).fill('Corrigir depois');await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.reload();await page.getByRole('button',{name:'Recuperar rascunho',exact:true}).click();await expect(box.getByLabel('Máximo de usos 1',{exact:true})).toHaveValue('Corrigir depois');expect(await page.locator('#editor-json').inputValue()).toBe(before);
 await box.getByLabel('O que adicionar',{exact:true}).selectOption('text');await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await expect(page.getByRole('button',{name:'Aplicar pacote',exact:true})).toBeEnabled();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar pacote',exact:true}).click();const exported=JSON.parse(await readFile(await(await downloading).path(),'utf8'));expect(exported.system.characterTemplate.reserva_sem_rede).toEqual({current:0,max:8});expect(exported.ui).toBeUndefined();await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await page.getByRole('button',{name:'Confirmar aplicação',exact:true}).click();await expect(page.locator('#editor-application-status')).toContainText('Pacote aplicado');
 }finally{await context.setOffline(false);await server.close();}
});

test('T10 toque emulado conclui recurso, cálculo, teste, ação, recuperação e exportação sem arrasto',async({browser})=>{
 test.setTimeout(120000);const context=await browser.newContext({hasTouch:true,viewport:{width:360,height:900}}),page=await context.newPage();try{await open(page);const box=page.locator('.editor-toolbox');const start=async(type,name)=>{await box.getByLabel('O que adicionar',{exact:true}).selectOption(type);await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill(name);},review=async()=>{await box.getByRole('button',{name:'Revisar inclusão',exact:true}).tap();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).tap();};
 await start('resource','Energia');await box.getByLabel('Valor atual inicial',{exact:true}).fill('3');await box.getByLabel('Valor máximo inicial',{exact:true}).fill('5');await review();await start('computed','Defesa');await box.getByLabel('Cálculo compartilhado',{exact:true}).selectOption('');await box.getByLabel('Operação desta parte',{exact:true}).selectOption('+');await box.getByRole('button',{name:'Editar primeiro valor',exact:true}).tap();await box.getByLabel('Número desta parte',{exact:true}).fill('10');await box.getByRole('button',{name:'Cálculo inteiro',exact:true}).tap();await box.getByRole('button',{name:'Editar segundo valor',exact:true}).tap();await box.getByLabel('Operação desta parte',{exact:true}).selectOption('identifier');await box.getByLabel('Fonte desta parte',{exact:true}).selectOption('score');await review();
 await start('checkRoll','Teste da viagem');await box.getByLabel('Nome da fonte 1',{exact:true}).fill('Agilidade');await box.getByLabel('Dado da fonte 1',{exact:true}).selectOption('score');await box.getByLabel('Decisões que ficam com a mesa neste teste',{exact:true}).fill('A mesa decide consequências.');await review();await start('actionGroup','Gastar energia');await box.getByLabel('Operação 1',{exact:true}).selectOption('add');await box.getByLabel('Dado alterado pela operação 1',{exact:true}).selectOption('energia.current');await box.getByLabel('Quantidade a somar (negativa para gastar)',{exact:true}).fill('-1');await review();await start('recoveryGroup','Recuperar energia');await box.getByLabel('Operação 1',{exact:true}).selectOption('restoreValue');await box.getByLabel('Dado alterado pela operação 1',{exact:true}).selectOption('energia.current');await box.getByLabel('Máximo deste valor',{exact:true}).selectOption('energia.max');await review();
 const canonical=await page.locator('#editor-json').inputValue();await page.getByRole('button',{name:'Prévia',exact:true}).tap();await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).tap();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');await page.getByRole('button',{name:'Experimentar',exact:true}).tap();const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await expect(frame.locator('.engine-computed__value').last()).toHaveText('12');await frame.getByRole('button',{name:'Rolar teste',exact:true}).tap();await expect(frame.locator('.engine-check__result')).not.toHaveText('');await frame.getByRole('button',{name:'Gastar energia',exact:true}).tap();await expect(frame.getByLabel('Energia atual',{exact:true})).toHaveValue('2');await frame.getByRole('button',{name:'Recuperar energia',exact:true}).tap();await frame.getByRole('dialog').getByRole('checkbox').tap();await frame.getByRole('dialog').getByRole('button',{name:'Aplicar recuperação',exact:true}).tap();await expect(frame.getByLabel('Energia atual',{exact:true})).toHaveValue('5');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
 const readiness=page.locator('.editor-package-readiness');await readiness.locator(':scope > summary').tap();const downloadPromise=page.waitForEvent('download');await readiness.getByRole('button',{name:'Exportar revisão conferida',exact:true}).tap();const exported=JSON.parse(await readFile(await (await downloadPromise).path(),'utf8'));expect(exported).toEqual(JSON.parse(canonical));expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);await expect(page.locator('#editor-json')).toBeHidden();
 }finally{await context.close();}
});
