import {test,expect} from '@playwright/test';
const open=async page=>{await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.getByRole('button',{name:'Criar pacote',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0',{timeout:20000});await page.getByRole('button',{name:'Compor',exact:true}).click();};
const pkg=async page=>JSON.parse(await page.locator('#editor-json').inputValue());
const review=async page=>{await page.locator('.editor-toolbox').getByRole('button',{name:'Revisar inclusão',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Cancelar conserva');await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();};
test('14A.2 toolbox cria texto, recurso, coleção e calculado sem JSON nem caminhos',async({page})=>{
 await open(page);const original=await page.locator('#editor-json').inputValue(),box=page.locator('.editor-toolbox');
 await box.getByLabel('O que adicionar',{exact:true}).selectOption('text');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Anotações');await review(page);let next=await pkg(page);expect(next.layouts[0].tabs[0].sections[0].containers[0].components.at(-1)).toMatchObject({type:'text',field:'anotacoes'});expect(Object.hasOwn(next.system.characterTemplate,'anotacoes')).toBe(false);
 await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(original);
 await box.getByLabel('O que adicionar',{exact:true}).selectOption('resource');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Energia');await box.getByLabel('Valor atual inicial',{exact:true}).fill('0');await box.getByLabel('Valor máximo inicial',{exact:true}).fill('12');await review(page);next=await pkg(page);expect(next.system.characterTemplate.energia).toEqual({current:0,max:12});
 await box.getByLabel('O que adicionar',{exact:true}).selectOption('list');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Contatos');await review(page);expect((await pkg(page)).system.characterTemplate.contatos).toEqual([]);
 await box.getByLabel('O que adicionar',{exact:true}).selectOption('computed');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Resultado');await box.getByLabel('Cálculo compartilhado',{exact:true}).selectOption('total');await review(page);expect((await pkg(page)).layouts[0].tabs[0].sections[0].containers[0].components.at(-1).formula).toBe('total');
 await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await expect(frame.getByLabel('Energia atual',{exact:true})).toHaveValue('0');
});
test('14A.2 cancelar inclusão e usar dado existente não cria dependência órfã',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue(),box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('number');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Outra apresentação da Base');await box.getByLabel('Dado do personagem',{exact:true}).selectOption('score');await box.getByRole('button',{name:'Revisar inclusão',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);await review(page);expect((await pkg(page)).system.characterTemplate).toEqual(JSON.parse(before).system.characterTemplate);
});
test('14A.3 Compor seleciona definição, não joga; Experimentar não edita layout',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue();const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await frame.getByLabel('Base',{exact:true}).click();await expect(page.locator('[role=treeitem][data-pointer="/layouts/0/tabs/0/sections/0/containers/0/components/1"]')).toHaveAttribute('aria-selected','true');expect(await page.locator('#editor-json').inputValue()).toBe(before);
 await frame.getByLabel('Base',{exact:true}).press('9');await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('2');await frame.getByLabel('Base',{exact:true}).press('Escape');await frame.getByLabel('Base',{exact:true}).press('7');await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('2');
 await page.getByRole('button',{name:'Experimentar',exact:true}).click();await frame.getByLabel('Base',{exact:true}).fill('9');await expect(frame.locator('.engine-computed__value')).toContainText('10');expect(await page.locator('#editor-json').inputValue()).toBe(before);await expect(page.locator('.editor-forms')).toBeHidden();await page.getByRole('button',{name:'Compor',exact:true}).click();await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('9');
});

test('14B.1 mover por nomes, teclado, cancelar e undo sem índices técnicos',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue();await page.getByRole('treeitem',{name:'Componente · Nome',exact:true}).click();const move=page.locator('.editor-movement');await move.getByLabel('Posição entre os blocos',{exact:true}).selectOption({label:'No fim'});await move.getByRole('button',{name:'Revisar movimento',exact:true}).press('Enter');await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);await move.getByRole('button',{name:'Revisar movimento',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();expect((await pkg(page)).layouts[0].tabs[0].sections[0].containers[0].components.at(-1).label).toBe('Nome');await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);
});
test('14B.2 arrasto de existente e novo usa os mesmos planos e ignora drop externo',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue(),group=page.getByRole('treeitem',{name:'Grupo · Grupo 1',exact:true}),source=page.getByRole('treeitem',{name:'Componente · Nome',exact:true});await source.dragTo(group);await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');await expect(page.getByRole('dialog')).toHaveCount(0);expect((await pkg(page)).layouts[0].tabs[0].sections[0].containers[0].components.at(-1).label).toBe('Nome');await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);
 await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 2');await page.locator('[data-toolbox-type="text"]').dragTo(group);await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 3');const after=await page.locator('#editor-json').inputValue();expect((await pkg(page)).layouts[0].tabs[0].sections[0].containers[0].components.at(-1).label).toBe('Texto curto');await group.dispatchEvent('drop',{dataTransfer:await page.evaluateHandle(()=>{const data=new DataTransfer();data.setData('application/x-ficha-authoring-token','externo');return data;})});expect(await page.locator('#editor-json').inputValue()).toBe(after);
});

test('14B.2 alça no canvas move definição e Escape cancela sem jogar',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue(),frame=page.frameLocator('.editor-preview-frame:not([hidden])');await frame.getByLabel('Nome',{exact:true}).click();const handle=frame.getByRole('button',{name:'Arrastar definição deste bloco',exact:true});await expect(handle).toBeVisible();const from=await handle.boundingBox(),to=await frame.getByLabel('Base',{exact:true}).boundingBox();await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:8});await page.keyboard.press('Escape');await page.mouse.up();expect(await page.locator('#editor-json').inputValue()).toBe(before);await expect(page.getByRole('dialog')).toHaveCount(0);
});
