import {test,expect} from '@playwright/test';
import {minimalPackage} from '../../js/editor/minimal-package.js';
const upload=pkg=>({name:'apply.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))});
async function ready(page){await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.evaluate(()=>navigator.serviceWorker.ready);await page.getByRole('button',{name:'Sistemas',exact:true}).click();}
async function edit(page,pkg){await page.locator('#systems-list .library-card').filter({hasText:pkg.system.name}).getByRole('button',{name:'Editar pacote',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0');}
async function change(page,pkg){await page.locator('#editor-json').fill(JSON.stringify(pkg,null,2));await page.getByRole('button',{name:'Atualizar / reiniciar ensaio'}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');await expect(page.getByRole('button',{name:'Aplicar pacote',exact:true})).toBeEnabled();}
const library=page=>page.evaluate(()=>Object.fromEntries(Object.entries(localStorage).filter(([key])=>key.startsWith('ficha-rpg:')&&!key.startsWith('ficha-rpg:editor:')&&!['ficha-rpg:v2:app-session','ficha-rpg:last-tab'].includes(key))));
test('instalar/cancelar/sair; undo JSON não desfaz instalação',async({page})=>{
  await ready(page);await page.getByRole('button',{name:'Criar pacote'}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0');const pkg=JSON.parse(await page.locator('#editor-json').inputValue());const before=await library(page);
  await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();expect(await library(page)).toEqual(before);
  await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await page.getByRole('button',{name:'Confirmar aplicação'}).click();await expect(page.locator('#editor-application-status')).toContainText('Pacote aplicado');
  await page.locator('#editor-json').fill('{ invalid');await page.getByRole('button',{name:'Desfazer JSON'}).click();expect(await page.evaluate(id=>JSON.parse(localStorage.getItem('ficha-rpg:v2:systems')).some(pkg=>pkg.system.id===id),pkg.system.id)).toBe(true);
  await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.getByRole('button',{name:'Sair do editor'}).click();await expect(page.locator('#systems-list')).toContainText(pkg.system.name);
});
test('substituição preserva dados atuais/null/ausência/extras, omissões e fallback de layout',async({page})=>{
  await ready(page);const pkg=minimalPackage('preserve-test','Preservar');pkg.layouts.push({...structuredClone(pkg.layouts[0]),id:'second'});await page.locator('#input-import-system').setInputFiles(upload(pkg));await expect(page.locator('#systems-list')).toContainText('Preservar');await page.locator('#systems-list .library-card').filter({hasText:'Preservar'}).getByRole('button',{name:'Abrir',exact:true}).click();await page.locator('#sheet-layout-select').selectOption('second');
  await page.evaluate(async()=>{const {state}=await import('/js/state.js');state.get().nil=null;state.get().extra={zero:0,off:false,empty:'',nil:null};state.get().omitted='continua';state.notify();});await expect(page.locator('#save-indicator')).toHaveText('Salvo');
  const before=await page.evaluate(async()=>({state:structuredClone((await import('/js/state.js')).state.get()),raw:(await import('/js/repositories/character-repository.js')).rawCharacter((await import('/js/state.js')).state.get().meta.id)}));
  await page.getByRole('button',{name:'Sistemas',exact:true}).click();await edit(page,pkg);pkg.layouts.pop();pkg.system.name='Preservar atualizado';pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'number',field:'newDefault',default:7,label:'Novo default'},{type:'number',field:'nil',default:8,label:'Nulo'},{type:'list',field:'missingList',label:'Lista nova',itemSchema:{name:{type:'text',label:'Entrada'}}});
  await change(page,pkg);await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('second');await page.getByRole('button',{name:'Confirmar aplicação'}).click();await expect(page.locator('#editor-application-status')).toContainText('Pacote aplicado');
  expect(await page.evaluate(async()=>structuredClone((await import('/js/state.js')).state.get()))).toEqual(before.state);expect(await page.evaluate(async()=>{const api=await import('/js/repositories/character-repository.js');return api.rawCharacter((await import('/js/state.js')).state.get().meta.id);})).toBe(before.raw);
  await page.getByRole('button',{name:'Sair do editor'}).click();await page.getByRole('button',{name:'Ficha atual',exact:true}).click();await expect(page.locator('#sheet-layout-select')).toHaveValue('default');await page.locator('#generic-sheet-host').getByLabel('Base',{exact:true}).fill('9');await expect(page.locator('#save-indicator')).toHaveText('Salvo');
  const current=await page.evaluate(async()=>structuredClone((await import('/js/state.js')).state.get()));expect(current.nil).toBeNull();expect(current.omitted).toBe('continua');expect(current.extra).toEqual(before.state.extra);expect(current).not.toHaveProperty('newDefault');expect(current).not.toHaveProperty('missingList');
  await page.locator('#btn-undo-edit').click();await expect(page.locator('#generic-sheet-host').getByLabel('Base',{exact:true})).toHaveValue('2');
  expect(await page.evaluate(async()=>{const api=await import('/js/persistence.js');return api.recoveryEntries().some(entry=>JSON.parse(entry.raw)?.some?.(item=>item.system?.name==='Preservar'));})).toBe(true);
});
test('edição durante confirmação invalida revisão, sem write na biblioteca',async({page})=>{
  await ready(page);await page.getByRole('button',{name:'Criar pacote'}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0');const before=await library(page);await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();
  await page.locator('#editor-json').evaluate(node=>{node.value='{ changed';node.dispatchEvent(new Event('input',{bubbles:true}));});await page.getByRole('button',{name:'Confirmar aplicação'}).click();await expect(page.locator('#editor-status')).toContainText('mudou');expect(await library(page)).toEqual(before);
});
test('conflito entre abas e novos vinculados durante confirmação são recusados',async({page,context})=>{
  await ready(page);const pkg=minimalPackage('conflict-apply','Conflito');await page.locator('#input-import-system').setInputFiles(upload(pkg));await expect(page.locator('#systems-list')).toContainText('Conflito');await edit(page,pkg);pkg.system.name='Conflito editado';await change(page,pkg);await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();
  const second=await context.newPage();await ready(second);await second.evaluate(async pkg=>await(await import('/js/repositories/character-repository.js')).createCharacter(pkg.system),pkg);await page.getByRole('button',{name:'Confirmar aplicação'}).click();await expect(page.locator('#editor-status')).toContainText('mudou');
  await second.evaluate(async pkg=>{const api=await import('/js/repositories/system-repository.js');pkg.system.name='Outra aba';await api.installSystemPackage(api.prepareSystemInstallation(pkg));},pkg);
  await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('desde a abertura');expect(await page.locator('#editor-json').inputValue()).toContain('Conflito editado');
});
test('quota durante aplicação reverte pacote/preferências/recuperação e preserva rascunho',async({page})=>{
  await ready(page);const pkg=minimalPackage('quota-apply','Quota apply');await page.locator('#input-import-system').setInputFiles(upload(pkg));await expect(page.locator('#systems-list')).toContainText('Quota apply');await edit(page,pkg);pkg.system.name='Novo';await change(page,pkg);await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');const before=await library(page);
  await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='ficha-rpg:v2:systems')throw new DOMException('quota','QuotaExceededError');return original.call(this,key,value);};});
  await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await page.getByRole('button',{name:'Confirmar aplicação'}).click();await expect(page.locator('#editor-status')).toContainText('Falha ao gravar');expect(await library(page)).toEqual(before);await expect(page.locator('#editor-json')).toHaveValue(JSON.stringify(pkg,null,2));
});
test('falha de remontagem é informada como pacote salvo, sem rollback fictício',async({page})=>{
  await ready(page);const pkg=minimalPackage('mount-failure','Montagem');await page.locator('#input-import-system').setInputFiles(upload(pkg));await expect(page.locator('#systems-list')).toContainText('Montagem');await page.locator('#systems-list .library-card').filter({hasText:'Montagem'}).getByRole('button',{name:'Abrir',exact:true}).click();await page.getByRole('button',{name:'Sistemas',exact:true}).click();await edit(page,pkg);pkg.system.name='Salvo';await change(page,pkg);
  await page.evaluate(()=>{const append=Element.prototype.appendChild;Element.prototype.appendChild=function(node){if(this.id==='generic-sheet-host')throw new Error('Falha de montagem simulada');return append.call(this,node);};});
  await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await page.getByRole('button',{name:'Confirmar aplicação'}).click();await expect(page.locator('#editor-application-status')).toContainText('Pacote salvo, ficha não remontada');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ficha-rpg:v2:systems'))[0].system.name)).toBe('Salvo');
});
