import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
test('T07/T10 orçamento: 4 MiB, profundidade 32, 100000 valores e repeat 10000',async({page},testInfo)=>{
 test.setTimeout(120000);await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');
 const measurements=await page.evaluate(async()=>{
  const {EditorSession}=await import('/js/editor/session.js'),{minimalPackage}=await import('/js/editor/minimal-package.js'),{FormView}=await import('/js/editor/form-view.js'),{PreviewHost}=await import('/js/editor/preview-host.js'),{inspectJson}=await import('/js/validation/limits.js');
  const now=()=>performance.now(),count=value=>{let nodes=0,stack=[value];while(stack.length){const v=stack.pop();nodes++;if(v&&typeof v==='object')stack.push(...Object.values(v));}return nodes;},summary=samples=>{const sorted=[...samples].sort((a,b)=>a-b);return {samples,median:sorted[Math.floor(sorted.length/2)],worst:sorted.at(-1)};};
  const bytes=minimalPackage('four-mib');bytes.extra=Array.from({length:40},()=> 'x'.repeat(100000));let text=JSON.stringify(bytes);text+=' '.repeat(4*1024**2-text.length);const valid=[],forms=[],visual=[];
  for(let i=0;i<3;i++){let start=now();const session=new EditorSession({text});valid.push(now()-start);if(session.validation.status!=='ready')throw Error('4 MiB não preservados');const node=document.createElement('section');document.body.append(node);const view=new FormView(node,{session,onChange(){},onPending(){},confirm:async()=>false});start=now();view.refresh(true);forms.push(now()-start);view.visual=true;session.ui.mode='visual';start=now();view.refresh(true);visual.push(now()-start);if(session.text!==text)throw Error('Visita modificou o documento');node.remove();}
  const deep=minimalPackage('depth');let branch=deep;for(let i=0;i<32;i++)branch=branch.extra={};const depthIssues=inspectJson(deep,'package');branch.extra={};const depthOver=inspectJson(deep,'package');
  const dense=minimalPackage('nodes');dense.system.characterTemplate.values={};let remaining=100000-count(dense),bucket=0;while(remaining>1){const length=Math.min(9999,remaining-1);dense.system.characterTemplate.values['grupo'+bucket++]=Object.fromEntries(Array.from({length},(_,i)=>['valor'+i,0]));remaining-=length+1;}if(remaining)dense.extra=0;const nodeCount=count(dense),start=now(),denseSession=new EditorSession({text:JSON.stringify(dense)}),denseValidateMs=now()-start;const denseHost=document.createElement('div');document.body.append(denseHost);denseSession.ui.mode='visual';const denseView=new FormView(denseHost,{session:denseSession,onChange(){},onPending(){},confirm:async()=>false});denseView.visual=true;const denseStart=now();denseView.refresh(true);const denseComposeMs=now()-denseStart;denseHost.remove();dense.extraOver=0;const nodesOver=inspectJson(dense,'package');
  const repeat=minimalPackage('repeat-budget');repeat.system.catalog=Array.from({length:10000},(_,i)=>({key:'k'+i}));repeat.system.characterTemplate.values={};repeat.layouts[0].tabs[0].sections[0].containers=[{id:'repeat',repeat:{source:'catalog'},components:[{type:'text',field:'values.{key}',label:'Entrada {index}'}]}];const hostNode=document.createElement('div');hostNode.id='repeat-budget';document.body.append(hostNode);const host=new PreviewHost(hostNode),mountStart=now();await host.mount(repeat,{revision:1,layoutId:'default'});const repeatMountMs=now()-mountStart,compose=[];for(let i=0;i<3;i++){const start=now();host.compose(true);const geometry=await host.geometry();compose.push(now()-start);host.compose(false);await host.snapshot();if(!geometry.length)throw Error('Repeat não oferece geometria de composição');}window.visualPerfHost=host;
  return {fourMiB:{validate:summary(valid),forms:summary(forms),compose:summary(visual)},depth32:depthIssues,depthOver,nodeCount,denseStatus:denseSession.validation.status,denseValidateMs,denseComposeMs,nodesOver,repeatMountMs,repeatCompose:summary(compose)};
 });
 expect(measurements.depth32).toEqual([]);expect(measurements.depthOver).toHaveLength(1);expect(measurements.nodeCount).toBe(100000);expect(measurements.denseStatus).toBe('ready');expect(measurements.nodesOver).toHaveLength(1);await expect(page.frameLocator('#repeat-budget iframe').locator('input[type=text]')).toHaveCount(10000);await writeFile(testInfo.outputPath('visual-performance.json'),JSON.stringify(measurements,null,2));await page.evaluate(()=>{window.visualPerfHost.dispose();document.querySelector('#repeat-budget').remove();});
});
