import {minimalPackage} from '../../js/editor/minimal-package.js';
import {test,expect} from '@playwright/test';
const open=async page=>{await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.getByRole('button',{name:'Criar pacote',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0');await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();};
const row=(page,pointer)=>page.locator('.editor-property').filter({has:page.locator('strong')}).locator('xpath=self::*[@data-property="'+pointer+'"]');
const property=(page,pointer)=>page.locator('[data-property="'+pointer+'"]');
test('13A estrutura, identidade, histórico comum e JSON inválido preservado',async({page})=>{
  await open(page);const before=await page.locator('#editor-json').inputValue();
  await page.getByRole('treeitem',{name:'Aba · Ficha',exact:true}).click();await page.getByRole('button',{name:'Duplicar bloco',exact:true}).click();
  expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[1].id).toBe('main-copia');
  await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);
  await page.getByRole('treeitem',{name:'Componente · Nome',exact:true}).click();const label=property(page,'/layouts/0/tabs/0/sections/0/containers/0/components/0/label');await label.getByLabel('Rótulo',{exact:true}).fill('Novo nome');await label.getByRole('button',{name:'Aplicar campo',exact:true}).click();
  expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[0].sections[0].containers[0].components[0].label).toBe('Novo nome');
  await page.getByRole('button',{name:'Editar JSON',exact:true}).click();await page.locator('#editor-json').fill('{ invalid');await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();await expect(page.locator('#editor-json')).toBeVisible();await expect(page.locator('#editor-json')).toHaveValue('{ invalid');
});
test('13A texto numérico pendente sobrevive alternância e recuperação',async({page})=>{
  await open(page);await page.getByRole('treeitem',{name:'Sistema · Sistema',exact:true}).click();const field=property(page,'/system/schemaVersion');await field.getByLabel('Versão do documento',{exact:true}).fill('abc');await field.getByRole('button',{name:'Aplicar campo',exact:true}).click();await expect(field).toContainText('representável');
  await page.getByRole('button',{name:'Editar JSON',exact:true}).click();await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();await expect(property(page,'/system/schemaVersion').getByLabel('Versão do documento',{exact:true})).toHaveValue('abc');
  await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');
  expect(await page.evaluate(()=>Object.entries(localStorage).find(([k])=>k.startsWith('ficha-rpg:editor:v1:draft:'))?.[1])).toContain('abc');await expect(page.getByRole('button',{name:'Exportar pacote',exact:true})).toBeDisabled();
});

const put=async(page,pointer,value)=>{const control=property(page,pointer);await control.locator(':scope > input, :scope > textarea').first().fill(value);await control.getByRole('button',{name:'Aplicar campo',exact:true}).first().click();};
const expand=async(page,pointer)=>{const details=page.locator('[data-nested="'+pointer+'"]');if(await details.getAttribute('open')===null)await details.locator(':scope > summary').click();};
test('13B criar coleção, itemSchema e fórmula sem escrever JSON, exportar preservando extras',async({page})=>{
  await open(page);const base='/layouts/0/tabs/0/sections/0/containers/0';
  await page.getByRole('treeitem',{name:'Grupo · Grupo 1',exact:true}).click();await page.getByLabel('Tipo do novo componente').selectOption('list');await page.getByRole('button',{name:'Adicionar componente',exact:true}).click();const comp=base+'/components/4';
  await put(page,comp+'/field','items');const schema=property(page,comp+'/itemSchema');await schema.getByLabel('Estado de Campos dos itens').selectOption('value');await schema.getByRole('button',{name:'Aplicar campo',exact:true}).first().click();await expand(page,comp+'/itemSchema');
  await page.getByLabel('Nova chave em '+comp+'/itemSchema',{exact:true}).fill('name');await page.locator('[data-nested="'+comp+'/itemSchema"]').getByRole('button',{name:'Adicionar propriedade',exact:true}).last().click();await expand(page,comp+'/itemSchema/name');const type=property(page,comp+'/itemSchema/name/type');await type.getByLabel('Tipo',{exact:true}).selectOption('text');await type.getByRole('button',{name:'Aplicar campo',exact:true}).click();await put(page,comp+'/itemSchema/name/label','Nome do item');
  await page.getByRole('treeitem',{name:'Sistema · Sistema',exact:true}).click();await expand(page,'/system/formulas');await put(page,'/system/formulas/total','score * 3');
  await page.getByRole('button',{name:'Validar JSON',exact:true}).click();await expect(page.locator('#editor-validation-summary')).toContainText('Contrato válido');
  await page.getByRole('button',{name:'Atualizar / reiniciar ensaio'}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar pacote',exact:true}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toContain('.system.json');const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.layouts[0].tabs[0].sections[0].containers[0].components[4].itemSchema.name.label).toBe('Nome do item');expect(pkg.system.formulas.total).toBe('score * 3');
});
test('13B valores tipados do template e opções mantêm null/0/false/vazio',async({page})=>{
  await open(page);await expand(page,'/system/characterTemplate');for(const [name,type,raw]of [['nil','null',''],['zero','number','0'],['no','boolean','false'],['empty','string','']]){
    await page.getByLabel('Nova chave em /system/characterTemplate',{exact:true}).fill(name);await page.locator('[data-nested="/system/characterTemplate"] > div').getByRole('button',{name:'Adicionar propriedade',exact:true}).last().click();const p=property(page,'/system/characterTemplate/'+name);await p.getByLabel('Tipo de valor de '+name).selectOption(type);if(type==='boolean')await p.getByLabel(name,{exact:true}).selectOption(raw);else if(raw)await p.getByRole('textbox').fill(raw);await p.getByRole('button',{name:'Aplicar campo',exact:true}).first().click();
  }
  const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.system.characterTemplate).toMatchObject({nil:null,zero:0,no:false,empty:''});
});

test('13C criar teste com fonte, vincular e experimentar sem JSON',async({page})=>{
  await open(page);const checks=property(page,'/system/checks');await checks.getByLabel('Estado de Testes').selectOption('value');await checks.getByRole('button',{name:'Aplicar campo',exact:true}).first().click();await expand(page,'/system/checks');await page.getByLabel('Nova chave em /system/checks',{exact:true}).fill('custom');await page.locator('[data-nested="/system/checks"] > div').getByRole('button',{name:'Adicionar propriedade',exact:true}).last().click();await expand(page,'/system/checks/custom');
  const algorithm=property(page,'/system/checks/custom/algorithm');await algorithm.getByLabel('Algoritmo',{exact:true}).selectOption('fate');await algorithm.getByRole('button',{name:'Aplicar campo',exact:true}).click();await put(page,'/system/checks/custom/note','A mesa decide a dificuldade e as consequências.');const sources=property(page,'/system/checks/custom/sources');await sources.getByLabel('Estado de Fontes').selectOption('value');await sources.getByRole('button',{name:'Aplicar campo',exact:true}).first().click();await expand(page,'/system/checks/custom/sources');await page.locator('[data-nested="/system/checks/custom/sources"] > div').getByRole('button',{name:'Adicionar entrada',exact:true}).click();await expand(page,'/system/checks/custom/sources/0');await put(page,'/system/checks/custom/sources/0/label','Base');await put(page,'/system/checks/custom/sources/0/field','score');
  await page.getByRole('treeitem',{name:'Grupo · Grupo 1',exact:true}).click();await page.getByLabel('Tipo do novo componente').selectOption('checkRoll');await page.getByRole('button',{name:'Adicionar componente',exact:true}).click();await put(page,'/layouts/0/tabs/0/sections/0/containers/0/components/4/configFrom','checks.custom');
  await page.getByRole('button',{name:'Atualizar / reiniciar ensaio'}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await expect(frame.getByText('A mesa decide a dificuldade e as consequências.',{exact:true})).toBeVisible();
});
test('13C renomear fórmula mostra impacto, conserva extras e desfaz atomicamente',async({page})=>{
  await open(page);await expand(page,'/system/formulas');await page.getByLabel('Nova chave de total',{exact:true}).fill('result');await page.getByRole('button',{name:'Renomear total',exact:true}).click();await expect(page.locator('[role="dialog"]')).toContainText('usos conhecidos');await page.locator('[role="dialog"]').getByRole('button',{name:'Confirmar alteração',exact:true}).click();
  let pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.system.formulas.result).toBe('score + 1');expect(pkg.layouts[0].tabs[0].sections[0].containers[0].components[3]).toMatchObject({formula:'result',overrideKey:'total'});await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.system.formulas.total).toBe('score + 1');expect(pkg.layouts[0].tabs[0].sections[0].containers[0].components[3].overrideKey).toBeUndefined();
});

function advancedPackage(){const pkg=minimalPackage('advanced-forms');pkg.schemaVersion=2;pkg.system.schemaVersion=2;pkg.layouts[0].schemaVersion=2;pkg.system.characterTemplate.schemaVersion=2;pkg.system.characterTemplate.activeEffects=[];pkg.system.characterTemplate.items=[{id:'one',name:'Teste'}];pkg.system.characterTemplate.flags={consume:false};pkg.extra={nil:null,zero:0,no:false,empty:'',array:[]};
  pkg.system.checks={custom:{algorithm:'fate',note:'A mesa confirma.',sources:[{id:'score',label:'Base',field:'score'}]}};
  pkg.system.entryRolls={demo:{buttonLabel:'Usar',check:{expression:{value:'1d6'},enabled:true},effect:{expression:{value:'1d6'}},resource:{field:'health.current',mode:'remaining',cost:{value:1},consumeField:'flags.consume'},extensions:{sentinel:false}}};
  pkg.system.recoveryActions=[{id:'rest',label:'Descanso',operations:[{type:'restoreValue',field:'health.current',maxField:'health.max'}]}];pkg.system.sheetActions=[{id:'bonus',label:'Bônus',operations:[{type:'add',field:'score',amount:1}]}];pkg.system.effectDefinitions=[{id:'boost',revision:1,label:'Impulso',stacking:'unique',applicability:'always',duration:{type:'manual'},operations:[{type:'add',value:1,target:{kind:'checkModifier',key:'custom',unit:'total'}}]}];
  pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'list',field:'items',label:'Itens',itemSchema:{name:{type:'text',label:'Nome'}},entryAction:'roll',rollPreset:'demo'},{type:'recoveryGroup',actionsFrom:'recoveryActions',historyField:'scene.recovery'},{type:'actionGroup',actionsFrom:'sheetActions'},{type:'effectList'});return pkg;}
const load=async(page,pkg)=>{await page.getByRole('button',{name:'Editar JSON',exact:true}).click();await page.locator('#editor-json').fill(JSON.stringify(pkg,null,2));await expect(page.locator('#editor-validation-summary')).toContainText('Contrato válido');await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();};
test('13C entryRolls/consumo, recuperação, ação e efeito editam regras compartilhadas preservando extras',async({page})=>{
  test.setTimeout(90000);await open(page);await load(page,advancedPackage());
  await expand(page,'/system/entryRolls');await expand(page,'/system/entryRolls/demo');await expand(page,'/system/entryRolls/demo/resource');await expand(page,'/system/entryRolls/demo/resource/cost');await put(page,'/system/entryRolls/demo/resource/cost/value','0');
  await expand(page,'/system/recoveryActions');await expand(page,'/system/recoveryActions/0');await expand(page,'/system/recoveryActions/0/operations');await expand(page,'/system/recoveryActions/0/operations/0');await put(page,'/system/recoveryActions/0/operations/0/label','Recuperar vida');
  await expand(page,'/system/sheetActions');await expand(page,'/system/sheetActions/0');await expand(page,'/system/sheetActions/0/operations');await expand(page,'/system/sheetActions/0/operations/0');await put(page,'/system/sheetActions/0/operations/0/amount','2');
  await expand(page,'/system/effectDefinitions');await expand(page,'/system/effectDefinitions/0');await expand(page,'/system/effectDefinitions/0/operations');await expand(page,'/system/effectDefinitions/0/operations/0');await put(page,'/system/effectDefinitions/0/operations/0/value','3');
  await page.getByRole('button',{name:'Atualizar / reiniciar ensaio'}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.system.entryRolls.demo.resource.cost.value).toBe(0);expect(pkg.system.entryRolls.demo.resource.consumeField).toBe('flags.consume');expect(pkg.system.entryRolls.demo.extensions.sentinel).toBe(false);expect(pkg.system.sheetActions[0].operations[0].amount).toBe(2);expect(pkg.system.effectDefinitions[0].operations[0].value).toBe(3);expect(pkg.extra).toEqual({nil:null,zero:0,no:false,empty:'',array:[]});
  const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await frame.getByRole('button',{name:'Bônus',exact:true}).click();await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('4');
});
test('13C módulos autorais têm formulários próprios e mantêm tabelas e dados reais',async({page})=>{
  test.setTimeout(60000);await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.locator('#systems-list .library-card').filter({hasText:'Sistema de RPG'}).getByRole('button',{name:'Editar cópia',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();const original=JSON.parse(await page.locator('#editor-json').inputValue());
  await expand(page,'/system/pointBudget');await expand(page,'/system/pointBudget/sources');await expand(page,'/system/pointBudget/sources/0');await put(page,'/system/pointBudget/sources/0/baseDie','6');await expand(page,'/system/repertoire');await put(page,'/system/repertoire/linkField','specializationId');await expand(page,'/system/techniqueUse');await expand(page,'/system/techniqueUse/modes');await expand(page,'/system/techniqueUse/modes/0');await put(page,'/system/techniqueUse/modes/0/label','Receita da mesa');
  const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.system.pointBudget.sources[0].baseDie).toBe(6);expect(pkg.system.techniqueUse.modes[0].label).toBe('Receita da mesa');expect(pkg.system.energyCostByDie).toEqual(original.system.energyCostByDie);expect(pkg.system.characterTemplate).toEqual(original.system.characterTemplate);await page.getByRole('button',{name:'Atualizar / reiniciar ensaio'}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');
});
test('13C teclado, pendência com precisão, seleção no undo e remoção com impacto',async({page})=>{
  await open(page);const tree=page.getByRole('tree');await tree.getByRole('treeitem').first().focus();await page.keyboard.press('End');await expect(tree.getByRole('treeitem').last()).toBeFocused();await page.keyboard.press('Enter');await expect(tree.getByRole('treeitem').last()).toHaveAttribute('aria-selected','true');
  const comp='/layouts/0/tabs/0/sections/0/containers/0/components/3';await put(page,comp+'/label','Soma');await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();await expect(page.getByRole('treeitem',{name:'Componente · Total',exact:true})).toHaveAttribute('aria-selected','true');
  await page.getByRole('treeitem',{name:'Sistema · Sistema',exact:true}).click();await expand(page,'/system/formulas');await page.getByRole('button',{name:'Remover total',exact:true}).click();await expect(page.locator('[role="dialog"]')).toContainText('/layouts/0');await page.locator('[role="dialog"]').getByRole('button',{name:'Cancelar',exact:true}).click();expect(JSON.parse(await page.locator('#editor-json').inputValue()).system.formulas.total).toBe('score + 1');
  const version=property(page,'/system/schemaVersion');await version.getByLabel('Versão do documento',{exact:true}).fill('9007199254740993');await version.getByRole('button',{name:'Aplicar campo',exact:true}).click();await expect(version).toContainText('representável');await page.getByRole('button',{name:'Editar JSON',exact:true}).click();await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();await expect(property(page,'/system/schemaVersion').getByLabel('Versão do documento',{exact:true})).toHaveValue('9007199254740993');
});

test('formulários offline recuperam texto pendente e aplicam pelo fluxo comum',async({page,context})=>{
  test.setTimeout(60000);await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await context.setOffline(true);
  try{await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.getByRole('button',{name:'Criar pacote',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0');await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();await put(page,'/system/name','Criado offline');const version=property(page,'/system/schemaVersion');await version.getByLabel('Versão do documento',{exact:true}).fill('abc');await version.getByRole('button',{name:'Aplicar campo',exact:true}).click();await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.reload();await page.getByRole('button',{name:'Recuperar rascunho',exact:true}).click();await expect(property(page,'/system/schemaVersion').getByLabel('Versão do documento',{exact:true})).toHaveValue('abc');await property(page,'/system/schemaVersion').getByRole('button',{name:'Descartar texto deste campo',exact:true}).click();await page.getByRole('button',{name:'Atualizar / reiniciar ensaio'}).click();await expect(page.getByRole('button',{name:'Aplicar pacote',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Aplicar pacote',exact:true}).click();await page.getByRole('button',{name:'Confirmar aplicação',exact:true}).click();await expect(page.locator('#editor-application-status')).toContainText('Pacote aplicado');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ficha-rpg:v2:systems')).some(pkg=>pkg.system.name==='Criado offline'))).toBe(true);
  }finally{await context.setOffline(false);}
});
test('formulários por toque nas seis paletas, claro/escuro, 360/768/1280 e zoom',async({browser},testInfo)=>{
  test.setTimeout(60000);const context=await browser.newContext({hasTouch:true,viewport:{width:360,height:900}}),page=await context.newPage();await open(page);for(const [width,theme,palette]of [[360,'light','classic'],[360,'dark','editorial'],[768,'light','forest'],[768,'dark','ruby'],[1280,'light','monochrome'],[1280,'dark','petals']]){
    await page.setViewportSize({width,height:900});await page.evaluate(({theme,palette})=>{document.documentElement.dataset.theme=theme;document.documentElement.dataset.palette=palette;},{theme,palette});await page.locator('[role=treeitem][data-pointer="/layouts/0/tabs/0/sections/0/containers/0/components/0"]').tap();const field=property(page,'/layouts/0/tabs/0/sections/0/containers/0/components/0/label');await field.getByLabel('Rótulo',{exact:true}).fill('Nome '+palette);await field.getByRole('button',{name:'Aplicar campo',exact:true}).tap();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('.editor-inspector').screenshot({path:testInfo.outputPath('forms-'+width+'-'+theme+'-'+palette+'.png')});
  }
  await page.evaluate(()=>document.documentElement.style.zoom='2');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await context.close();
});

test('seleção comum da árvore, JSON e prévia; foco e histórico por teclado',async({page})=>{
  await open(page);const pointer='/layouts/0/tabs/0/sections/0/containers/0/components/0',tree=page.locator('[role=treeitem][data-pointer="'+pointer+'"]');await tree.click();
  await page.getByRole('button',{name:'Mostrar na prévia',exact:true}).click();await expect(page.locator('#editor-navigation-status')).toContainText(pointer);
  const preview=page.frameLocator('.editor-preview-frame:not([hidden])');await expect(preview.locator('[data-editor-source-highlight]')).toHaveCount(1);
  await page.getByRole('button',{name:'Localizar no JSON',exact:true}).click();await preview.getByLabel('Base',{exact:true}).click();await expect(page.locator('#editor-json')).toBeFocused();await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();
  await expect(page.locator('[role=treeitem][data-pointer="/layouts/0/tabs/0/sections/0/containers/0/components/1"]')).toHaveAttribute('aria-selected','true');
  await tree.click();const p=property(page,pointer+'/label');await p.getByLabel('Rótulo',{exact:true}).fill('Nome alterado');await p.getByRole('button',{name:'Aplicar campo',exact:true}).click();await expect(p.getByRole('button',{name:'Aplicar campo',exact:true})).toBeFocused();
  await p.getByRole('button',{name:'Aplicar campo',exact:true}).press('Control+z');expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[0].sections[0].containers[0].components[0].label).toBe('Nome');
  await tree.focus();await tree.press('Control+s');await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');
});

test('JSON estrutural incompleto conserva valores e permite remover nó nulo explicitamente',async({page})=>{
  await open(page);await page.getByRole('button',{name:'Editar JSON',exact:true}).click();const broken=minimalPackage('incomplete');broken.system=null;let text=JSON.stringify(broken,null,2);await page.locator('#editor-json').fill(text);await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();await expect(page.locator('#editor-json')).toBeVisible();await expect(page.locator('#editor-json')).toHaveValue(text);
  const pkg=minimalPackage('incomplete');pkg.layouts[0].tabs=null;text=JSON.stringify(pkg,null,2);await page.locator('#editor-json').fill(text);await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();await page.locator('[role=treeitem][data-pointer="/layouts/0"]').click();await page.getByRole('button',{name:'Adicionar aba',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('existente incompatível');expect(await page.locator('#editor-json').inputValue()).toBe(text);
  await page.getByRole('button',{name:'Editar JSON',exact:true}).click();const valid=minimalPackage('incomplete');valid.layouts[0].tabs[0].sections[0].containers[0].components.push(null);text=JSON.stringify(valid,null,2);await page.locator('#editor-json').fill(text);await page.getByRole('button',{name:'Editar por formulários',exact:true}).click();await page.locator('[role=treeitem][data-pointer="/layouts/0/tabs/0/sections/0/containers/0/components/4"]').click();await page.getByRole('button',{name:'Duplicar bloco',exact:true}).click();await expect(page.locator('[role=treeitem][data-pointer="/layouts/0/tabs/0/sections/0/containers/0/components/5"]')).toHaveAttribute('aria-selected','true');await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();await expect(page.locator('[role=treeitem][data-pointer="/layouts/0/tabs/0/sections/0/containers/0/components/4"]')).toHaveAttribute('aria-selected','true');expect(await page.locator('#editor-json').inputValue()).toBe(text);await page.getByRole('button',{name:'Remover bloco',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();await expect(page.locator('#editor-validation-summary')).toContainText('Contrato válido');expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[0].sections[0].containers[0].components).toHaveLength(4);
});
