import {test,expect} from '@playwright/test';
import {minimalPackage} from '../../js/editor/minimal-package.js';
import {CHECK_ALGORITHMS} from '../../js/validation/contracts.js';
import {progressionRecipePlan} from '../../js/editor/progression-plans.js';
import {applyOperations} from '../../js/editor/operations.js';
import {readFile} from 'node:fs/promises';
const openFile=async(page,pkg)=>{await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.locator('#input-editor-file').setInputFiles({name:'exemplo.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg,null,3))});await expect(page.locator('#editor-json')).toBeVisible();await page.getByRole('button',{name:'Compor',exact:true}).click();};
const property=(page,path)=>page.locator('[data-property="'+path+'"]');
const expand=async(page,path)=>{const d=page.locator('[data-nested="'+path+'"]');if(await d.getAttribute('open')===null)await d.locator(':scope > summary').click();};
test('14C.1 reparar system nulo e estrutura incompatível sem editar JSON, undo exato',async({page})=>{
 const pkg=minimalPackage('repair');pkg.system=null;await openFile(page,pkg);const text=await page.locator('#editor-json').inputValue();await expect(page.locator('.editor-inspector')).toContainText('incompatível');await page.getByRole('button',{name:'Reparar system com estrutura inicial',exact:true}).click();await expect(page.locator('#editor-validation-summary')).toContainText('Contrato válido');await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(text);
});
test('14C.1 impressão de seção/grupo e regra em caminho customizado têm controles reais',async({page})=>{
 const pkg=minimalPackage('context');pkg.system.own={commands:[{id:'gain',label:'Ganhar',operations:[{type:'add',field:'score',amount:1}]}]};pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'actionGroup',actionsFrom:'own.commands'});await openFile(page,pkg);await expand(page,'/system/own');await expand(page,'/system/own/commands');await expand(page,'/system/own/commands/0');await expand(page,'/system/own/commands/0/operations');await expand(page,'/system/own/commands/0/operations/0');const amount=property(page,'/system/own/commands/0/operations/0/amount');await amount.getByLabel('Quantidade somada (negativa para gastar)',{exact:true}).fill('3');await amount.getByRole('button',{name:'Aplicar campo',exact:true}).click();expect(JSON.parse(await page.locator('#editor-json').inputValue()).system.own.commands[0].operations[0].amount).toBe(3);
 await page.getByRole('treeitem',{name:'Seção · Personagem',exact:true}).click();const print=property(page,'/layouts/0/tabs/0/sections/0/print');await print.getByLabel('Estado de print',{exact:true}).selectOption('value');await print.getByRole('button',{name:'Aplicar campo',exact:true}).click();await expand(page,'/layouts/0/tabs/0/sections/0/print');const compact=property(page,'/layouts/0/tabs/0/sections/0/print/compact');await compact.getByLabel('Estado de compact',{exact:true}).selectOption('value');await compact.getByRole('button',{name:'Aplicar campo',exact:true}).click();await expand(page,'/layouts/0/tabs/0/sections/0/print/compact');const presentation=property(page,'/layouts/0/tabs/0/sections/0/print/compact/presentation');expect(await presentation.getByLabel('Apresentação compacta',{exact:true}).locator('option').allTextContents()).toEqual(['cards','inline']);
});

test('14C.2 criar catálogo, repeat e selecionar segunda ocorrência sem digitar chave ou caminho',async({page})=>{
 await openFile(page,minimalPackage('catalog-ui'));const panel=page.locator('.editor-data-panel');await panel.locator(':scope > summary').click();await panel.getByLabel('Onde o dado pertence',{exact:true}).selectOption('system');await panel.getByLabel('Nome do novo dado ou catálogo',{exact:true}).fill('Atributos');await panel.getByLabel('Tipo do novo dado',{exact:true}).selectOption('collection');await panel.getByRole('button',{name:'Revisar novo dado',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();
 for(const name of ['Agilidade','Força']){const catalog=panel.locator('details').filter({has:page.locator('summary')}).filter({hasText:'atributos · coleção · do sistema'}).last();if(await catalog.getAttribute('open')===null)await catalog.locator(':scope > summary').click();await catalog.getByLabel('Nome da entrada em atributos',{exact:true}).fill(name);await catalog.getByRole('button',{name:'Acrescentar entrada em atributos',exact:true}).click();}
 const repeat=panel.locator('.editor-repeat-creator');await repeat.locator(':scope > summary').click();await repeat.getByLabel('Catálogo da repetição',{exact:true}).selectOption('atributos');await repeat.getByLabel('Nome do conjunto repetido',{exact:true}).fill('Traços');await repeat.getByLabel('Controle de cada entrada',{exact:true}).selectOption('number');await repeat.getByRole('button',{name:'Revisar conjunto repetido',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await frame.getByLabel('Força',{exact:true}).click();await expect(page.locator('#editor-navigation-status')).toContainText('todas as ocorrências');const label=property(page,'/layouts/0/tabs/0/sections/0/containers/1/components/0/label');await label.getByLabel('Rótulo',{exact:true}).fill('Traço do grupo');await label.getByRole('button',{name:'Aplicar campo',exact:true}).click();const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.system.atributos.map(e=>e.name)).toEqual(['Agilidade','Força']);expect(pkg.layouts[0].tabs[0].sections[0].containers[1].components).toHaveLength(1);
});
test('14C.2 sete tipos de campo de coleção e referências têm inclusão por nome',async({page})=>{
 await openFile(page,minimalPackage('collection-ui'));const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('list');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Contatos');await box.getByRole('button',{name:'Revisar inclusão',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();const schema='/layouts/0/tabs/0/sections/0/containers/0/components/4/itemSchema';await expand(page,schema);for(const type of ['text','textarea','number','boolean','select','die','reference']){await page.getByLabel('Nome do campo da coleção',{exact:true}).fill('Campo '+type);await page.getByLabel('Tipo do campo da coleção',{exact:true}).selectOption(type);if(type==='select')await page.getByLabel('Opções do campo (uma por linha)',{exact:true}).fill('Aliado\nRival');if(type==='reference')await page.getByLabel('Coleção de destino da referência',{exact:true}).selectOption('contatos');await page.getByRole('button',{name:'Criar campo da coleção',exact:true}).click();}const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(Object.values(pkg.layouts[0].tabs[0].sections[0].containers[0].components[4].itemSchema).map(d=>d.type)).toEqual(['text','text','textarea','number','boolean','select','die','reference']);await expect(page.locator('#editor-validation-summary')).toContainText('Contrato válido');
});

test('14C.3 montar Defesa = 10 + Base sem digitar expressão ou caminho',async({page})=>{
 await openFile(page,minimalPackage('formula-ui'));const before=await page.locator('#editor-json').inputValue(),box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('computed');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Defesa');await box.getByLabel('Cálculo compartilhado',{exact:true}).selectOption('');await box.getByLabel('Operação desta parte',{exact:true}).selectOption('+');await box.getByRole('button',{name:'Editar primeiro valor',exact:true}).click();await box.getByLabel('Número desta parte',{exact:true}).fill('10');await box.getByRole('button',{name:'Cálculo inteiro',exact:true}).click();await box.getByRole('button',{name:'Editar segundo valor',exact:true}).click();await box.getByLabel('Operação desta parte',{exact:true}).selectOption('identifier');await box.getByLabel('Fonte desta parte',{exact:true}).selectOption({label:'Base · número · da ficha (score)'});await box.getByRole('button',{name:'Revisar inclusão',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await page.getByRole('button',{name:'Experimentar',exact:true}).click();const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await expect(frame.locator('.engine-computed__value').last()).toHaveText('12');await frame.getByLabel('Base',{exact:true}).fill('4');await expect(frame.locator('.engine-computed__value').last()).toHaveText('14');await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);
});
test('14C.3 texto numérico inválido de fórmula sobrevive seleção, modos e recuperação',async({page})=>{
 await openFile(page,minimalPackage('formula-pending'));const before=await page.locator('#editor-json').inputValue();await expand(page,'/system/formulas');const formula=property(page,'/system/formulas/total');await formula.getByRole('button',{name:'Editar segundo valor',exact:true}).click();await formula.getByLabel('Número desta parte',{exact:true}).fill('abc');await formula.getByRole('button',{name:'Aplicar cálculo construído',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);await page.getByRole('treeitem',{name:'Componente · Base',exact:true}).click();await page.getByRole('button',{name:'Experimentar',exact:true}).click();await page.getByRole('button',{name:'Compor',exact:true}).click();await page.locator('[role=treeitem][data-pointer="/system"]').click();await expect(formula.getByLabel('Número desta parte',{exact:true})).toHaveValue('abc');await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.reload();await page.getByRole('button',{name:'Recuperar rascunho',exact:true}).click();await expect(formula.getByLabel('Número desta parte',{exact:true})).toHaveValue('abc');expect(await page.locator('#editor-json').inputValue()).toBe(before);await formula.getByRole('button',{name:'Descartar texto deste campo',exact:true}).click();await expect(formula.getByLabel('Operação desta parte',{exact:true})).toHaveValue('+');
});
test('14C.3 rolagem composta por grupos e modificador mantém pending inválido',async({page})=>{
 const pkg=minimalPackage('dice-ui');pkg.system.entryRolls={contact:{effect:{expression:{value:'1d6'}}}};pkg.system.characterTemplate.contacts=[];pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'list',label:'Contatos',field:'contacts',itemSchema:{name:{type:'text'}},entryAction:'roll',rollPreset:'contact'});await openFile(page,pkg);for(const p of ['/system/entryRolls','/system/entryRolls/contact','/system/entryRolls/contact/effect','/system/entryRolls/contact/effect/expression'])await expand(page,p);const value=property(page,'/system/entryRolls/contact/effect/expression/value');await value.getByLabel('Quantidade do grupo 1',{exact:true}).fill('2');await value.getByRole('button',{name:'Somar grupo de dados',exact:true}).click();await value.getByLabel('Faces do grupo 2',{exact:true}).fill('8');await value.getByLabel('Modificador inteiro da rolagem',{exact:true}).fill('-2');await value.getByRole('button',{name:'Aplicar rolagem construída',exact:true}).click();expect(JSON.parse(await page.locator('#editor-json').inputValue()).system.entryRolls.contact.effect.expression.value).toBe('2d6 + 1d8 - 2');await value.getByLabel('Quantidade do grupo 1',{exact:true}).fill('oops');await page.getByRole('button',{name:'Experimentar',exact:true}).click();await page.getByRole('button',{name:'Compor',exact:true}).click();await expect(value.getByLabel('Quantidade do grupo 1',{exact:true})).toHaveValue('oops');
});
test('14C.3 condição de bloqueio usa fonte e valor tipado sem JSON',async({page})=>{
 const pkg=minimalPackage('condition-ui');pkg.system.characterTemplate.ready=false;await openFile(page,pkg);await page.getByRole('treeitem',{name:'Componente · Base',exact:true}).click();const condition=property(page,'/layouts/0/tabs/0/sections/0/containers/0/components/1/disabledWhen');await condition.getByLabel('Fonte da condição',{exact:true}).selectOption('ready');await condition.getByLabel('Valor comparado',{exact:true}).selectOption('false');await condition.getByRole('button',{name:'Aplicar condição construída',exact:true}).click();expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[0].sections[0].containers[0].components[1].disabledWhen).toEqual({field:'ready',equals:false});await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await page.getByRole('button',{name:'Experimentar',exact:true}).click();await expect(page.frameLocator('.editor-preview-frame:not([hidden])').getByLabel('Base',{exact:true})).toBeDisabled();
});

test('14C.3 criar variável por nome e usar sua fonte no cálculo sem expressão',async({page})=>{
 await openFile(page,minimalPackage('variable-ui'));await page.getByRole('treeitem',{name:'Componente · Total',exact:true}).click();const vars=property(page,'/layouts/0/tabs/0/sections/0/containers/0/components/3/variables');await vars.getByLabel('Nome da variável',{exact:true}).fill('Agilidade');await vars.getByLabel('Origem da variável',{exact:true}).selectOption('field');await vars.getByLabel('Fonte da variável',{exact:true}).selectOption('score');await vars.getByRole('button',{name:'Criar variável',exact:true}).click();await page.locator('[role=treeitem][data-pointer="/system"]').click();await expand(page,'/system/formulas');const formula=property(page,'/system/formulas/total');await formula.getByRole('button',{name:'Editar primeiro valor',exact:true}).click();await formula.getByLabel('Fonte desta parte',{exact:true}).selectOption({label:'Variável: agilidade'});await formula.getByRole('button',{name:'Aplicar cálculo construído',exact:true}).click();await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await expect(page.frameLocator('.editor-preview-frame:not([hidden])').locator('.engine-computed__value')).toHaveText('3');await page.getByRole('treeitem',{name:'Componente · Total',exact:true}).click();await expand(page,'/layouts/0/tabs/0/sections/0/containers/0/components/3/variables');await vars.getByLabel('Nova chave de agilidade',{exact:true}).fill('Reflexo');await vars.getByRole('button',{name:'Renomear agilidade',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(next.system.formulas.total).toContain('reflexo');expect(next.layouts[0].tabs[0].sections[0].containers[0].components[3].variables.reflexo).toEqual({field:'score'});
});

const confirmRecipe=async page=>{await page.locator('.editor-toolbox').getByRole('button',{name:'Revisar inclusão',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Cancelar conserva');await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();};
const experiment=async page=>{await page.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão');await page.getByRole('button',{name:'Experimentar',exact:true}).click();return page.frameLocator('.editor-preview-frame:not([hidden])');};
test('14C.5 diagnóstico leva ao controle correto em Compor sem abrir JSON',async({page})=>{
 const pkg=minimalPackage('diagnostic-ui');pkg.layouts[0].tabs[0].sections[0].containers[0].components[1].type='counter';pkg.layouts[0].tabs[0].sections[0].containers[0].components[1].min='inválido';await openFile(page,pkg);const before=await page.locator('#editor-json').inputValue();await page.locator('.editor-diagnostics button').filter({hasText:'/components/1/min'}).click();await expect(page.getByRole('button',{name:'Compor',exact:true})).toHaveAttribute('aria-pressed','true');const field=property(page,'/layouts/0/tabs/0/sections/0/containers/0/components/1/min');await expect(field).toBeVisible();expect(await page.locator('#editor-json').inputValue()).toBe(before);await field.getByLabel('Mínimo',{exact:true}).fill('0');await field.getByRole('button',{name:'Aplicar campo',exact:true}).click();await expect(page.locator('#editor-validation-summary')).toContainText('Contrato válido');
});
test('14C.5 ajuda local e relatório explicam amostra sem alterar documento',async({page})=>{
 await openFile(page,minimalPackage('report-ui'));await page.getByRole('treeitem',{name:'Componente · Base',exact:true}).click();await page.locator('.editor-authoring-help summary').click();await expect(page.locator('.editor-authoring-help')).toContainText('Experimentar usa uma amostra isolada');const canonical=await page.locator('#editor-json').inputValue(),frame=await experiment(page);await frame.getByLabel('Base',{exact:true}).fill('0');await page.getByRole('button',{name:'Conferir leituras e resultados',exact:true}).click();const report=page.locator('.editor-experiment-report');await expect(report).toContainText('no momento desta consulta');await expect(report.getByRole('row').filter({has:page.getByRole('cell',{name:'Base',exact:true})})).toContainText('0');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);await page.getByRole('button',{name:'Compor',exact:true}).click();await expect(report).toBeHidden();
});
test('14D.1 organizar cópia de layout mesa, nome, ordem e excluir com impacto explícito',async({page})=>{
 await openFile(page,minimalPackage('layout-manager'));const manager=page.locator('.editor-layout-manager');await manager.locator(':scope > summary').click();await manager.getByLabel('Nome do novo layout',{exact:true}).fill('Mesa');await manager.getByLabel('Apresentação do novo layout',{exact:true}).selectOption('table');await manager.getByRole('button',{name:'Criar cópia nomeada do layout',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();const copied=JSON.parse(await page.locator('#editor-json').inputValue());expect(copied.layouts[1].mode).toBe('table');await manager.getByRole('button',{name:'Subir layout 2',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();await manager.getByRole('button',{name:'Excluir layout 1',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('primeiro layout restante');await page.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts).toHaveLength(2);await manager.getByRole('button',{name:'Excluir layout 1',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(next.layouts).toHaveLength(1);expect(next.layouts[0].id).toBe('default');expect(next.system).toEqual(copied.system);
});
test('14D.2 revisão visual exporta, reimporta em outra biblioteca e aplica pelo fluxo existente',async({page,context})=>{
 const pkg=minimalPackage('visual-roundtrip','Viagem visual');pkg.extra={nil:null,zero:0,no:false,empty:''};await openFile(page,pkg);const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('boolean');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Em perigo');await box.getByLabel('Valor inicial',{exact:true}).selectOption('value');await box.getByLabel('Valor do novo dado',{exact:true}).selectOption('false');await confirmRecipe(page);await experiment(page);const readiness=page.locator('.editor-package-readiness');await readiness.locator(':scope > summary').click();const expected=JSON.parse(await page.locator('#editor-json').inputValue()),downloadPromise=page.waitForEvent('download');await readiness.getByRole('button',{name:'Exportar revisão conferida',exact:true}).click();const download=await downloadPromise,exported=JSON.parse(await readFile(await download.path(),'utf8'));expect(exported).toEqual(expected);expect(exported.extra).toEqual(pkg.extra);expect(exported.system.characterTemplate.em_perigo).toBe(false);expect(exported.ui).toBeUndefined();
 const fresh=await context.browser().newContext();try{const other=await fresh.newPage();await openFile(other,exported);await other.getByRole('button',{name:'Atualizar / reiniciar ensaio',exact:true}).click();await expect(other.getByRole('button',{name:'Aplicar pacote',exact:true})).toBeEnabled();await other.locator('.editor-package-readiness > summary').click();await other.getByRole('button',{name:'Aplicar pelo fluxo da biblioteca',exact:true}).click();await other.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();expect(await other.evaluate(()=>JSON.parse(localStorage.getItem('ficha-rpg:v2:systems')||'[]').some(p=>p.system.id==='visual-roundtrip'))).toBe(false);await other.getByRole('button',{name:'Aplicar pelo fluxo da biblioteca',exact:true}).click();await other.getByRole('dialog').getByRole('button',{name:'Confirmar aplicação',exact:true}).click();await expect(other.locator('#editor-application-status')).toContainText('Pacote aplicado');const installed=await other.evaluate(async()=>await(await import('/js/repositories/system-repository.js')).exportSystemPackage('visual-roundtrip'));expect(installed).toEqual(expected);}finally{await fresh.close();}
});
test('14C.4 módulos assistidos do zero funcionam sem expressão, caminho ou chave',async({page})=>{
 test.setTimeout(90000);await openFile(page,minimalPackage('assisted-recipes'));const box=page.locator('.editor-toolbox');
 const start=async(type,name)=>{await box.getByLabel('O que adicionar',{exact:true}).selectOption(type);await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill(name);};
 await start('slotTracker','Cargas');const before=await page.locator('#editor-json').inputValue();await expect(box.getByLabel('Máximo de usos 1',{exact:true})).toHaveValue('');expect(await page.locator('#editor-json').inputValue()).toBe(before);await box.getByLabel('Máximo de usos 1',{exact:true}).fill('3');await box.getByLabel('Mostrar o recurso como',{exact:true}).selectOption('remaining');await confirmRecipe(page);
 await start('skillCatalog','Perícias');await box.getByLabel('Nome da categoria 1',{exact:true}).fill('Aventura');await box.getByLabel('Perícia 1 da categoria 1',{exact:true}).fill('Nadar');await confirmRecipe(page);
 await start('traitAllocation','Traços');await box.getByLabel('Nome do traço 1',{exact:true}).fill('Agilidade');await box.getByLabel('Nome do conjunto 1',{exact:true}).fill('Ágil');await box.getByLabel('Faces do dado 1 do conjunto 1',{exact:true}).fill('6');await confirmRecipe(page);
 await start('stateList','Desgaste');await box.getByLabel('Oferecer redução e cura de estado',{exact:true}).selectOption('yes');await confirmRecipe(page);
 await start('inventorySummary','Carga');await box.getByLabel('Capacidade base inicial',{exact:true}).fill('4');await box.getByLabel('Multiplicador inicial de carga',{exact:true}).fill('5');await confirmRecipe(page);
 const canonical=await page.locator('#editor-json').inputValue(),frame=await experiment(page);
 await expect(frame.locator('.engine-slot__count')).toHaveText('3 / 3');await frame.getByRole('button',{name:'Reduzir espaços disponíveis do nível 1',exact:true}).click();await expect(frame.locator('.engine-slot__count')).toHaveText('2 / 3');
 await frame.getByRole('button',{name:'Editar perícias',exact:true}).click();await frame.getByLabel('Nadar',{exact:true}).selectOption('6');
 await frame.getByRole('button',{name:'Aplicar conjunto',exact:true}).click();await expect(frame.getByLabel('Agilidade',{exact:true})).toHaveValue('6');
 await expect(frame.getByLabel('Capacidade de carga',{exact:true})).toContainText('20');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
});
test('14C.4 texto pendente nas receitas assistidas sobrevive a modos e seleção',async({page})=>{
 await openFile(page,minimalPackage('assisted-pending'));const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('slotTracker');const before=await page.locator('#editor-json').inputValue();await box.getByLabel('Máximo de usos 1',{exact:true}).fill('a corrigir');await page.getByRole('button',{name:'Experimentar',exact:true}).click();await page.getByRole('button',{name:'Compor',exact:true}).click();await page.getByRole('treeitem',{name:'Componente · Base',exact:true}).click();await expect(box.getByLabel('Máximo de usos 1',{exact:true})).toHaveValue('a corrigir');expect(await page.locator('#editor-json').inputValue()).toBe(before);
});
test('14C.4 criação e repertório completos usam custos e distribuição escolhidos por controles',async({page})=>{
 test.setTimeout(90000);await openFile(page,minimalPackage('progression-recipes'));const box=page.locator('.editor-toolbox');
 await box.getByLabel('O que adicionar',{exact:true}).selectOption('pointBudget');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Progressão');await box.getByLabel('Nome da qualidade 1',{exact:true}).fill('Iniciante');await box.getByLabel('Pontos da qualidade 1',{exact:true}).fill('10');await box.getByLabel('Nome da fonte de pontos 1',{exact:true}).fill('Talentos');for(const step of ['sem dado → d4','d4 → d6','d6 → d8','d8 → d10','d10 → d12'])await box.getByLabel('Custo da fonte 1 '+step,{exact:true}).fill('2');await confirmRecipe(page);
 await box.getByLabel('O que adicionar',{exact:true}).selectOption('repertoire');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Repertório');await box.getByLabel('Mínimo garantido no grau 1',{exact:true}).fill('1');await box.getByLabel('Quantidade 1 no grau 1',{exact:true}).fill('1');await confirmRecipe(page);
 const canonical=await page.locator('#editor-json').inputValue(),frame=await experiment(page);await expect(frame.getByLabel('Pontos de criação',{exact:true})).toHaveText('10');await frame.getByRole('button',{name:'Concluir criação',exact:true}).click();await expect(frame.getByRole('button',{name:'Reabrir criação',exact:true})).toBeVisible();await expect(frame.locator('output[aria-label="Evolução recebida"]')).toHaveText('0');await expect(frame.locator('.engine-repertoire')).toContainText('Adicione uma Especialização');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
});
test('14C.4 Pool cria fonte e cálculo por operações e rola somente em Experimentar',async({page})=>{
 await openFile(page,minimalPackage('pool-recipe'));const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('poolBuilder');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Pool de aventura');await box.getByLabel('Nome do traço no Pool 1',{exact:true}).fill('Apoio');await box.getByLabel('Faces do traço no Pool 1',{exact:true}).fill('6');await box.getByLabel('Número desta parte',{exact:true}).fill('10');await box.getByLabel('Decisões manuais da resolução',{exact:true}).fill('Consequências são decididas pela mesa.');await confirmRecipe(page);const canonical=await page.locator('#editor-json').inputValue(),frame=await experiment(page);await frame.getByRole('checkbox',{name:/^Apoio/}).check();await frame.getByRole('button',{name:'Rolar Pool',exact:true}).click();await expect(frame.locator('.engine-pool__result')).toContainText('Peso');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
});
test('14C.4 técnica do zero gera recursos e debita apenas custo escolhido no ensaio',async({page})=>{
 const pkg=minimalPackage('technique-recipe');pkg.system.dieScale=[4,6,8,10,12];await openFile(page,pkg);const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('techniqueUse');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Técnicas');await box.getByLabel('Nome do atributo de técnicas 1',{exact:true}).fill('Agilidade');await box.getByLabel('Energia atual inicial das técnicas',{exact:true}).fill('5');await box.getByLabel('Energia máxima inicial das técnicas',{exact:true}).fill('10');for(const die of [4,6,8,10,12])await box.getByLabel('Custo de energia d'+die,{exact:true}).fill('1');await box.getByLabel('Nome do modo de técnica 1',{exact:true}).fill('Teste de apoio');await box.getByRole('button',{name:'Acrescentar termo do modo 1',exact:true}).click();await box.getByLabel('Termo 1 do modo 1',{exact:true}).selectOption('constant');await confirmRecipe(page);const canonical=await page.locator('#editor-json').inputValue(),frame=await experiment(page);await frame.getByRole('button',{name:'Usar e rolar',exact:true}).click();await expect(frame.getByLabel('Energia atual',{exact:true})).toHaveValue('4');await expect(frame.locator('.engine-technique-use')).toContainText('1 Energia paga');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
});
test('14C.4 custos consumidos usam tabela visual, preservam extras e texto inválido',async({page})=>{
 const pkg=minimalPackage('cost-table');pkg.system.dieScale=[4,6,8,10,12];const plan=progressionRecipePlan(pkg,{type:'pointBudget',name:'Progressão',destination:['layouts',0,'tabs',0,'sections',0,'containers',0,'components'],config:{presets:[{label:'Iniciante',points:10}],adjustment:0,awarded:0,sources:[{label:'Talentos',baseDie:4,costs:{'0->4':0,'4->6':2,'6->8':3,'8->10':4,'10->12':5,extra:{nil:null}}}]}}),next=JSON.parse(applyOperations(JSON.stringify(pkg),plan.commands));await openFile(page,next);await page.locator('[role=treeitem][data-pointer="/system"]').click();const table=property(page,'/system/talentos_custos');const before=await page.locator('#editor-json').inputValue();await expect(table.getByLabel('Custo d4 → d6',{exact:true})).toHaveValue('2');expect(await page.locator('#editor-json').inputValue()).toBe(before);await table.getByLabel('Custo d4 → d6',{exact:true}).fill('pendente');await page.getByRole('button',{name:'Experimentar',exact:true}).click();await page.getByRole('button',{name:'Compor',exact:true}).click();await expect(table.getByLabel('Custo d4 → d6',{exact:true})).toHaveValue('pendente');await table.getByLabel('Custo d4 → d6',{exact:true}).fill('0.5');await table.getByRole('button',{name:'Aplicar tabela de custos',exact:true}).click();const result=JSON.parse(await page.locator('#editor-json').inputValue());expect(result.system.talentos_custos['4->6']).toBe(0.5);expect(result.system.talentos_custos.extra).toEqual({nil:null});
});
test('14C.4 copiar regra para um consumidor preserva original e outros vínculos',async({page})=>{
 const pkg=minimalPackage('copy-rule');pkg.system.checks={shared:{algorithm:'fate',sources:[{id:'value',label:'Base',field:'score'}],note:'Mesa define consequência.',extensions:{nil:null}}};const comps=pkg.layouts[0].tabs[0].sections[0].containers[0].components;comps.push({type:'checkRoll',label:'Teste primeiro',configFrom:'checks.shared'},{type:'checkRoll',label:'Teste segundo',configFrom:'checks.shared'});await openFile(page,pkg);await page.getByRole('treeitem',{name:'Componente · Teste primeiro',exact:true}).click();await page.getByLabel('Nome da cópia de regra configFrom',{exact:true}).fill('Teste próprio');await page.getByRole('button',{name:'Usar cópia independente: configFrom',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(next.system.checks.teste_proprio).toEqual(pkg.system.checks.shared);expect(next.system.checks.shared).toEqual(pkg.system.checks.shared);expect(next.layouts[0].tabs[0].sections[0].containers[0].components.at(-2).configFrom).toBe('checks.teste_proprio');expect(next.layouts[0].tabs[0].sections[0].containers[0].components.at(-1).configFrom).toBe('checks.shared');
});
test('14C.4 selecionar as oito famílias e rolar os testes gerados sem JSON',async({page})=>{
 test.setTimeout(90000);await openFile(page,minimalPackage('check-recipes'));const box=page.locator('.editor-toolbox');for(const algorithm of CHECK_ALGORITHMS){await box.getByLabel('O que adicionar',{exact:true}).selectOption('checkRoll');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Teste '+algorithm);await box.getByLabel('Família do teste',{exact:true}).selectOption(algorithm);await box.getByLabel('Nome da fonte 1',{exact:true}).fill('Fonte '+algorithm);await box.getByLabel('Origem da fonte 1',{exact:true}).selectOption('new');if(algorithm==='explodingDamage'){await box.getByRole('button',{name:'Somar grupo de dados',exact:true}).click();}else await box.getByLabel('Valor inicial da fonte 1',{exact:true}).fill(algorithm==='explodingTrait'?'4':'2');await box.getByLabel('Decisões que ficam com a mesa neste teste',{exact:true}).fill('Custos e consequências são decisões da mesa.');await confirmRecipe(page);}const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(Object.values(next.system.checks).map(c=>c.algorithm)).toEqual(CHECK_ALGORITHMS);const frame=await experiment(page);for(const check of await frame.locator('.engine-check').all()){await check.getByRole('button',{name:'Rolar teste',exact:true}).click();await expect(check.locator('.engine-check__result')).not.toHaveText('');await expect(check.locator('.engine-check__result')).not.toContainText('informe');}
});
test('14C.4 ação com requisito e recuperação são criadas, canceladas e executadas no ensaio',async({page})=>{
 const pkg=minimalPackage('action-recipes');pkg.system.characterTemplate.ready=true;await openFile(page,pkg);const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('actionGroup');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Gastar');await box.getByLabel('Operação 1',{exact:true}).selectOption('add');await box.getByLabel('Dado alterado pela operação 1',{exact:true}).selectOption('score');await box.getByLabel('Quantidade a somar (negativa para gastar)',{exact:true}).fill('-1');await box.getByLabel('Limite mínimo após somar',{exact:true}).fill('0');await box.getByRole('button',{name:'Acrescentar requisito',exact:true}).click();await box.getByLabel('Fonte da condição',{exact:true}).selectOption('score');await box.getByLabel('Comparação da condição',{exact:true}).selectOption('min');await box.getByLabel('Mínimo necessário',{exact:true}).fill('1');await confirmRecipe(page);await box.getByLabel('O que adicionar',{exact:true}).selectOption('recoveryGroup');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Descanso');await box.getByLabel('Operação 1',{exact:true}).selectOption('restoreValue');await box.getByLabel('Dado alterado pela operação 1',{exact:true}).selectOption('health.current');await box.getByLabel('Máximo deste valor',{exact:true}).selectOption('health.max');await confirmRecipe(page);const canonical=await page.locator('#editor-json').inputValue();const frame=await experiment(page);await frame.getByRole('button',{name:'Gastar',exact:true}).click();await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('1');await frame.getByRole('button',{name:'Gastar',exact:true}).click();await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('0');await frame.getByRole('button',{name:'Gastar',exact:true}).click();await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('0');await frame.getByRole('button',{name:'Descanso',exact:true}).click();await frame.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();await expect(frame.getByLabel('Vida atual',{exact:true})).toHaveValue('5');await frame.getByRole('button',{name:'Descanso',exact:true}).click();await frame.getByRole('dialog').getByRole('checkbox').check();await frame.getByRole('dialog').getByRole('button',{name:'Aplicar recuperação',exact:true}).click();await expect(frame.getByLabel('Vida atual',{exact:true})).toHaveValue('10');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
});
test('14C.4 efeito visual +2 exige habilitação v2 e encerra por evento confirmado',async({page})=>{
 await openFile(page,minimalPackage('effect-recipe'));const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('effectList');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Proteção');await box.getByLabel('Alvo da contribuição 1',{exact:true}).selectOption({label:'Cálculo: Total'});await box.getByLabel('Valor a somar na contribuição 1',{exact:true}).fill('2');await box.getByLabel('Quando o efeito termina',{exact:true}).selectOption('endScene');await box.getByLabel('Documentos versão 2 e controles de efeitos',{exact:true}).selectOption('yes');await confirmRecipe(page);const canonical=await page.locator('#editor-json').inputValue();const frame=await experiment(page);await frame.getByRole('button',{name:'Ativar Proteção',exact:true}).click();await frame.getByRole('dialog').getByRole('button',{name:'Migrar e ativar',exact:true}).click();await expect(frame.locator('.engine-computed__value')).toHaveText('5');await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('2');await frame.getByRole('button',{name:'Confirmar fim de cena',exact:true}).click();await frame.getByRole('dialog').getByRole('button',{name:'Confirmar evento',exact:true}).click();await expect(frame.locator('.engine-computed__value')).toHaveText('3');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
});
test('14C.4 rolagem de entrada com grupos e consumo compartilhado não escreve ao cancelar',async({page})=>{
 const pkg=minimalPackage('entry-recipe');pkg.system.characterTemplate.contacts=[{id:'a',name:'Raio'}];pkg.system.characterTemplate.consume=false;pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'list',label:'Contatos',field:'contacts',itemSchema:{name:{type:'text'}}});await openFile(page,pkg);const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('list');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Técnicas');await box.getByLabel('Uso desta lista',{exact:true}).selectOption('roll');await box.getByLabel('Entradas que oferecem esta rolagem',{exact:true}).selectOption('contacts');await box.getByLabel('Efeito ou dano separado',{exact:true}).selectOption('yes');await box.getByRole('button',{name:'Somar grupo de dados',exact:true}).click();await box.getByLabel('Quantidade do grupo 1',{exact:true}).fill('2');await box.getByLabel('Consumo opcional de recurso',{exact:true}).selectOption('yes');await box.getByLabel('Recurso compartilhado para o consumo',{exact:true}).selectOption('score');await box.getByLabel('Valor informado',{exact:true}).fill('1');await box.getByLabel('Preferência que habilita consumo',{exact:true}).selectOption('consume');await confirmRecipe(page);const canonical=await page.locator('#editor-json').inputValue();const frame=await experiment(page);await frame.getByRole('button',{name:'Técnicas',exact:true}).click();await frame.getByRole('dialog').getByRole('button',{name:'Fechar',exact:true}).click();await expect(frame.getByLabel('Base',{exact:true})).toHaveValue('2');expect(await page.locator('#editor-json').inputValue()).toBe(canonical);
});

test('T03 leituras distintas de cálculo são escolhidas e recuperadas sem inferência',async({page})=>{
 const pkg=minimalPackage('scope-choice'),cs=pkg.layouts[0].tabs[0].sections[0].containers[0].components;cs[3].label='Zero';cs[3].overrideKey='computed.zero';cs[3].variables={score:{value:0}};cs.push({...cs[3],label:'Nove',overrideKey:'computed.nine',variables:{score:{value:9}}});await openFile(page,pkg);const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('computed');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Leitura escolhida');await box.getByLabel('Cálculo compartilhado',{exact:true}).selectOption('total');await box.getByRole('button',{name:'Revisar inclusão',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('#editor-status')).toContainText('Escolha as leituras');await box.getByLabel('Leituras do cálculo selecionado',{exact:true}).selectOption({label:'Nove'});await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.reload();await page.getByRole('button',{name:'Recuperar rascunho',exact:true}).click();await expect(box.getByLabel('Leituras do cálculo selecionado',{exact:true})).toHaveValue('/layouts/0/tabs/0/sections/0/containers/0/components/4/formula');await confirmRecipe(page);const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(next.layouts[0].tabs[0].sections[0].containers[0].components.at(-1).variables).toEqual({score:{value:9}});const frame=await experiment(page);await expect(frame.locator('.engine-computed__value').last()).toHaveText('10');
});
test('T01 imagem local entra no pacote somente na confirmação, com undo e recovery',async({page})=>{
 await openFile(page,minimalPackage('local-image'));const before=await page.locator('#editor-json').inputValue(),box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('image');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Emblema');await box.getByLabel('Imagem local do pacote',{exact:true}).setInputFiles({name:'emblema.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="red"/></svg>')});await expect(box.getByLabel('Valor do novo dado',{exact:true})).toHaveValue(/^data:image\/webp;base64,/);expect(await page.locator('#editor-json').inputValue()).toBe(before);await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.reload();await page.getByRole('button',{name:'Recuperar rascunho',exact:true}).click();await expect(box.getByLabel('Valor do novo dado',{exact:true})).toHaveValue(/^data:image\/webp;base64,/);await confirmRecipe(page);const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(next.system.characterTemplate.emblema).toMatch(/^data:image\/webp;base64,/);const frame=await experiment(page);await expect(frame.locator('img').last()).toHaveJSProperty('naturalWidth',32);await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);
});
test('T07 coleções grandes paginam preservando o índice original e dados não visitados',async({page})=>{
 const pkg=minimalPackage('paged');pkg.system.attributes=Array.from({length:105},(_,i)=>({key:'a'+i,label:'Atributo '+i,extra:i===104?null:false}));pkg.system.characterTemplate.many=Object.fromEntries(Array.from({length:210},(_,i)=>['v'+i,i]));await openFile(page,pkg);await expand(page,'/system/attributes');const collection=property(page,'/system/attributes');await expect(collection).toContainText('Entradas 1–50 de 105');await collection.getByRole('button',{name:'Próximas entradas',exact:true}).click();await expect(collection).toContainText('Entradas 51–100 de 105');await collection.getByRole('button',{name:'Próximas entradas',exact:true}).click();await expect(collection).toContainText('Entradas 101–105 de 105');await expand(page,'/system/attributes/104');const label=property(page,'/system/attributes/104/label');await label.getByLabel('Rótulo',{exact:true}).fill('Último atributo');await label.getByRole('button',{name:'Aplicar campo',exact:true}).click();const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(next.system.attributes[104]).toEqual({...pkg.system.attributes[104],label:'Último atributo'});expect(next.system.attributes.slice(0,104)).toEqual(pkg.system.attributes.slice(0,104));const panel=page.locator('.editor-data-panel');await panel.locator(':scope > summary').click();await panel.getByLabel('Buscar dado ou catálogo por nome',{exact:true}).fill('v209');await expect(panel).toContainText('v209');await expect(panel.getByRole('button',{name:'Próximos dados',exact:true})).toBeDisabled();
});

test('T04 fonte de rolagem escolhe contexto e salva sidecar sem funções',async({page})=>{
 const pkg=minimalPackage('roll-scopes'),cs=pkg.layouts[0].tabs[0].sections[0].containers[0].components;cs[3].label='Zero';cs[3].overrideKey='computed.zero';cs[3].variables={score:{value:0}};cs.push({...cs[3],label:'Nove',overrideKey:'computed.nine',variables:{score:{value:9}}});pkg.system.entryRolls={hit:{effect:{expression:{value:'1d6'}},scale:{base:{value:1},min:1,max:3,increment:{field:'score',fallback:0,extra:{nil:null}}}}};await openFile(page,pkg);for(const path of ['/system/entryRolls','/system/entryRolls/hit','/system/entryRolls/hit/effect','/system/entryRolls/hit/scale','/system/entryRolls/hit/scale/increment'])await expand(page,path);const source=property(page,'/system/entryRolls/hit/scale/increment');await source.getByLabel('Origem deste valor',{exact:true}).selectOption('formula');await source.getByLabel('Fonte deste valor',{exact:true}).selectOption('total');await source.getByLabel('Leituras do cálculo selecionado',{exact:true}).selectOption({label:'Nove'});await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Rascunho salvo');await page.reload();await page.getByRole('button',{name:'Recuperar rascunho',exact:true}).click();await expect(source.getByLabel('Leituras do cálculo selecionado',{exact:true})).toHaveValue('/layouts/0/tabs/0/sections/0/containers/0/components/4/formula');await source.getByRole('button',{name:'Aplicar origem construída',exact:true}).click();expect(JSON.parse(await page.locator('#editor-json').inputValue()).system.entryRolls.hit.scale.increment).toEqual({formula:'total',variables:{score:{value:9}},overrideKey:'computed.computed.nine',fallback:0,extra:{nil:null}});
});
test('T06 receitas D&D reutilizam catálogos e derivados reais sem mudar os originais',async({page})=>{
 const pkg={kind:'rpg-system-package',schemaVersion:1,system:JSON.parse(await readFile('data/systems/dnd2024.system.json','utf8')),layouts:[JSON.parse(await readFile('data/systems/dnd2024.layout.json','utf8'))]};await openFile(page,pkg);const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('dndAbility');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Força adicional');await box.getByLabel('Atributo D&D do catálogo',{exact:true}).selectOption('str');await confirmRecipe(page);await box.getByLabel('O que adicionar',{exact:true}).selectOption('dndSkill');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Acrobacia adicional');await box.getByLabel('Perícia D&D do catálogo',{exact:true}).selectOption('acrobatics');await confirmRecipe(page);await box.getByLabel('O que adicionar',{exact:true}).selectOption('dndDerived');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Proficiência adicional');await confirmRecipe(page);const canonical=JSON.parse(await page.locator('#editor-json').inputValue());expect(canonical.system).toEqual(pkg.system);const frame=await experiment(page);await expect(frame.getByLabel('Valor de Força adicional',{exact:true})).toHaveValue('10');await expect(frame.locator('.engine-dnd-derived').filter({hasText:'Proficiência adicional'}).locator('.engine-dnd-derived__value')).toHaveText('+2');expect(await page.evaluate(async()=>await (await fetch('/data/systems/dnd2024.system.json')).json())).toEqual(pkg.system);
});
