import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
async function downloaded(download){const stream=await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);return JSON.parse(Buffer.concat(chunks).toString());}
test('exportação/reimportação multilayout preserva extras e exclui ensaio; inválido tem comando distinto',async({page,context})=>{
  const pkg=JSON.parse(readFileSync('data/examples/generic-entry-rolls.package.json','utf8'));pkg.extra={nil:null,zero:0,off:false,empty:''};pkg.layouts.push({...structuredClone(pkg.layouts[0]),id:'second'});
  await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.locator('#input-editor-file').setInputFiles({name:'package.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))});await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0');
  const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await frame.getByLabel('Energia',{exact:true}).fill('99');
  const exported=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar pacote',exact:true}).click();const data=await downloaded(await exported);expect(data).toEqual(pkg);
  await page.locator('#editor-json').fill('{ invalid');await expect(page.getByRole('button',{name:'Exportar pacote',exact:true})).toBeDisabled();const old=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar última versão válida',exact:true}).click();expect(await downloaded(await old)).toEqual(pkg);await expect(page.locator('#editor-status')).toContainText('revisão 0');
  const fresh=await context.browser().newContext();const other=await fresh.newPage();await other.goto('/');await expect(other.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await other.getByRole('button',{name:'Sistemas',exact:true}).click();await other.locator('#input-import-system').setInputFiles({name:'exported.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await expect(other.locator('#systems-list')).toContainText(pkg.system.name);await other.locator('#systems-list .library-card').filter({hasText:pkg.system.name}).getByRole('button',{name:'Abrir',exact:true}).click();expect(await other.evaluate(async()=>await(await import('/js/repositories/system-repository.js')).exportSystemPackage('generic-roll-example'))).toEqual(pkg);await fresh.close();
});
