import {minimalPackage} from '../../js/editor/minimal-package.js';
import {test,expect} from '@playwright/test';
const open=async page=>{await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.getByRole('button',{name:'Criar pacote',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0',{timeout:20000});await page.getByRole('button',{name:'Compor',exact:true}).click();};
const drag=async(page,type,pointer,after=true,axis='vertical')=>{const card=page.locator('[data-toolbox-type="'+type+'"]');await page.locator('.editor-preview').scrollIntoViewIfNeeded();await card.scrollIntoViewIfNeeded();const box=await card.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+10,box.y+box.height/2+10,{steps:4});const zone=page.locator('[data-drop-pointer="'+pointer+'"]');await expect(zone).toBeVisible();const r=await zone.boundingBox();await page.mouse.move(r.x+r.width*(axis==='horizontal'?(after?.85:.15):.5),r.y+r.height*(axis==='vertical'?(after?.85:.15):.5),{steps:10});await page.mouse.move(r.x+r.width*(axis==='horizontal'?(after?.85:.15):.5),r.y+r.height*(axis==='vertical'?(after?.85:.15):.5));await expect(zone).toHaveAttribute('data-drop-valid','true');return zone;};
test('T01/B toolbox de cards inclui diretamente no canvas, mostra encaixe e atualiza sem reiniciar',async({page},testInfo)=>{
 await open(page);await expect(page.locator('.editor-toolbox-cards')).toContainText('Textos');await expect(page.locator('.editor-toolbox-cards')).toContainText('Caixas');const before=await page.locator('#editor-json').inputValue();const zone=await drag(page,'text','/layouts/0/tabs/0/sections/0/containers/0/components/0');await expect(zone).toHaveAttribute('data-drop-side','after');await page.screenshot({path:testInfo.outputPath('canvas-encaixe.png')});expect(await page.locator('#editor-json').inputValue()).toBe(before);await page.mouse.up();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');await expect(page.getByRole('dialog')).toHaveCount(0);const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.layouts[0].tabs[0].sections[0].containers[0].components[1].label).toBe('Texto curto');await expect(page.frameLocator('.editor-preview-frame:not([hidden])').getByLabel('Texto curto',{exact:true})).toHaveValue('');await page.screenshot({path:testInfo.outputPath('canvas-incluido.png')});await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 2');
});
test('T02/B seção e caixa grid arrastadas encaixam no canvas, preservando dados e original',async({page})=>{
 await open(page);const before=JSON.parse(await page.locator('#editor-json').inputValue());await drag(page,'section','/layouts/0/tabs/0/sections/0/containers/0/components/0',false);await page.mouse.up();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');const frame=page.frameLocator('.editor-preview-frame:not([hidden])');await expect(frame.getByRole('heading',{name:'Nova seção',exact:true})).toBeVisible();await drag(page,'container-grid','/layouts/0/tabs/0/sections/0/containers/0/components/0',true);await page.mouse.up();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 2');const pkg=JSON.parse(await page.locator('#editor-json').inputValue());expect(pkg.system.characterTemplate.identity).toEqual(before.system.characterTemplate.identity);expect(pkg.system.formulas).toEqual(before.system.formulas);expect(pkg.layouts[0].tabs[0].sections[1]).toEqual(before.layouts[0].tabs[0].sections[0]);expect(pkg.layouts[0].tabs[0].sections[0].containers.some(c=>c.layout.type==='grid'&&c.components[0].type==='text')).toBe(true);await expect(frame.locator('.engine-container--grid')).toContainText('');
});
test('T09/B Escape durante card novo remove indicação sem editar ou jogar',async({page})=>{await open(page);const before=await page.locator('#editor-json').inputValue();await drag(page,'resource','/layouts/0/tabs/0/sections/0/containers/0/components/0');await page.keyboard.press('Escape');await page.mouse.up();await expect(page.locator('.editor-composition-overlay')).toHaveCount(0);expect(await page.locator('#editor-json').inputValue()).toBe(before);await page.getByRole('button',{name:'Experimentar',exact:true}).click();await expect(page.locator('.editor-toolbox-cards')).toBeHidden();});

const openFixture=async(page,pkg)=>{await page.goto('/');await expect(page.locator('#shell-current-system')).toHaveText('D&D 5e (2024)');await page.getByRole('button',{name:'Sistemas',exact:true}).click();await page.locator('#input-editor-file').setInputFiles({name:'canvas.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))});await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 0',{timeout:20000});await page.getByRole('button',{name:'Compor',exact:true}).click();};
test('T09/B movimento direto da definição na prévia atualiza e desfaz sem jogar',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue(),frame=page.frameLocator('.editor-preview-frame:not([hidden])');await frame.getByLabel('Nome',{exact:true}).click();const handle=frame.getByRole('button',{name:'Arrastar definição deste bloco',exact:true});await frame.getByLabel('Base',{exact:true}).scrollIntoViewIfNeeded();const from=await handle.boundingBox(),to=await frame.getByLabel('Base',{exact:true}).boundingBox();await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height*.85,{steps:10});await page.mouse.up();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');const p=JSON.parse(await page.locator('#editor-json').inputValue());expect(p.layouts[0].tabs[0].sections[0].containers[0].components.slice(0,2).map(c=>c.label)).toEqual(['Base','Nome']);expect(p.system).toEqual(JSON.parse(before).system);await page.getByRole('button',{name:'Desfazer JSON',exact:true}).click();expect(await page.locator('#editor-json').inputValue()).toBe(before);
});
test('T01/B grade usa encaixe horizontal e caixa pode ser incluída pelo teclado',async({page})=>{
 const p=minimalPackage('grid-canvas');p.layouts[0].showHeader=false;p.layouts[0].tabs[0].sections[0].containers[0].layout.type='grid';await openFixture(page,p);const zone=await drag(page,'number','/layouts/0/tabs/0/sections/0/containers/0/components/0',true,'horizontal');await expect(zone).toHaveAttribute('data-drop-axis','horizontal');await expect(zone).toHaveAttribute('data-drop-side','after');await page.mouse.up();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[0].sections[0].containers[0].components[1].type).toBe('number');await page.getByRole('treeitem',{name:'Seção · Personagem',exact:true}).click();await page.locator('[data-toolbox-type="container-flex"]').press('Enter');await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 2');expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[0].sections[0].containers[1].layout.type).toBe('flex');
});
test('T02/B arrasto muda de aba sem alterar o documento antes de soltar',async({page})=>{
 const p=minimalPackage('tabs-canvas');p.layouts[0].showHeader=false;const tab=structuredClone(p.layouts[0].tabs[0]);tab.id='other';tab.label='Outra apresentação';tab.sections[0].id='other-section';p.layouts[0].tabs.push(tab);await openFixture(page,p);const before=await page.locator('#editor-json').inputValue(),card=page.locator('[data-toolbox-type="text"]');await page.locator('.editor-preview').scrollIntoViewIfNeeded();await card.scrollIntoViewIfNeeded();const c=await card.boundingBox();await page.mouse.move(c.x+c.width/2,c.y+c.height/2);await page.mouse.down();await page.mouse.move(c.x+c.width/2+10,c.y+c.height/2+10,{steps:4});const tabZone=page.locator('[data-drop-pointer="/layouts/0/tabs/1"]');await expect(tabZone).toBeVisible();const t=await tabZone.boundingBox();await page.mouse.move(t.x+t.width/2,t.y+t.height/2,{steps:10});await page.mouse.move(t.x+t.width/2,t.y+t.height/2);const target=page.locator('[data-drop-pointer="/layouts/0/tabs/1/sections/0/containers/0/components/0"]');await expect(target).toBeVisible();expect(await page.locator('#editor-json').inputValue()).toBe(before);const r=await target.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height*.85,{steps:10});await page.mouse.move(r.x+r.width/2,r.y+r.height*.85);await expect(target).toHaveAttribute('data-drop-valid','true');await page.mouse.up();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');const next=JSON.parse(await page.locator('#editor-json').inputValue());expect(next.layouts[0].tabs[0]).toEqual(p.layouts[0].tabs[0]);expect(next.layouts[0].tabs[1].sections[0].containers[0].components[1].label).toBe('Texto curto');await expect(page.frameLocator('.editor-preview-frame:not([hidden])').getByLabel('Texto curto',{exact:true})).toBeVisible();
});
test('T01/B card com lógica mantém a posição escolhida até confirmar sua receita',async({page})=>{
 await open(page);const before=await page.locator('#editor-json').inputValue();await page.locator('.editor-toolbox-category').filter({has:page.getByText('Cálculos',{exact:true})}).locator(':scope > summary').click();await drag(page,'computed','/layouts/0/tabs/0/sections/0/containers/0/components/0');await page.mouse.up();expect(await page.locator('#editor-json').inputValue()).toBe(before);const box=page.locator('.editor-toolbox');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Cálculo adicional');await box.getByLabel('Cálculo compartilhado',{exact:true}).selectOption('total');await box.getByRole('button',{name:'Revisar inclusão',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração',exact:true}).click();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');expect(JSON.parse(await page.locator('#editor-json').inputValue()).layouts[0].tabs[0].sections[0].containers[0].components[1]).toMatchObject({type:'computed',formula:'total',label:'Cálculo adicional'});
});
test('T09/B borda do canvas rola a ficha durante arrasto sem gravar antes de soltar',async({page})=>{
 const p=minimalPackage('scroll-canvas');p.layouts[0].showHeader=false;const cs=p.layouts[0].tabs[0].sections[0].containers[0].components;for(let i=0;i<30;i++)cs.push({type:'text',field:'note'+i,label:'Nota '+i});await openFixture(page,p);const before=await page.locator('#editor-json').inputValue(),frame=page.frameLocator('.editor-preview-frame:not([hidden])'),card=page.locator('[data-toolbox-type="text"]');await page.locator('.editor-preview').scrollIntoViewIfNeeded();await card.scrollIntoViewIfNeeded();const c=await card.boundingBox();await page.mouse.move(c.x+c.width/2,c.y+c.height/2);await page.mouse.down();await page.mouse.move(c.x+c.width/2+10,c.y+c.height/2+10,{steps:4});await expect(page.locator('.editor-composition-overlay')).toBeVisible();const layer=await page.locator('.editor-composition-overlay').boundingBox(),start=await frame.locator('body').evaluate(()=>scrollY);await page.mouse.move(layer.x+layer.width/2,layer.y+layer.height-10,{steps:10});await page.mouse.move(layer.x+layer.width/2,layer.y+layer.height-10);await expect.poll(()=>frame.locator('body').evaluate(()=>scrollY)).toBeGreaterThan(start);await page.keyboard.press('Escape');await page.mouse.up();await expect(page.locator('.editor-composition-overlay')).toHaveCount(0);expect(await page.locator('#editor-json').inputValue()).toBe(before);
});
test('T01/B arrastar card configurado usa nome e dados escolhidos, sem voltar ao padrão',async({page})=>{
 await open(page);const box=page.locator('.editor-toolbox');await box.getByLabel('O que adicionar',{exact:true}).selectOption('resource');await box.getByLabel('Nome mostrado na ficha',{exact:true}).fill('Energia');await box.getByLabel('Valor atual inicial',{exact:true}).fill('0');const before=await page.locator('#editor-json').inputValue();await box.getByLabel('Valor máximo inicial',{exact:true}).fill('inválido pendente');await drag(page,'resource','/layouts/0/tabs/0/sections/0/containers/0/components/0');await page.mouse.up();expect(await page.locator('#editor-json').inputValue()).toBe(before);await expect(box.getByLabel('Valor máximo inicial',{exact:true})).toHaveValue('inválido pendente');await box.getByLabel('Valor máximo inicial',{exact:true}).fill('12');await drag(page,'resource','/layouts/0/tabs/0/sections/0/containers/0/components/0');await page.mouse.up();await expect(page.locator('#editor-preview-status')).toContainText('Ensaio da revisão 1');const p=JSON.parse(await page.locator('#editor-json').inputValue());expect(p.system.characterTemplate.energia).toEqual({current:0,max:12});expect(p.layouts[0].tabs[0].sections[0].containers[0].components[1]).toMatchObject({type:'resource',field:'energia',label:'Energia'});
});
