import {cachedProjection} from './projection-cache.js';
// Projections of existing contracts. This is not another document schema.
import {COMPONENT_CONTRACTS,ITEM_FIELD_CONTRACTS} from '../validation/contracts.js';
import {nodeSchema,SYSTEM_RULES} from './form-metadata.js';
import {structuralNodes,valueAt} from './form-structure.js';
const FAMILY_FILES={checks:['js/engine/checks.js','js/validation/checks.js'],entryRolls:['js/engine/entry-rolls.js','js/validation/entry-rolls.js'],sheetActions:['js/engine/assisted-fields.js','js/validation/actions.js'],recoveryActions:['js/engine/recovery.js','js/validation/recovery.js'],effectDefinitions:['js/engine/effects.js','js/validation/effects.js'],pointBudget:['js/engine/point-budget.js','js/validation/schemas.js'],repertoire:['js/engine/assisted-fields.js','js/validation/schemas.js'],techniqueUse:['js/engine/technique-fields.js','js/validation/schemas.js'],resolution:['js/engine/resolution.js','js/validation/schemas.js']};
const SYSTEM_CONSUMERS={schemaVersion:'js/validation/schemas.js',id:'js/validation/references.js',name:'js/engine/renderer.js',description:'js/engine/system.js',characterTemplate:'js/repositories/character-repository.js',formulas:'js/engine/system.js',diceSteps:'js/engine/fields.js',diceTray:'js/app.js',dieScale:'js/engine/renderer.js',diceSet:'js/engine/system.js',abilities:'js/engine/system.js',skills:'js/engine/system.js'};
export function capabilityCatalog(){
 const rows=[];
 const walk=(schema,context,consumer,validation,prefix='')=>{for(const [property,desc]of Object.entries(schema)){const name=prefix+property,family=context==='system'?name.split('.')[0]:context.startsWith('rule:')?context.slice(5):null,files=FAMILY_FILES[family];const control=desc.inert?'preservar sem controle funcional':desc.editor==='postAscensionFormula'||context==='system'&&name.startsWith('formulas.')?'construtor de fórmula':['stepCosts','dieCosts'].includes(desc.editor)?'custos por dado ou passagem':desc.rollSource||desc.exclusive?.includes('resolver')?'construtor de origem':desc.type==='path'||['attributeKey','skillKey'].includes(desc.editor)?'seletor contextual':desc.enum?'escolha enumerada':desc.type==='object'||desc.type==='array'?'inspector por ramo/entradas nomeadas':desc.type==='any'?'valor tipado preservado':'valor tipado';rows.push({context,property:name,consumer:files?.[0]||(context==='system'?SYSTEM_CONSUMERS[family]:null)||consumer,validation:files?.[1]||validation,type:desc.type,inert:desc.inert===true,control,verification:'projeção do contrato; jornadas de família não provam cada valor possível',tests:['tests/unit/editor-visual.test.mjs','tests/unit/editor-rule-authoring.test.mjs','tests/unit/editor-visual-audit.test.mjs',context.startsWith('component:')&&!FAMILY_FILES[context.slice(10)]?'tests/e2e/editor-visual.spec.js':'tests/e2e/editor-rule-authoring.spec.js']});if(desc.properties)walk(desc.properties,context,consumer,validation,name+'.');if(desc.values)walk({'*':desc.values},context,consumer,validation,name+'.');if(desc.items)walk({'[]':desc.items},context,consumer,validation,name+'.');}};
 for(const [type,contract]of Object.entries(COMPONENT_CONTRACTS))walk({...contract.properties,...nodeSchema('component',{type})},'component:'+type,contract.source,'js/validation/schemas.js');
 for(const [type,schema]of Object.entries(ITEM_FIELD_CONTRACTS))walk(schema,'item:'+type,'js/engine/advanced-fields.js','js/validation/schemas.js');
 for(const kind of ['package','system','layout','tab','section','container'])walk(nodeSchema(kind),kind,kind==='system'?'js/engine/system.js':'js/engine/renderer.js','js/validation/schemas.js');
 for(const [family,desc]of Object.entries(SYSTEM_RULES))walk({definition:desc},'rule:'+family,FAMILY_FILES[family]?.[0]||'js/engine/assisted-fields.js',FAMILY_FILES[family]?.[1]||'js/validation/schemas.js');
 return rows;
}
export function ruleSchemaAt(pkg,path){return path[0]==='system'?ruleSchemas(pkg).get(path.slice(1).join('.'))||null:null;}
function ruleSchemas(pkg){return cachedProjection(pkg,'ruleSchemas',()=>{
 const result=new Map(),read=source=>typeof source==='string'?valueAt(pkg,['system',...source.replace(/^system\./,'').split('.')]):undefined;
 const add=(source,schema)=>{if(typeof source==='string'&&!result.has(source.replace(/^system\./,'')))result.set(source.replace(/^system\./,''),schema);};
 for(const node of structuralNodes(pkg))if(node.kind==='component'){
  const c=node.value||{},config=read(c.configFrom??COMPONENT_CONTRACTS[c.type]?.properties.configFrom?.default),rules=Array.isArray(config?.sources)?config.sources:[];
  for(const [source,schema]of [[c.traitsFrom,SYSTEM_RULES.attributes],[c.presetsFrom,SYSTEM_RULES.attributeSetPresets],[c.categoriesFrom,SYSTEM_RULES.skillCategories],[c.baseDieFrom,{type:'number'}],[config?.attributesFrom,SYSTEM_RULES.attributes],[config?.presetsFrom,SYSTEM_RULES.qualityPresets],[config?.progressionFrom,SYSTEM_RULES.techniques.properties.progressionByDie],[config?.costsFrom,{...SYSTEM_RULES.energyCostByDie,editor:'dieCosts'}],[config?.postAscension?.formulaFrom,{type:'string',editor:'postAscensionFormula'}]])add(source,schema);
  for(const source of rules)for(const [value,schema]of [[source.costsFrom,{...SYSTEM_RULES.evolution.properties.costs,editor:'stepCosts'}],[source.labelsFrom,SYSTEM_RULES.attributes],[source.catalogFrom,SYSTEM_RULES.skillCategories]])add(value,schema);
  const family={pointBudget:'pointBudget',repertoire:'repertoire',techniqueUse:'techniqueUse',checkRoll:'checks',list:'entryRolls',actionGroup:'sheetActions',recoveryGroup:'recoveryActions'}[c.type];
  if(family){const source=c.type==='list'?(c.rollPreset??c.rollConfigFrom)?'entryRolls.'+(c.rollPreset??c.rollConfigFrom):undefined:c.configFrom||c.actionsFrom||COMPONENT_CONTRACTS[c.type]?.properties.configFrom?.default;add(source,['checkRoll','list'].includes(c.type)?SYSTEM_RULES[family].values:SYSTEM_RULES[family]);}
 }
 return result;
});}

export function consumedRuleRoots(pkg){const roots=new Set(),add=source=>{if(typeof source==='string')roots.add(source.replace(/^system\./,'').split('.')[0]);};for(const node of structuralNodes(pkg).filter(n=>n.kind==='component')){const c=node.value||{};for(const key of ['configFrom','actionsFrom','rollConfigFrom','presetsFrom','traitsFrom','categoriesFrom','baseDieFrom'])add(c[key]);const config=typeof c.configFrom==='string'?valueAt(pkg,['system',...c.configFrom.replace(/^system\./,'').split('.')]):undefined;for(const key of ['attributesFrom','presetsFrom','progressionFrom','costsFrom'])add(config?.[key]);add(config?.postAscension?.formulaFrom);for(const source of Array.isArray(config?.sources)?config.sources:[])for(const key of ['costsFrom','labelsFrom','catalogFrom'])add(source?.[key]);}return [...roots];}
