import {formulaContexts} from './formula-contexts.js';
import {CHECK_ALGORITHMS} from '../validation/contracts.js';
import {structuralNodes} from './form-structure.js';
import {dataIndex,displayData,generatedKey} from './data-index.js';
import {itemFields} from './data-picker.js';
import {numberFromText} from './form-commands.js';
import {mountDiceEditor,diceText} from './dice-expression-editor.js';
import {checkRecipePlan} from './rule-plans.js';
import {el,input,choose,button} from './authoring-dom.js';
export const CHECK_HELP={fate:['Fate — quatro dados de sinais','Abordagem entre −100 e 100; oposição e modificador são escolhidos no ensaio.'],percentile:['Percentual — unidade e dezenas','Valor de 0 a 100; de −2 a +2 dados de bônus/penalidade. Críticos e consequência final ficam com a mesa.'],d6Pool:['Pool de d6 — maior resultado','De 0 a 20 dados; com zero, menor de dois d6. Posição, efeito e consequências são manuais.'],d6Resistance:['Resistência de d6','Pool de 0 a 20 dados; informa estresse a registrar. Não altera estresse automaticamente.'],explodingTrait:['Traço explosivo e dado selvagem','Traço d4/d6/d8/d10/d12; alvo e dado selvagem são escolhidos no ensaio.'],explodingDamage:['Dano com dados explosivos','Expressão de grupos de dados; limite de 100 rolagens. Resistência, armadura e ferimentos ficam com a mesa.'],challenge:['Ação contra dois desafios','Fonte de 0 a 10; ímpeto opcional entre −6 e 10. Queima de ímpeto e movimento são manuais.'],progress:['Progresso contra dois desafios','De 0 a 40 marcas, quatro por caixa. Sem modificador nem ímpeto.']};
export function mountCheckRecipe(host,{pkg,state={},notify}){state.sources??=[{kind:'field'}];const remember=(key,c)=>c.addEventListener('input',()=>{state[key]=c.value;notify?.();});host.append(el('h3','Configurar teste'));const algorithm=choose('Família do teste',CHECK_ALGORITHMS.map(k=>[k,CHECK_HELP[k][0]]),state.algorithm||'fate');remember('algorithm',algorithm.input);host.append(algorithm.wrap);const body=el('div');host.append(body);let sourcesRead=[];
 const render=()=>{body.replaceChildren();const damage=algorithm.input.value==='explodingDamage';body.append(el('p',CHECK_HELP[algorithm.input.value][1],'editor-note'));sourcesRead=[];state.sources.forEach((source,i)=>{const box=el('fieldset');box.append(el('legend','Fonte '+(i+1)));const label=input('Nome da fonte '+(i+1),source.label||''),kind=choose('Origem da fonte '+(i+1),[['field','Campo da ficha'],['collection','Valor de cada entrada'],['formula','Cálculo existente'],['new','Criar dado com nome']],source.kind||'field');box.append(label.wrap,kind.wrap);for(const [key,c]of [['label',label.input],['kind',kind.input]])c.addEventListener('input',()=>{source[key]=c.value;notify?.();});const inner=el('div');box.append(inner);let read;const draw=()=>{inner.replaceChildren();const index=dataIndex(pkg);if(kind.input.value==='new'){const initial=input('Valor inicial da fonte '+(i+1),source.initial??'');if(damage){source.dice??={};const dice=el('div');inner.append(dice);mountDiceEditor(dice,{value:'',state:source.dice,onEdit:()=>notify?.(),onApply:()=>notify?.()});read=()=>({newValue:diceText(source.dice)});}else{inner.append(initial.wrap);initial.input.addEventListener('input',()=>{source.initial=initial.input.value;notify?.();});read=()=>({newValue:numberFromText(initial.input.value,{integer:true})});}}
 else if(kind.input.value==='formula'){const formula=choose('Cálculo da fonte '+(i+1),[['','Escolha um cálculo'],...Object.keys(pkg.system.formulas||{}).map(k=>[k,k])],source.formula||'');inner.append(formula.wrap);const scopeBox=el('div');inner.append(scopeBox);let scope,contexts=[];const drawScope=()=>{scopeBox.replaceChildren();contexts=formulaContexts(pkg,formula.input.value,{family:'check'});scope=choose('Leituras da fórmula na fonte '+(i+1),[['','Escolha o uso com as leituras desejadas'],...contexts.map(c=>[c.pointer,c.label])],source.contextPointer||(contexts.length===1?contexts[0].pointer:''));if(contexts.length)scopeBox.append(scope.wrap);scope.input.addEventListener('change',()=>{source.contextPointer=scope.input.value;notify?.();});};formula.input.addEventListener('change',()=>{source.formula=formula.input.value;source.contextPointer='';drawScope();notify?.();});drawScope();read=()=>{if(!formula.input.value)throw new Error('Escolha um cálculo para a fonte.');const context=contexts.find(c=>c.pointer===scope.input.value);if(contexts.length&&!context)throw new Error('Escolha explicitamente as leituras deste cálculo compartilhado.');return {formula:formula.input.value,...(context?{variables:structuredClone(context.variables),...(context.overrideKey?{overrideKey:context.overrideKey}:{})}:{})};};}

 else{const rows=index.filter(r=>r.scope==='character'&&(kind.input.value==='collection'?r.type==='collection':damage?r.type==='string':r.type==='number'));const field=choose('Dado da fonte '+(i+1),[['','Escolha um dado'],...rows.map(r=>[r.field,displayData(r)])],source.field||'');inner.append(field.wrap);field.input.addEventListener('change',()=>{source.field=field.input.value;notify?.();drawItems();});const items=el('div');inner.append(items);let item;const drawItems=()=>{items.replaceChildren();if(kind.input.value!=='collection')return;item=choose('Valor da entrada na fonte '+(i+1),[['','Escolha o campo'],...itemFields(pkg,field.input.value).filter(f=>damage?['text','string'].includes(f.type):['number','die'].includes(f.type)).map(f=>[f.key,f.label+' · '+f.type])],source.valueField||'');item.input.addEventListener('change',()=>{source.valueField=item.input.value;notify?.();});items.append(item.wrap);};drawItems();read=()=>{if(!field.input.value||kind.input.value==='collection'&&!item?.input.value)throw new Error('Escolha dado e campo compatíveis da fonte.');return kind.input.value==='collection'?{collection:field.input.value,valueField:item.input.value}:{field:field.input.value};};}
 };kind.input.addEventListener('change',()=>{source.kind=kind.input.value;draw();});draw();sourcesRead.push(()=>{if(!label.input.value.trim())throw new Error('Informe o nome da fonte '+(i+1)+'.');return {...read(),label:label.input.value};});box.append(button('Remover fonte '+(i+1),()=>{if(state.sources.length<2)return;state.sources.splice(i,1);render();notify?.();}));body.append(box);});body.append(button('Acrescentar fonte ao teste',()=>{if(state.sources.length>=100)return;state.sources.push({kind:'field'});render();notify?.();}));};algorithm.input.addEventListener('change',render);render();const note=input('Decisões que ficam com a mesa neste teste',state.note||'');remember('note',note.input);host.append(note.wrap);const momentum=choose('Ímpeto para o teste de ação',[['','Sem ímpeto'],...dataIndex(pkg).filter(r=>r.scope==='character'&&r.type==='number').map(r=>[r.field,displayData(r)])],state.momentum||'');remember('momentum',momentum.input);host.append(momentum.wrap);const nodes=structuralNodes(pkg).filter(n=>n.kind==='component'&&['number','counter','die','computed','list'].includes(n.value?.type));const bind=choose('Botão de teste junto a um controle',[['','Somente painel do teste'],...nodes.map(n=>[n.pointer,n.title])],state.button||'');remember('button',bind.input);host.append(bind.wrap,el('p','Botão opcional exige a mesma fonte do controle e layout versão 2. A revisão mostra a habilitação antes de confirmar.','editor-note'));
 return ({name,destination})=>{if(!note.input.value.trim())throw new Error('Explique as decisões manuais antes de incluir o teste.');const newData=[],used=Object.keys(pkg.system.characterTemplate),sources=sourcesRead.map((read,i)=>{const source=read();if(Object.hasOwn(source,'newValue')){const field=generatedKey(source.label,used);used.push(field);newData.push({field,value:source.newValue,name:source.label});delete source.newValue;source.field=field;}source.id='source_'+(i+1);return source;});return checkRecipePlan(pkg,{name,destination,config:{algorithm:algorithm.input.value,sources,note:note.input.value,...(algorithm.input.value==='challenge'&&momentum.input.value?{momentumField:momentum.input.value}:{})},newData,buttonPath:nodes.find(n=>n.pointer===bind.input.value)?.path});};
}
