import {dataChoices} from './data-picker.js';
import {object} from './form-structure.js';
import {numberFromText} from './form-commands.js';
import {el,choose,input,button} from './authoring-dom.js';
export function conditionKind(path){if(['disabledWhen','excludeWhen'].includes(path.at(-1)))return path.at(-1);if(path.at(-2)==='requirements'&&typeof path.at(-1)==='number')return 'requirement';return null;}
export function conditionValue(state,base={}){if(!state.field)throw new Error('Escolha a fonte da condição.');const next=object(base)?structuredClone(base):{};next.field=state.field;if(state.comparison!=='min'){let value=state.raw;if(state.type==='number')value=numberFromText(state.raw);else if(state.type==='boolean'){if(!['true','false'].includes(state.raw))throw new Error('Escolha Sim ou Não.');value=state.raw==='true';}else if(state.type==='null')value=null;else if(state.type!=='string')throw new Error('Use texto, número, Sim/Não ou null para igualdade.');next.equals=value;}else delete next.equals;if(['min','both'].includes(state.comparison))next.min=numberFromText(state.minimum);else delete next.min;return next;}
export function mountConditionBuilder(host,{pkg,path,value,state={},onEdit,onApply}){const kind=conditionKind(path);if(!state.initialized){state.initialized=true;state.field=value?.field||'';state.comparison=value?.min!==undefined?(Object.hasOwn(value,'equals')?'both':'min'):'equals';state.minimum=String(value?.min??'');state.type=value?.equals===null?'null':typeof value?.equals==='undefined'?'boolean':typeof value.equals;state.raw=value?.equals===null?'':String(value?.equals??true);}
 const options=dataChoices(pkg,[...path,'field'],'field');if(state.field&&!options.some(([key])=>key===state.field))options.push([state.field,'Fonte existente ausente: '+state.field]);
 const publish=()=>{try{const next=conditionValue(state,value);delete state.invalid;onEdit?.(next,state);}catch(error){state.invalid=error.message;onEdit?.(value,state);}const status=host.querySelector('[role=status]');if(status)status.textContent=state.invalid||'Condição pendente; aplique para confirmar.';};
 const render=()=>{host.replaceChildren(el('h4',kind==='disabledWhen'?'Quando bloquear os controles':kind==='excludeWhen'?'Quando excluir esta entrada do Pool':'Requisito para executar a ação'),el('p',kind==='requirement'?'Os requisitos da ação devem ser atendidos juntos. Igualdade compara o tipo e o valor; mínimo é um limite numérico.':'A condição bloqueia ou exclui quando a fonte tem exatamente o tipo e o valor escolhidos. Não apaga os dados.','editor-note'));
 const field=choose('Fonte da condição',[['','Escolha uma fonte'],...options],state.field);host.append(field.wrap);field.input.addEventListener('change',()=>{state.field=field.input.value;publish();});
 if(kind==='requirement'){const comparison=choose('Comparação da condição',[['equals','Igual ao valor'],['min','Pelo menos o mínimo'],['both','Igual ao valor e pelo menos o mínimo']],state.comparison);host.append(comparison.wrap);comparison.input.addEventListener('change',()=>{state.comparison=comparison.input.value;publish();render();});}
 if(state.comparison!=='min'){const type=choose('Tipo do valor comparado',[['boolean','Sim ou Não'],['number','Número'],['string','Texto ou opção'],['null','null explícito']],state.type);host.append(type.wrap);type.input.addEventListener('change',()=>{state.type=type.input.value;state.raw=state.type==='boolean'?'true':'';publish();render();});const choices=state.type==='boolean'?[['true','Sim'],['false','Não']]:null;const literal=choices?choose('Valor comparado',choices,state.raw):input('Valor comparado',state.raw);if(state.type==='null')host.append(el('p','Comparar com null explícito. Ausência é diferente de null.'));else{host.append(literal.wrap);literal.input.addEventListener('input',()=>{state.raw=literal.input.value;publish();});literal.input.addEventListener('change',()=>{state.raw=literal.input.value;publish();});}}
 if(['min','both'].includes(state.comparison)){const minimum=input('Mínimo necessário',state.minimum);minimum.input.inputMode='decimal';host.append(minimum.wrap);minimum.input.addEventListener('input',()=>{state.minimum=minimum.input.value;publish();});}
 const status=el('p');status.setAttribute('role','status');status.textContent=state.invalid||'Abrir este controle não modifica o documento.';host.append(status,button('Aplicar condição construída',async()=>{try{const next=conditionValue(state,value);await onApply(next);}catch(error){status.textContent=error.message;}}));};render();return state;
}
