import {nodeSchema} from './form-metadata.js';
import {ruleSchemaAt} from './capability-catalog.js';
import {repeatControls} from './repeat-controls.js';
import {dataIndex,displayData,generatedKey} from './data-index.js';
import {createDataPlan,relinkDataPlan} from './data-commands.js';
import {numberFromText} from './form-commands.js';
import {el,button,choose,input} from './authoring-dom.js';
import {pointerFor} from './source-map.js';
export function renderDataPanel(view,pkg){
 const panel=el('details','','editor-data-panel');panel.append(el('summary','Dados e catálogos do sistema'),el('p','Crie valores iniciais para novos personagens e coleções para a ficha, ou catálogos comuns ao sistema. Mudar o rótulo conserva a identidade; religar um nome interno não migra personagens instalados.','editor-note'));let populated=false;
 const populate=()=>{if(populated||!panel.open)return;populated=true;const ui=view.session.ui;ui.dataInputs??={};const state=ui.dataInputs;const remember=(key,control)=>control.addEventListener('input',()=>{state[key]=control.value;view.onPending?.();});
  const scope=choose('Onde o dado pertence',[['character','Na ficha de cada personagem'],['system','No sistema (catálogo ou tabela)']],state.scope||'character'),name=input('Nome do novo dado ou catálogo',state.name||''),type=choose('Tipo do novo dado',[['string','Texto'],['number','Número'],['boolean','Sim/Não'],['resource','Recurso atual e máximo'],['collection','Coleção de entradas'],['object','Tabela por nome'],['null','null explícito']],state.type||'string');for(const [key,c]of [['scope',scope.input],['name',name.input],['type',type.input]])remember(key,c);panel.append(scope.wrap,name.wrap,type.wrap);const values=el('div');panel.append(values);let read=()=>{};
  const draw=()=>{values.replaceChildren();const kind=type.input.value;if(kind==='resource'){const current=input('Atual do novo recurso',state.current??'0'),max=input('Máximo do novo recurso',state.max??'10');remember('current',current.input);remember('max',max.input);values.append(current.wrap,max.wrap);read=()=>({current:numberFromText(current.input.value),max:numberFromText(max.input.value)});}else if(['collection','object','null'].includes(kind)){values.append(el('p','Será criado explicitamente '+({collection:'uma coleção vazia',object:'uma tabela vazia',null:'um valor null'}[kind])+'.'));read=()=>kind==='null'?null:kind==='object'?{}:[];}else{const value=kind==='boolean'?choose('Valor inicial do dado',[['false','Não'],['true','Sim']],state.value||'false'):input('Valor inicial do dado',state.value||'');remember('value',value.input);values.append(value.wrap);read=()=>kind==='number'?numberFromText(value.input.value):kind==='boolean'?value.input.value==='true':value.input.value;}};type.input.addEventListener('change',draw);draw();
  panel.append(button('Revisar novo dado',()=>view.run(async()=>{const revision=view.session.revision,plan=createDataPlan(pkg,{scope:scope.input.value,name:name.input.value,type:type.input.value,hasInitial:true,value:read()});if(!await view.confirm('Criar '+name.input.value+'? Valor inicial: '+JSON.stringify(read())+'. Só novos personagens usarão o template.'))return;if(revision!==view.session.revision)throw new Error('Revisão mudou.');view.commit(plan.commands,'Criar dado por nome',view.selection);})));
  panel.append(repeatControls(view,pkg));const list=el('div');panel.append(list);const rows=dataIndex(pkg).filter(r=>!r.field.startsWith('meta')&&!['schemaVersion','activeEffects'].includes(r.field));
  const search=input('Buscar dado ou catálogo por nome',state.query??'');panel.insertBefore(search.wrap,list);let page=Math.max(0,Number(state.page)||0);const renderList=()=>{const filtered=rows.filter(r=>displayData(r).toLocaleLowerCase('pt-BR').includes((state.query||'').toLocaleLowerCase('pt-BR'))),size=200;page=Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1));state.page=page;list.replaceChildren();const nav=el('nav'),previous=button('Dados anteriores',()=>{page--;renderList();view.onPending?.();}),next=button('Próximos dados',()=>{page++;renderList();view.onPending?.();});previous.disabled=page===0;next.disabled=(page+1)*size>=filtered.length;nav.append(previous,el('span',(filtered.length?String(page*size+1):'0')+'–'+Math.min((page+1)*size,filtered.length)+' de '+filtered.length+' dados'),next);list.append(nav);
  for(const row of filtered.slice(page*size,(page+1)*size)){const item=el('details');item.append(el('summary',displayData(row)));let built=false;item.addEventListener('toggle',()=>{if(!item.open||built)return;built=true;const selectBlock=()=>{view.selection=['system'];view.session.ui.formSelection=view.selection;view.session.ui.formOpen??={};for(let i=2;i<=row.path.length;i++)view.session.ui.formOpen[pointerFor(row.path.slice(0,i))]=true;view.session.ui.formDataKeys??=[];if(row.scope==='system'&&!view.session.ui.formDataKeys.includes(row.path[1]))view.session.ui.formDataKeys.push(row.path[1]);view.session.ui.inspectorBranch=row.path;view.refresh(true);view.onPending?.();};item.append(button('Editar valores de '+row.label,selectBlock));
    if(row.scope==='character'){const rename=input('Novo nome interno de '+row.label,state['rename:'+row.field]||'');remember('rename:'+row.field,rename.input);item.append(rename.wrap,button('Revisar religação de '+row.label,()=>view.run(async()=>{if(Object.keys(view.session.ui.formPending||{}).length)throw new Error('Resolva textos pendentes antes de religar.');const key=generatedKey(rename.input.value,[]),plan=relinkDataPlan(pkg,row.path,key),revision=view.session.revision;if(!await view.confirm('Religar '+row.label+'? '+plan.usages.length+' usos conhecidos. '+plan.notes.join(' ')))return;if(revision!==view.session.revision)throw new Error('Revisão mudou.');view.commit(plan.commands,'Religar dado e consumidores',view.selection);})));
    }
    if(row.scope==='system'&&row.type==='collection'){const entry=input('Nome da entrada em '+row.label,state['entry:'+row.field]||'');remember('entry:'+row.field,entry.input);item.append(entry.wrap,button('Acrescentar entrada em '+row.label,()=>view.run(()=>{if(!entry.input.value.trim())throw new Error('Informe o nome da entrada do catálogo.');const props=(ruleSchemaAt(pkg,row.path)||nodeSchema('system')[row.path[1]])?.items?.properties,identity=props?.key?'key':'id',key=generatedKey(entry.input.value,row.value.map(v=>v?.[identity])),value=props?{[identity]:key,...(props.name?{name:entry.input.value}:{}),...(props.label?{label:entry.input.value}:{})}:{id:crypto.randomUUID(),name:entry.input.value,label:entry.input.value};view.commit([{type:'insertNode',path:row.path,index:row.value.length,value}],'Adicionar entrada de catálogo',view.selection);})));}
   });list.append(item);}
  };search.input.addEventListener('input',()=>{state.query=search.input.value;page=0;renderList();view.onPending?.();});renderList();
 };
 panel.addEventListener('toggle',()=>{view.session.ui.dataPanelOpen=panel.open;populate();view.onPending?.();});panel.open=view.session.ui.dataPanelOpen===true;populate();return panel;
}
