import {dataIndex,displayData,compatibleData,systemSourceChoices} from './data-index.js';
import {structuralNodes,valueAt,object} from './form-structure.js';
import {pointerFor} from './source-map.js';
import {rollValueResolverNames} from '../engine/roll-values.js';
import {referenceOptions} from './form-commands.js';
import {effectTargetChoices} from './rule-plans.js';
export function itemFields(pkg,collection){const fields=new Map([['id',{label:'Identidade estável',type:'text'}]]);for(const node of structuralNodes(pkg))if(node.kind==='component'&&node.value?.field===collection)for(const [key,desc]of Object.entries(node.value?.itemSchema||{}))fields.set(key,typeof desc==='string'?{label:key,type:desc}:{...desc,label:desc.label||key});const sample=dataIndex(pkg).find(r=>r.scope==='character'&&r.field===collection)?.value;for(const item of Array.isArray(sample)?sample.slice(0,20):[])if(object(item))for(const [key,value]of Object.entries(item))if(!fields.has(key))fields.set(key,{label:key,type:typeof value});return [...fields].map(([key,desc])=>({key,...desc}));}
export function collectionFor(pkg,path,key){for(let i=path.length-1;i>0;i--){const ancestor=valueAt(pkg,path.slice(0,i));if(ancestor?.collection)return ancestor.collection;}const owner=valueAt(pkg,path.slice(0,-1)),nodes=structuralNodes(pkg);if(['valueField','labelField'].includes(key)&&owner?.optionsFrom?.startsWith('character.'))return owner.optionsFrom.slice(10);if(owner?.collection)return owner.collection;if(owner?.sourceField&&Array.isArray(dataIndex(pkg).find(d=>d.scope==='character'&&d.field===owner.sourceField)?.value))return owner.sourceField;if(owner?.field&&Array.isArray(dataIndex(pkg).find(d=>d.scope==='character'&&d.field===owner.field)?.value))return owner.field;const component=nodes.filter(n=>n.kind==='component'&&n.path.length<path.length&&n.path.every((part,i)=>part===path[i])).at(-1);if(component?.value?.itemSchema)return component.value.field;
 if(path[0]==='system'&&path[1]==='entryRolls'){const consumer=nodes.find(n=>n.kind==='component'&&(n.value?.rollPreset??n.value?.rollConfigFrom)===path[2]);return consumer?.value?.field;}return null;}
export function dataChoices(pkg,path,key){const owner=valueAt(pkg,path.slice(0,-1)),index=dataIndex(pkg),fields=index.filter(d=>d.scope==='character'),system=index.filter(d=>d.scope==='system');let rows=[];
 if(key==='key'&&path.at(-2)==='target')return effectTargetChoices(pkg).filter(t=>t.kind===owner?.kind&&(!owner.unit||!t.unit||t.unit===owner.unit)).map(t=>[t.key,t.label+(t.unit?' · '+t.unit:'')]);
 if(['defaultAttribute','skill'].includes(key)&&path.includes('modes')){let config;for(let i=path.length-1;i>1;i--){const candidate=valueAt(pkg,path.slice(0,i));if(candidate?.attributesFrom&&candidate?.modes){config=candidate;break;}}if(key==='defaultAttribute')return (valueAt(pkg,['system',...(config?.attributesFrom||'').replace(/^system\./,'').split('.')])||[]).map(a=>[a.key,a.label||a.key]);return Object.keys(valueAt(pkg,['system','characterTemplate',...(config?.skillsField||'').split('.')])||{}).map(name=>[name,name]);}
 if(key==='resolver')return rollValueResolverNames().map(name=>[name,{ 'dnd.constitutionModifier':'D&D: modificador de Constituição','dnd.spellAttackBonus':'D&D: bônus de ataque mágico','dnd.spellSaveDC':'D&D: dificuldade de magia'}[name]||name]);
 if(['formula','formulaFrom','difficultyFormula'].includes(key))return Object.keys(pkg.system?.formulas||{}).map(name=>[name,'Cálculo: '+name]);
 if(['check','sourceId','rollPreset','rollConfigFrom'].includes(key))return referenceOptions(pkg,path,key).map(value=>[value,value]);
 const structural=structuralNodes(pkg),component=structural.filter(n=>n.kind==='component'&&n.path.length<path.length&&n.path.every((part,i)=>part===path[i])).at(-1);
 if(key==='field'&&component&&path.length===component.path.length+1){const compatible=compatibleData(pkg,component.value.type);const group=valueAt(pkg,component.path.slice(0,-2)),repeat=group?.repeat;const special=[];if(repeat){const catalog=systemSourceChoices(pkg).find(s=>s.path===repeat.source)?.value||[];const keys=new Set(catalog.flatMap(item=>item&&typeof item==='object'?Object.keys(item):[]));for(const map of fields.filter(d=>d.type==='object'&&!d.resource))for(const attr of keys)special.push([map.field+'.{'+attr+'}',map.label+' · uma entrada por '+attr]);}return [...compatible.map(d=>[d.field,displayData(d)]),...special];}
 const item=collectionFor(pkg,path,key);if(key==='itemField'||['valueField','labelField','filterField','matchField','gradeField','weightField','quantityField','carriedField','textEntryField','linkField','costField','evolutionValueField','recoverableField','require'].includes(key)&&item)return itemFields(pkg,item).map(f=>[f.key,f.label+' · '+f.type+' · desta entrada']);
 if(key==='optionsFrom')return [...fields.filter(d=>d.type==='collection').map(d=>['character.'+d.field,displayData(d)]),...system.filter(d=>d.type==='collection').map(d=>[(path.includes('itemSchema')?'system.':'')+d.field,displayData(d)])];
 if(key==='source'&&path.includes('repeat'))return systemSourceChoices(pkg).map(s=>[s.path,'Uma ocorrência por entrada de '+s.label]);
 else if(key==='system'||key.endsWith('From'))rows=system;
 else rows=fields;
 if(key==='collection')rows=rows.filter(d=>d.type==='collection');
 if(key==='consumeField'||key==='enabledField')rows=fields.filter(d=>d.type==='boolean');
 return rows.map(d=>[d.field,displayData(d)]);
}
