import {cachedProjection} from './projection-cache.js';
import {structuralNodes,valueAt,object,uniqueName} from './form-structure.js';
import {knownReferences} from './references.js';
export const dataType=value=>value===null?'null':Array.isArray(value)?'collection':typeof value==='object'?'object':typeof value;
export function dataIndex(pkg){return cachedProjection(pkg,'data',()=>buildDataIndex(pkg));}
function buildDataIndex(pkg){
 const nodes=structuralNodes(pkg),rows=[],refs=knownReferences(pkg),refsByValue=new Map(),componentsByField=new Map();for(const ref of refs){if(!refsByValue.has(ref.value))refsByValue.set(ref.value,[]);refsByValue.get(ref.value).push(ref);}for(const node of nodes)if(node.kind==='component'&&node.value?.field){if(!componentsByField.has(node.value.field))componentsByField.set(node.value.field,[]);componentsByField.get(node.value.field).push(node);}
 const walk=(value,path,scope,depth=0)=>{if(depth>32)return;for(const [key,child]of Object.entries(value||{})){if(scope==='system'&&['characterTemplate','extensions','metadata'].includes(key))continue;const parts=[...path,key],field=parts.join('.'),uses=scope==='character'?componentsByField.get(field)||[]:[];
  rows.push({scope,field,path:scope==='character'?['system','characterTemplate',...parts]:['system',...parts],value:child,type:dataType(child),label:uses[0]?.value?.label||key,consumers:refsByValue.get(field)||[],components:uses.map(n=>n.pointer),resource:object(child)&&Object.hasOwn(child,'current')&&Object.hasOwn(child,'max')});
  if(object(child))walk(child,parts,scope,depth+1);
 }};
 walk(pkg.system?.characterTemplate,[],'character');walk(pkg.system,[],'system');const present=new Set(rows.filter(r=>r.scope==='character').map(r=>r.field));for(const [field,uses]of componentsByField)if(!field.includes('{')&&!present.has(field)){const type=uses[0].value.type;rows.push({scope:'character',field,path:['system','characterTemplate',...field.split('.')],value:undefined,type:({text:'string',textarea:'string',number:'number',counter:'number',die:'number',boolean:'boolean',list:'collection',table:'collection',resource:'object'}[type]||'object'),label:uses[0].value.label||field,consumers:refsByValue.get(field)||[],components:uses.map(n=>n.pointer),resource:type==='resource',absent:true});}return rows;
}
export function compatibleData(pkg,type){return dataIndex(pkg).filter(row=>row.scope==='character'&&({resource:row.resource,list:row.type==='collection',table:row.type==='collection',stateList:row.type==='collection',slotTracker:row.type==='collection',inventorySummary:row.type==='collection',tagList:row.type==='collection',skillCatalog:row.type==='object'&&!row.resource,traitAllocation:row.type==='object'&&!row.resource,boolean:row.type==='boolean',dndAbility:row.type==='number',dndSkill:row.type==='boolean',number:row.type==='number',counter:row.type==='number',die:row.type==='number'||row.type==='object',text:row.type==='string',textarea:row.type==='string',image:row.type==='string',select:['string','number','boolean','null'].includes(row.type)}[type]??false));}
export function generatedKey(name,existing=[]){const base=String(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')||'dado';const stem=/^[0-9]/.test(base)?'dado_'+base:base;let key=stem,index=2;while(existing.includes(key))key=stem+'_'+index++;return key;}
export function displayData(row){return row.label+' · '+({collection:'coleção',object:row.resource?'recurso atual/máximo':'objeto',string:'texto',number:'número',boolean:'Sim/Não',null:'null'}[row.type]||row.type)+' · '+(row.scope==='character'?'da ficha':'do sistema')+' ('+row.field+')';}

export function systemSourceChoices(pkg){const result=new Map();const walk=(value,path,depth)=>{if(depth>32||!value||typeof value!=='object')return;if(Array.isArray(value)){result.set(path,{path,value,label:path});for(const sample of value.slice(0,20))if(sample&&typeof sample==='object')walk(sample,path+'[]',depth+1);}else for(const [key,child]of Object.entries(value)){if(['characterTemplate','extensions','metadata','extra','extras','manifest'].includes(key))continue;walk(child,path?path+'.'+key:key,depth+1);}};walk(pkg.system,'',0);return [...result.values()];}
