import {validateFormula,evaluate} from '../engine/formula.js';
import {rollValue} from '../engine/roll-values.js';
import {knownReferences} from './references.js';
import {pointerPath} from './form-commands.js';
import {computedVariables} from '../engine/computed-values.js';
import {printFormula} from './formula-codec.js';
import {dataIndex,displayData} from './data-index.js';
import {structuralNodes,valueAt} from './form-structure.js';
import {numberFromText} from './form-commands.js';
import {el,button,choose,input} from './authoring-dom.js';
export const FORMULA_OPERATIONS=[['number','Número informado'],['boolean','Sim ou Não'],['identifier','Valor de uma fonte'],['+','Somar'],['-','Subtrair'],['*','Multiplicar'],['/','Dividir'],['%','Resto da divisão'],['==','Igual a'],['!=','Diferente de'],['<','Menor que'],['<=','Menor ou igual'],['>','Maior que'],['>=','Maior ou igual'],['&&','E'],['||','OU'],['neg','Trocar sinal'],['not','NÃO'],['call:floor','Arredondar para baixo'],['call:ceil','Arredondar para cima'],['call:round','Arredondar ao mais próximo'],['call:abs','Valor absoluto'],['call:sqrt','Raiz quadrada'],['call:min','Menor valor'],['call:max','Maior valor'],['call:if','Escolher valor por condição']];
export function replaceFormulaNode(ast,path,node){const copy=structuredClone(ast);if(!path.length)return node;valueAt(copy,path.slice(0,-1))[path.at(-1)]=node;return copy;}
export function formulaNodeFor(operation,previous={}){const zero=()=>({op:'literal',value:0});if(operation==='number')return {op:'literal',value:typeof previous.value==='number'?previous.value:0};if(operation==='boolean')return {op:'literal',value:typeof previous.value==='boolean'?previous.value:false};if(operation==='identifier')return {op:'identifier',name:previous.name||''};if(operation.startsWith('call:')){const name=operation.slice(5),count=name==='if'?3:['min','max'].includes(name)?2:1;return {op:'call',name,args:previous.op==='call'&&previous.name===name?previous.args:Array.from({length:count},(_,i)=>previous.args?.[i]||zero())};}if(['neg','not'].includes(operation))return {op:operation,value:typeof previous.value==='object'?previous.value:zero()};return {op:operation,left:previous.left||zero(),right:previous.right||zero()};}
export function mountFormulaBuilder(host,{expression,pkg,state={},onEdit,onApply,contextVariables={},contextLabel}){
 const consumers=knownReferences(pkg).filter(r=>r.kind==='formula'&&r.value===state.formula).map(r=>({pointer:r.pointer,value:valueAt(pkg,pointerPath(pkg,r.pointer).slice(0,-1))})),sources=dataIndex(pkg).filter(r=>r.scope==='character'&&['number','boolean','null'].includes(r.type));
 const variablesFor=consumer=>consumer?.value?.variables||Object.fromEntries(Object.entries(consumer?.pointer==='/system/resolution/difficultyFormula'?{actorWeight:0,opponentWeight:0}:contextVariables).map(([key,value])=>[key,{value}]));
 let consumer=consumers.find(c=>c.pointer===state.consumerPointer)||consumers[0],variables=variablesFor(consumer);
 if(!state.ast)try{state.ast=validateFormula(expression);}catch(error){state.error=error.message;}
 state.selection??=[];state.rawValues??={};state.errors??={};
 const write=()=>{try{if(state.invalid)throw new Error(state.invalid);const generated=printFormula(state.ast);validateFormula(generated);state.error=null;onEdit?.(generated,state);}catch(error){state.error=error.message;onEdit?.(expression,state);}render();};
 const render=()=>{host.replaceChildren(el('h4','Construir cálculo por operações'),el('p','Escolha a operação, depois os valores ou fontes. Os dois valores de “Escolher por condição” são avaliados antes da escolha; uma fonte ausente continua sendo erro.','editor-note'));
  if(consumers.length){const scope=choose('Contexto de leitura deste cálculo',consumers.map(c=>[c.pointer,c.value?.label||c.value?.type||'Uso em '+c.pointer]),consumer?.pointer);host.append(scope.wrap,el('p','Cada uso tem suas próprias variáveis. Alterar a fórmula compartilhada afeta todos os usos.','editor-note'));scope.input.addEventListener('change',()=>{state.consumerPointer=scope.input.value;consumer=consumers.find(c=>c.pointer===state.consumerPointer);variables=variablesFor(consumer);render();});}
  if(!state.ast){host.append(el('p','Cálculo incompatível: '+state.error),button('Substituir por um cálculo novo',()=>{state.ast={op:'literal',value:0};state.selection=[];write();}));return;}
  if(!valueAt(state.ast,state.selection))state.selection=[];const node=valueAt(state.ast,state.selection),kind=node.op==='literal'?typeof node.value==='boolean'?'boolean':'number':node.op==='call'?'call:'+node.name:node.op;
  const nav=el('nav');nav.setAttribute('aria-label','Partes do cálculo');nav.append(button('Cálculo inteiro',()=>{state.selection=[];render();}));if(state.selection.length)nav.append(button('Parte anterior',()=>{state.selection=state.selection.slice(0,-1);if(typeof state.selection.at(-1)==='string'&&state.selection.at(-1)==='args')state.selection.pop();render();}));host.append(nav);
  const operation=choose('Operação desta parte',FORMULA_OPERATIONS,kind);host.append(operation.wrap);operation.input.addEventListener('change',()=>{if(Object.keys(state.errors).length){state.error='Resolva ou descarte os textos inválidos antes de trocar operações.';render();return;}state.ast=replaceFormulaNode(state.ast,state.selection,formulaNodeFor(operation.input.value,node));write();});
  if(node.op==='literal'){if(typeof node.value==='boolean'){const value=choose('Escolha Sim ou Não',[['false','Não'],['true','Sim']],String(node.value));host.append(value.wrap);value.input.addEventListener('change',()=>{node.value=value.input.value==='true';state.invalid=Object.values(state.errors).join('; ');write();});}else{const value=input('Número desta parte',state.rawValues[JSON.stringify(state.selection)]??String(node.value));value.input.inputMode='decimal';host.append(value.wrap);value.input.addEventListener('input',()=>{const key=JSON.stringify(state.selection);state.rawValues[key]=value.input.value;try{node.value=numberFromText(value.input.value);delete state.errors[key];delete state.rawValues[key];}catch(error){state.errors[key]=error.message;}state.invalid=Object.values(state.errors).join('; ');try{const generated=printFormula(state.ast);onEdit?.(generated,state);}catch{};const status=host.querySelector('[data-formula-status]');if(status)status.textContent=state.invalid||'Valor pendente; aplique o cálculo ao terminar.';});}}
  if(node.op==='identifier'){const options=[['','Escolha uma fonte'],...sources.map(r=>[r.field,displayData(r)]),...Object.keys(variables).map(key=>[key,'Variável: '+key])];if(node.name&&!options.some(([name])=>name===node.name))options.push([node.name,'Fonte existente ou ausente: '+node.name]);const value=choose('Fonte desta parte',options,node.name);host.append(value.wrap);value.input.addEventListener('change',()=>{node.name=value.input.value;state.invalid=Object.values(state.errors).join('; ');write();});}
  const child=(label,path)=>host.append(button(label,()=>{state.selection=[...state.selection,...path];render();}));if(node.left)child('Editar primeiro valor',['left']);if(node.right)child('Editar segundo valor',['right']);if(node.op==='neg'||node.op==='not')child('Editar valor transformado',['value']);
  if(node.args){node.args.forEach((_,i)=>child(node.name==='if'?['Editar condição','Editar valor quando Sim','Editar valor quando Não'][i]||'Editar argumento '+(i+1):'Editar valor '+(i+1),['args',i]));if(['min','max'].includes(node.name))host.append(button('Acrescentar valor à função',()=>{node.args.push({op:'literal',value:0});write();}));if(['min','max'].includes(node.name)&&node.args.length>1)node.args.forEach((_,i)=>host.append(button('Remover valor '+(i+1),()=>{node.args.splice(i,1);write();})));}
  if(Object.keys(state.errors).length)host.append(button('Descartar textos inválidos deste cálculo',()=>{state.rawValues={};state.errors={};delete state.invalid;write();}));
  const status=el('p');status.setAttribute('role','status');status.dataset.formulaStatus='';try{const expression=printFormula(state.ast);validateFormula(expression);const rollSources=consumer?.pointer?.includes('/entryRolls/')||consumer?.pointer?.includes('/healing/');const vars=rollSources?Object.fromEntries(Object.entries(variables).map(([key,source])=>[key,rollValue(source,{character:pkg.system.characterTemplate,system:pkg.system,item:{}})])):computedVariables(variables,pkg.system.characterTemplate,pkg.system);const result=evaluate(expression,{vars,data:pkg.system.characterTemplate});status.textContent=state.invalid||'Resultado no template: '+String(result)+'.';}catch(error){status.textContent='Não foi possível calcular o exemplo: '+error.message;}host.append(status);
  const details=el('details');details.append(el('summary','Leituras e detalhes'),el('code',(()=>{try{return printFormula(state.ast);}catch{return 'Valor pendente inválido';}})()));for(const r of sources)details.append(el('p',r.label+': '+String(r.value??'ausente/null')));host.append(details,button('Aplicar cálculo construído',async()=>{try{if(state.invalid)throw new Error(state.invalid);const text=printFormula(state.ast);validateFormula(text);await onApply(text);}catch(error){state.error=error.message;status.textContent=error.message;}}));
 };render();return state;
}
