import {mountLocalImage} from './local-image-input.js';
import {structuralNodes} from './form-structure.js';
import {ENUM_LABELS} from './authoring-labels.js';
import {inspectorPage} from './inspector-pagination.js';
import {diceLiteralAt} from './dice-literals.js';
import {valueAt,object,safeKey,blankNode} from './form-structure.js';
import {mountRollSource} from './roll-source-editor.js';
import {mountVariableCreator} from './variable-editor.js';
import {conditionKind,mountConditionBuilder} from './condition-builder.js';
import {mountFormulaBuilder} from './formula-builder.js';
import {mountCostTableEditor} from './cost-table-editor.js';
import {mountDiceEditor} from './dice-expression-editor.js';
import {addItemFieldPlan} from './data-commands.js';
import {generatedKey,compatibleData,displayData} from './data-index.js';
import {dataChoices} from './data-picker.js';
import {minimalPackage} from './minimal-package.js';
import {ruleSchemaAt} from './capability-catalog.js';
import {pointerFor} from './source-map.js';
import {labelFor,propertyGroup,initialValue,resolveSchema} from './form-metadata.js';
import {setValueCommands,renameKeyCommands,numberFromText} from './form-commands.js';
const el=(tag,text='',className='')=>{const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;return node;};
const button=(label,fn)=>{const node=el('button',label,'button button--ghost');node.type='button';node.addEventListener('click',fn);return node;};
const choose=(label,options,value)=>{const input=el('select');input.setAttribute('aria-label',label);for(const [id,text]of options){const opt=el('option',text);opt.value=id;input.append(opt);}input.value=value;return input;};
const valueType=value=>value===null?'null':Array.isArray(value)?'array':typeof value==='object'?'object':typeof value;
export class Inspector {
  constructor(host,{session,commit,onPending,onJson,referenceOptions=()=>[],rename,remove,visual=false}={}) {Object.assign(this,{host,session,onPending,onJson,referenceOptions,rename,remove,visual});this.commit=(...args)=>Promise.resolve().then(()=>commit(...args)).catch(error=>{this.onPending?.(false,error.message);return false;});}
  pending(path,value) {const key=pointerFor(path);this.session.ui.formPending??={};if(value===undefined)delete this.session.ui.formPending[key];else this.session.ui.formPending[key]=value;this.onPending?.();}
  render(pkg,node,schema) {
    this.pkg=pkg;this.node=node;this.rootSchema=schema;this.host.replaceChildren(el('h3','Propriedades: '+node.title));
    const branch=this.session.ui.inspectorBranch;if(Array.isArray(branch)&&branch.length>node.path.length&&node.path.every((key,i)=>branch[i]===key)&&valueAt(pkg,branch)!==undefined){this.renderBranch(branch,this.descriptorAt(branch));return;}
    if(!object(node.value)){this.repairNode(this.host,node);return;}
    this.repairStructure(this.host,node);
    for(const group of ['Apresentação','Dados','Lógica']){const section=el('details','','editor-property-group');section.open=true;section.append(el('summary',group));for(const [key,desc]of Object.entries(schema))if(propertyGroup(key)===group)this.field(section,[...node.path,key],desc,key,0);if(section.children.length>1)this.host.append(section);}
    const known=new Set([...Object.keys(schema),'type','tabs','sections','containers','components','system']);
    this.advanced(this.host,node.path,node.value,known);this.host.append(button('Abrir este bloco no JSON',()=>this.onJson(node.path)));
  }
  descriptorAt(path){let desc={type:'object',properties:this.rootSchema};for(let i=this.node.path.length;i<path.length;i++){const current=valueAt(this.pkg,path.slice(0,i));desc=ruleSchemaAt(this.pkg,path.slice(0,i))||resolveSchema(desc,current);if(desc.type==='any')desc=Array.isArray(current)?{type:'array',items:{type:'any'}}:{type:'object',values:{type:'any'}};desc=desc.properties?.[path[i]]||desc.values||desc.items||{type:'any'};}return ruleSchemaAt(this.pkg,path)||desc;}
  renderBranch(path,desc){this.host.replaceChildren(el('h3','Editar ramo: '+path.at(-1)));const nav=el('nav');nav.setAttribute('aria-label','Caminho do inspector');nav.append(button('Voltar ao bloco',()=>{delete this.session.ui.inspectorBranch;this.onPending?.(true);}));for(let i=this.node.path.length+1;i<path.length;i++)nav.append(button(String(path[i-1]),()=>{this.session.ui.inspectorBranch=path.slice(0,i);this.onPending?.(true);}));this.host.append(nav);this.field(this.host,path,desc,String(path.at(-1)),0);}
  repairNode(parent,node){parent.append(el('p','Este ramo tem um valor incompatível: '+JSON.stringify(node.value)+'. A substituição é explícita e pode ser desfeita. Baixar rascunho preserva o bruto.','editor-note'),button('Reparar '+node.kind+' com estrutura inicial',async()=>{const value=node.kind==='system'?minimalPackage(this.pkg.layouts?.[0]?.system||'sistema-'+crypto.randomUUID().slice(0,8)).system:blankNode(node.kind,this.pkg);const done=await this.commit(setValueCommands(this.pkg,node.path,value),'Reparar ramo '+node.kind,node.path);if(done!==false)this.onPending?.(true);}));}
  repairStructure(parent,node){const child={system:'layouts',layout:'tabs',tab:'sections',section:'containers',container:'components'}[node.kind];if(!child)return;const path=node.kind==='system'?['layouts']:[...node.path,child],value=valueAt(this.pkg,path);if(value===undefined||Array.isArray(value))return;const kind={layouts:'layout',tabs:'tab',sections:'section',containers:'container',components:'component'}[child];parent.append(el('p','Estrutura incompatível em '+child+': '+JSON.stringify(value)+'. Adicionar não substitui este valor.','editor-note'),button('Reparar '+child+' com primeiro bloco',async()=>{const done=await this.commit(setValueCommands(this.pkg,path,[blankNode(kind,this.pkg)]),'Reparar '+child,path);if(done!==false)this.onPending?.(true);}));}
  advanced(parent,path,value,known){const extra=object(value)?Object.keys(value).filter(key=>!known.has(key)):[];if(!extra.length)return;const details=el('details','','editor-extra-values');details.append(el('summary','Dados adicionais preservados ('+extra.length+')'),el('p','Estes dados podem ser editados por tipo. Semântica desconhecida não ganha execução por estar aqui.','editor-note'));let rendered=false;details.addEventListener('toggle',()=>{if(details.open&&!rendered){rendered=true;for(const key of extra)this.field(details,[...path,key],{type:'any'},key,0);}});parent.append(details);}
  field(parent,path,rawDesc,key,depth,ownerDesc={}) {
    const value=valueAt(this.pkg,path),owner=valueAt(this.pkg,path.slice(0,-1)),exists=owner!=null && Object.hasOwn(owner,path.at(-1)),pointer=pointerFor(path),label=rawDesc.label || labelFor(key);
    const desc=resolveSchema(ruleSchemaAt(this.pkg,path)||rawDesc,value),stored=this.session.ui.formPending?.[pointer],row=el('div','','editor-property');row.dataset.property=pointer;row.append(el('strong',label));
    if(depth>12){row.append(el('p','Abra somente este ramo para continuar sem carregar todos os níveis.'),button('Editar somente este ramo',()=>{this.session.ui.inspectorBranch=path;this.onPending?.(true);}));parent.append(row);return;}
    if(desc.semantic)row.append(el('small',desc.semantic.replace('; validação em schemas.js','').replace('; referências em roll-references.js',''),'editor-note'));
    const choices=[['absent','Ausente'],['value','Valor explícito'],...(desc.type==='any'||desc.nullable?[['null','null explícito']]:[]),...(Object.hasOwn(desc,'default')?[['default','Usar padrão: '+String(desc.default)]]:[])];
    if(value===null && !choices.some(([id])=>id==='null'))choices.push(['null','null existente (incompatível; corrigir ou usar JSON)']);
    const presence=choose('Estado de '+label,choices,stored?.mode ?? (!exists?'absent':value===null?'null':'value'));row.append(presence);
    const typed=desc.type==='any',typeInput=typed?choose('Tipo de valor de '+label,['string','number','boolean','object','array','null'].map(type=>[type,type]),stored?.valueType || (exists?valueType(value):'string')):null;
    let type=typed?typeInput.value:desc.type;
    if(typed)row.append(typeInput);
    const sourceKey=typeof path.at(-1)==='number'&&['summaryFields','fields'].includes(path.at(-2))?'itemField':key;const sourceChoices=this.visual&&(desc.type==='path'||['attributeKey','skillKey'].includes(desc.editor)||['valueField','labelField','gradeField','textEntryField','costField','evolutionValueField','linkField','recoverableField','weightField','quantityField','carriedField','itemField'].includes(sourceKey))?dataChoices(this.pkg,path,sourceKey):null;
    const input=el(sourceChoices||desc.enum||type==='boolean'?'select':desc.multiline?'textarea':'input');input.setAttribute('aria-label',label);
    if(sourceChoices){const options=[['','Escolha uma fonte'],...sourceChoices];const current=stored?.raw??(exists?String(value):'');if(current&&!options.some(([id])=>id===current))options.push([current,'Fonte existente ou pendente: '+current]);for(const [id,text]of options){const opt=el('option',text);opt.value=id;input.append(opt);}}
    if(desc.enum || type==='boolean')for(const entry of desc.enum || ['false','true']){const opt=el('option',ENUM_LABELS[entry]||String(entry));opt.value=String(entry);input.append(opt);}
    if(type==='boolean' && stored && !['false','true'].includes(stored.raw)){const opt=el('option',stored.raw+' (pendente)');opt.value=stored.raw;input.append(opt);}
    if(desc.enum && exists && !desc.enum.includes(value)){const opt=el('option',String(value)+' (existente)');opt.value=String(value);input.append(opt);}
    if(input.tagName==='INPUT'){input.type='text';if(['number','integer'].includes(type))input.inputMode='decimal';}
    input.value=stored?.raw ?? (exists && value!==null && !object(value)&&!Array.isArray(value)?String(value):type==='boolean'?'false':'');
    const complex=()=>['object','array'].includes(type);
    input.hidden=complex() || type==='null';row.append(input);
    if(desc.type==='path'&&!sourceChoices){const options=this.referenceOptions(path,key);if(options.length){const list=el('datalist');list.id='refs-'+crypto.randomUUID();for(const option of options){const item=el('option');item.value=option;list.append(item);}input.setAttribute('list',list.id);row.append(list);}}
    if(this.visual&&['stepCosts','dieCosts'].includes(desc.editor)&&object(value)){this.session.ui.costDrafts??={};let state=this.session.ui.costDrafts[pointer]??={base:value};if(JSON.stringify(state.base)!==JSON.stringify(value)&&!stored)state=this.session.ui.costDrafts[pointer]={base:value};const builder=el('div','','editor-domain-builder');row.append(builder);mountCostTableEditor(builder,{value,scale:this.pkg.system.dieScale||[],steps:desc.editor==='stepCosts',state,onEdit:state=>this.pending(path,{mode:'value',raw:'',builder:'costs',builderError:state.invalid}),onApply:async next=>{if(JSON.stringify(state.base)!==JSON.stringify(value))throw new Error('A tabela mudou desde a pendência. Revise antes de aplicar.');const done=await this.commit(setValueCommands(this.pkg,path,next),'Editar tabela de custos',path);if(done!==false){delete this.session.ui.costDrafts[pointer];this.pending(path);this.onPending?.(true);}}});}
    if(this.visual&&(path.at(-2)==='formulas'||desc.editor==='postAscensionFormula')){this.session.ui.formulaDrafts??={};let state=this.session.ui.formulaDrafts[pointer]??={base:value,formula:path.at(-1)};if(state.base!==value&&!stored){state=this.session.ui.formulaDrafts[pointer]={base:value,formula:path.at(-1)};}const builder=el('div','','editor-domain-builder');row.append(builder);mountFormulaBuilder(builder,{expression:stored?.raw??value??'',pkg:this.pkg,...(desc.editor==='postAscensionFormula'?{contextVariables:{n:1}}:{}),state:this.session.ui.formulaDrafts[pointer],onEdit:(text,state)=>{presence.value='value';input.value=text;this.pending(path,{mode:'value',raw:text,builder:'formula',builderError:state.invalid||state.error});},onApply:async text=>{if(state.base!==value)throw new Error('Este cálculo mudou desde a pendência. Revise e descarte ou copie a pendência antes de aplicar.');const done=await this.commit(setValueCommands(this.pkg,path,text),'Construir cálculo',path);if(done!==false){delete this.session.ui.formulaDrafts[pointer];this.pending(path);this.onPending?.(true);}}});input.hidden=true;}
    if(this.visual&&((key==='value'&&path.some(key=>['expression','increment'].includes(key)))||diceLiteralAt(this.pkg,path))){this.session.ui.diceDrafts??={};let state=this.session.ui.diceDrafts[pointer]??={base:value};if(state.base!==value&&!stored)state=this.session.ui.diceDrafts[pointer]={base:value};const builder=el('div','','editor-domain-builder');row.append(builder);mountDiceEditor(builder,{value:stored?.raw??(typeof value==='string'?value:''),state,onEdit:(text,state)=>{presence.value='value';input.value=text;if(typeInput){typeInput.value='string';type='string';}this.pending(path,{mode:'value',raw:text,valueType:'string',builder:'dice',builderError:state.invalid});},onApply:async text=>{if(state.base!==value)throw new Error('Esta rolagem mudou desde a pendência. Revise antes de aplicar.');const done=await this.commit(setValueCommands(this.pkg,path,text),'Construir rolagem',path);if(done!==false){delete this.session.ui.diceDrafts[pointer];this.pending(path);this.onPending?.(true);}}});input.hidden=true;}
    if(this.visual&&desc.exclusive?.includes('resolver')){this.session.ui.rollSourceDrafts??={};let state=this.session.ui.rollSourceDrafts[pointer]??={base:value};if(JSON.stringify(state.base)!==JSON.stringify(value)&&!stored)state=this.session.ui.rollSourceDrafts[pointer]={base:value};const builder=el('div','','editor-domain-builder');row.append(builder);mountRollSource(builder,{pkg:this.pkg,path,value:value||{},state,expression:['expression','increment'].includes(key),onEdit:(next,state)=>{presence.value='value';this.pending(path,{mode:'value',raw:'',builder:'rollSource',builderError:state.invalid});},onApply:async next=>{if(JSON.stringify(state.base)!==JSON.stringify(value))throw new Error('A origem mudou desde a pendência. Revise antes de aplicar.');const done=await this.commit(setValueCommands(this.pkg,path,next),'Construir origem de valor',path);if(done!==false){delete this.session.ui.rollSourceDrafts[pointer];this.pending(path);this.onPending?.(true);}}});}
    if(this.visual&&conditionKind(path)){this.session.ui.conditionDrafts??={};let state=this.session.ui.conditionDrafts[pointer]??={base:value};if(JSON.stringify(state.base)!==JSON.stringify(value)&&!stored)state=this.session.ui.conditionDrafts[pointer]={base:value};const builder=el('div','','editor-domain-builder');row.append(builder);mountConditionBuilder(builder,{pkg:this.pkg,path,value,state,onEdit:(next,state)=>{presence.value='value';this.pending(path,{mode:'value',raw:'',builder:'condition',builderError:state.invalid});},onApply:async next=>{if(JSON.stringify(state.base)!==JSON.stringify(value))throw new Error('A condição mudou desde a pendência. Revise antes de aplicar.');const done=await this.commit(setValueCommands(this.pkg,path,next),'Construir condição',path);if(done!==false){delete this.session.ui.conditionDrafts[pointer];this.pending(path);this.onPending?.(true);}}});}
    if(this.visual&&((key==='default'&&owner?.type==='image')||(path[0]==='system'&&path[1]==='characterTemplate'&&structuralNodes(this.pkg).some(n=>n.value?.type==='image'&&n.value.field===path.slice(2).join('.'))))){mountLocalImage(row,{onPending:filename=>this.pending(path,{mode:'value',raw:input.value,builder:'image',builderError:'Preparando '+filename,base:value,existed:exists}),onValue:text=>{presence.value='value';input.value=text;if(typeInput){typeInput.value='string';type='string';}this.pending(path,{mode:'value',raw:text,valueType:'string',builder:'image',base:value,existed:exists});},onError:message=>this.pending(path,{mode:'value',raw:input.value,builder:'image',builderError:message,base:value,existed:exists})});}
    const mark=()=>{this.pending(path,{mode:presence.value,raw:input.value,...(typed?{valueType:type}:{})});row.dataset.pending='true';};
    presence.addEventListener('change',mark);input.addEventListener('input',()=>{presence.value='value';mark();});input.addEventListener('change',()=>{presence.value='value';mark();});
    typeInput?.addEventListener('change',()=>{type=typeInput.value;input.hidden=complex() || type==='null';presence.value=type==='null'?'null':'value';mark();this.onPending?.(true);});
    const feedback=el('p');feedback.setAttribute('role','status');
    row.append(button('Aplicar campo',async()=>{try{
      const mode=presence.value,imagePending=this.session.ui.formPending?.[pointer];if(imagePending?.builder==='image'){if(imagePending.builderError)throw new Error(imagePending.builderError);const current=valueAt(this.session.validation.value,path);if(current!==imagePending.base||Object.hasOwn(valueAt(this.session.validation.value,path.slice(0,-1))||{},path.at(-1))!==imagePending.existed)throw new Error('O valor da imagem mudou. Preserve ou descarte a pendência antes de aplicar.');}if(this.visual&&(this.session.ui.formulaDrafts?.[pointer]?.invalid||this.session.ui.diceDrafts?.[pointer]?.invalid||this.session.ui.conditionDrafts?.[pointer]?.invalid))throw new Error('Corrija ou descarte o texto inválido no construtor.');
      let next=mode==='default'?initialValue(desc):type==='null'||mode==='null'?null:complex()?(valueType(value)===type?value:initialValue({type})):input.value;
      if(mode==='value' && ['number','integer'].includes(type))next=numberFromText(input.value,{integer:type==='integer'});
      if(mode==='value' && type==='boolean'){if(!['true','false'].includes(input.value))throw new Error('Use true ou false.');next=input.value==='true';}
      if(mode==='absent' && this.remove){this.remove(path).catch(error=>feedback.textContent=error.message);return;}
      if(mode==='value'&&['condition','rollSource','costs'].includes(this.session.ui.formPending?.[pointer]?.builder))throw new Error('Use o botão Aplicar do construtor para confirmar os valores escolhidos.');
      const commands=setValueCommands(this.pkg,path,next,mode==='absent');
      if(mode==='value' && ownerDesc.exclusive?.includes(key))for(const other of ownerDesc.exclusive)if(other!==key && Object.hasOwn(owner,other))commands.push(...setValueCommands(this.pkg,[...path.slice(0,-1),other],null,true));
      const committed=await this.commit(commands,'Editar '+label,path);if(committed===false)return;this.pending(path);this.onPending?.(true);
    }catch(error){feedback.textContent=error.message;input.setAttribute('aria-invalid','true');}}));
    row.append(button('Descartar texto deste campo',()=>{delete this.session.ui.formulaDrafts?.[pointer];delete this.session.ui.diceDrafts?.[pointer];delete this.session.ui.conditionDrafts?.[pointer];delete this.session.ui.rollSourceDrafts?.[pointer];delete this.session.ui.costDrafts?.[pointer];this.pending(path);this.onPending?.(true);}),feedback);
    if(desc.shorthand)row.append(button('Expandir definição abreviada',()=>{this.commit(setValueCommands(this.pkg,path,{type:value}),'Expandir campo de item');this.onPending?.(true);}));
    if(value!==null && (object(value)||Array.isArray(value))){
      const nested=typed?{type:valueType(value),...(object(value)?{values:{type:'any'}}:{items:{type:'any'}})}:desc;
      if(nested.properties || nested.values || nested.items){const details=el('details','','editor-nested');details.dataset.nested=pointer;details.append(el('summary','Configurar '+label));const content=el('div');details.append(content);let rendered=false;
        const populate=()=>{if(!details.open || rendered)return;rendered=true;this.children(content,path,value,nested,depth+1);};
        details.addEventListener('toggle',()=>{this.session.ui.formOpen??={};if(details.open)this.session.ui.formOpen[pointer]=true;else delete this.session.ui.formOpen[pointer];populate();this.onPending?.();});
        details.open=this.session.ui.formOpen?.[pointer]===true;populate();row.append(details);
      }else{const details=el('details');details.append(el('summary','Editar dados por tipo'));let rendered=false;details.addEventListener('toggle',()=>{if(details.open&&!rendered){rendered=true;this.children(details,path,value,Array.isArray(value)?{type:'array',items:{type:'any'}}:{type:'object',values:{type:'any'}},depth+1);}});row.append(details);}
    }
    if(this.visual&&key==='variables'&&desc.values){const creator=el('div','','editor-variable-creator');row.append(creator);mountVariableCreator(creator,{pkg:this.pkg,path,desc,session:this.session,commit:this.commit,onPending:this.onPending});}
    if(path.at(-2)==='formulas')row.append(el('p','Expressão limitada da engine. Valide e atualize o ensaio para conferir o resultado.','editor-note'));
    parent.append(row);
  }
  children(parent,path,value,desc,depth) {
    if(Array.isArray(value)){
      inspectorPage(parent,path,value.map((item,index)=>[index,item]),this).forEach(([index,item])=>{const wrap=el('div','','editor-array-entry');wrap.dataset.entry=pointerFor([...path,index]);this.field(wrap,[...path,index],desc.items || {type:'any'},'Entrada '+(index+1),depth,desc);
        wrap.append(button('Remover entrada '+(index+1),()=>this.removeValue([...path,index])),button('Subir entrada '+(index+1),()=>{if(index)this.commit([{type:'moveNode',path,index,to:index-1}],'Mover entrada');}),button('Descer entrada '+(index+1),()=>{if(index<value.length-1)this.commit([{type:'moveNode',path,index,to:index+1}],'Mover entrada');}),button('Duplicar entrada '+(index+1),()=>{const copy=structuredClone(item);if(object(copy)&&copy.id)copy.id=copy.id+'-copia-'+crypto.randomUUID().slice(0,4);this.commit([{type:'insertNode',path,index:index+1,value:copy}],'Duplicar entrada');}));parent.append(wrap);});
      if(this.visual&&(desc.items?.properties?.id||desc.items?.properties?.key)){const name=el('input'),address=pointerFor(path)+'::entry-name';name.setAttribute('aria-label','Nome da nova entrada em '+labelFor(path.at(-1)));name.value=this.session.ui.formInputs?.[address]??'';name.addEventListener('input',()=>{this.session.ui.formInputs??={};this.session.ui.formInputs[address]=name.value;this.onPending?.();});parent.append(name,button('Criar entrada nomeada',()=>{if(!name.value.trim()){this.onPending?.(false,'Informe o nome mostrado da nova entrada.');return;}const identity=desc.items.properties.id?'id':'key',entry={[identity]:generatedKey(name.value,value.map(v=>v?.[identity])),...(desc.items.properties.label?{label:name.value}:{}),...(desc.items.properties.name?{name:name.value}:{})};this.commit([{type:'insertNode',path,index:value.length,value:entry}],'Criar entrada nomeada');}));}else parent.append(button('Adicionar entrada',()=>this.commit([{type:'insertNode',path,index:value.length,value:initialValue(desc.items || {type:'any'})}],'Adicionar entrada')));return;
    }
    const schema=desc.properties || Object.fromEntries(Object.keys(value).map(key=>[key,desc.values || {type:'any'}]));
    const entries=inspectorPage(parent,path,Object.entries(schema),this);for(const [key,child]of entries)this.field(parent,[...path,key],child,key,depth,desc);
    this.advanced(parent,path,value,new Set(Object.keys(schema)));
    if(this.visual&&desc.values?.itemField){this.itemFieldCreator(parent,path,value);return;}
    if(desc.values){const input=el('input');input.type='text';input.setAttribute('aria-label','Nova chave em '+pointerFor(path));const inputKey=pointerFor(path)+'::new-key';input.value=this.session.ui.formInputs?.[inputKey] ?? '';input.addEventListener('input',()=>{this.session.ui.formInputs??={};this.session.ui.formInputs[inputKey]=input.value;this.onPending?.();});parent.append(input,button('Adicionar propriedade',()=>{try{const key=this.visual?generatedKey(input.value,Object.keys(value)):safeKey(input.value);if(Object.hasOwn(value,key))throw new Error('Chave já existe.');this.commit(setValueCommands(this.pkg,[...path,key],initialValue(desc.values)),'Adicionar propriedade');}catch(error){input.setCustomValidity(error.message);input.reportValidity();}}));
      for(const [key]of entries){const row=el('div','','editor-key-actions'),rename=el('input');const renameKey=pointerFor([...path,key])+'::rename-key';rename.value=this.session.ui.formInputs?.[renameKey] ?? key;rename.addEventListener('input',()=>{this.session.ui.formInputs??={};this.session.ui.formInputs[renameKey]=rename.value;this.onPending?.();});rename.setAttribute('aria-label','Nova chave de '+key);const doRename=()=>{try{const newName=this.visual?generatedKey(rename.value,[]):rename.value;const result=this.rename?.([...path,key],newName) ?? this.commit(renameKeyCommands(this.pkg,[...path,key],rename.value),'Renomear propriedade');if(result?.catch)result.catch(error=>{rename.setCustomValidity(error.message);rename.reportValidity();});}catch(error){rename.setCustomValidity(error.message);rename.reportValidity();}};row.append(el('span','Chave: '+key),rename,button('Renomear '+key,doRename),button('Remover '+key,()=>this.removeValue([...path,key])));parent.append(row);}
    }
  }
  itemFieldCreator(parent,path,value){const name=el('input');name.setAttribute('aria-label','Nome do campo da coleção');const key=pointerFor(path)+'::field-name';name.value=this.session.ui.formInputs?.[key]||'';name.addEventListener('input',()=>{this.session.ui.formInputs??={};this.session.ui.formInputs[key]=name.value;this.onPending?.();});const type=choose('Tipo do campo da coleção',['text','textarea','number','boolean','select','die','reference'].map(t=>[t,{text:'Texto',textarea:'Texto longo',number:'Número',boolean:'Sim/Não',select:'Escolha',die:'Dado',reference:'Referência a outra coleção'}[t]]),'text');const options=el('textarea');options.setAttribute('aria-label','Opções do campo (uma por linha)');const collections=choose('Coleção de destino da referência',compatibleData(this.pkg,'list').map(r=>[r.field,displayData(r)]),'');for(const [suffix,control]of [['field-type',type],['field-options',options],['field-reference',collections]]){const address=pointerFor(path)+'::'+suffix;if(Object.hasOwn(this.session.ui.formInputs||{},address))control.value=this.session.ui.formInputs[address];for(const event of ['input','change'])control.addEventListener(event,()=>{this.session.ui.formInputs??={};this.session.ui.formInputs[address]=control.value;this.onPending?.();});}parent.append(name,type,options,collections,button('Criar campo da coleção',async()=>{try{const plan=addItemFieldPlan(this.pkg,path.slice(0,-1),{name:name.value,type:type.value,options:options.value.split(/\r?\n/).filter(Boolean),referenceCollection:collections.value});const done=await this.commit(plan.commands,'Criar campo de coleção',path);if(done!==false)this.onPending?.(true);}catch(error){this.onPending?.(false,error.message);}}));
    for(const key of Object.keys(value)){const rename=el('input');rename.setAttribute('aria-label','Novo nome do campo '+key);const address=pointerFor([...path,key])+'::item-rename';rename.value=this.session.ui.formInputs?.[address]??'';rename.addEventListener('input',()=>{this.session.ui.formInputs??={};this.session.ui.formInputs[address]=rename.value;this.onPending?.();});parent.append(rename,button('Religar campo '+key,()=>this.rename([...path,key],generatedKey(rename.value,[])).catch(error=>this.onPending?.(false,error.message))),button('Remover campo '+key,()=>this.removeValue([...path,key])));}
  }
  removeValue(path){if(this.remove)this.remove(path).catch(error=>this.onPending?.(false,error.message));else this.commit(setValueCommands(this.pkg,path,null,true),'Remover propriedade');}
}
