import {ACTION_OPERATIONS} from '../validation/actions.js';
import {RECOVERY_CONTRACT} from '../validation/contracts.js';
import {dataIndex,displayData} from './data-index.js';
import {itemFields} from './data-picker.js';
import {numberFromText} from './form-commands.js';
import {mountLiteral,readLiteral} from './literal-editor.js';
import {mountConditionBuilder,conditionValue} from './condition-builder.js';
import {actionRecipePlan,recoveryRecipePlan} from './rule-plans.js';
import {mountRollSource} from './roll-source-editor.js';
import {el,input,choose,button} from './authoring-dom.js';
export const OPERATION_LABELS={set:'Definir valor fixo',add:'Somar ou subtrair valor',restoreResource:'Completar recurso atual/máximo',rollResource:'Recuperar recurso rolando dados de uma coleção',reduceNamedStates:'Reduzir estados escolhidos',clearNamedStates:'Remover estados escolhidos',restoreCollection:'Completar valores de entradas',setCollection:'Definir valores de entradas',restoreValue:'Completar valor até um máximo'};
export function mountOperation(host,{pkg,state={},recovery=false,index=0,notify}){const types=recovery?RECOVERY_CONTRACT.operations:ACTION_OPERATIONS;state.type??=types[0];const type=choose('Operação '+(index+1),types.map(t=>[t,OPERATION_LABELS[t]]),state.type),body=el('div');host.append(type.wrap,body);let read;
 const render=()=>{body.replaceChildren();state.type=type.input.value;const operation=state.type,rows=dataIndex(pkg).filter(r=>r.scope==='character'&&(['restoreResource','rollResource'].includes(operation)?r.resource:['restoreCollection','setCollection','reduceNamedStates','clearNamedStates'].includes(operation)?r.type==='collection':['add','restoreValue'].includes(operation)?r.type==='number':true));const field=choose('Dado alterado pela operação '+(index+1),[['','Escolha um dado'],...rows.map(r=>[r.field,displayData(r)])],state.field||'');field.input.addEventListener('change',()=>{state.field=field.input.value;notify?.();render();});body.append(field.wrap);const controls=[];const scalar=(key,label,{optional=false,integer=false}={})=>{const c=input(label,state[key]??'');body.append(c.wrap);c.input.addEventListener('input',()=>{state[key]=c.input.value;notify?.();});controls.push(op=>{if(optional&&c.input.value==='')return;op[key]=numberFromText(c.input.value,{integer});});};const path=(key,label,options,optional=false)=>{const c=choose(label,[['',optional?'Padrão do mecanismo / ausente':'Escolha uma fonte'],...options],state[key]||'');body.append(c.wrap);c.input.addEventListener('change',()=>{state[key]=c.input.value;notify?.();});controls.push(op=>{if(!c.input.value){if(optional)return;throw new Error('Escolha '+label+'.');}op[key]=c.input.value;});};
 const itemOptions=itemFields(pkg,field.input.value),items=(types)=>itemOptions.filter(f=>!types||types.includes(f.type)).map(f=>[f.key,f.label+' · '+f.type]);
 if(operation==='set'){state.literal??={};const value=el('div');body.append(value);const get=mountLiteral(value,{state:state.literal,label:'Valor a definir',simple:recovery,notify});controls.push(op=>op.value=get());}
 if(operation==='add'){scalar('amount','Quantidade a somar (negativa para gastar)');scalar('min','Limite mínimo após somar',{optional:true});}
 if(operation==='restoreValue')path('maxField','Máximo deste valor',dataIndex(pkg).filter(r=>r.scope==='character'&&r.type==='number').map(r=>[r.field,displayData(r)]));
 if(operation==='rollResource'){const collections=dataIndex(pkg).filter(r=>r.scope==='character'&&r.type==='collection');const source=choose('Coleção que fornece os dados',[['','Escolha coleção'],...collections.map(r=>[r.field,displayData(r)])],state.sourceField||'');body.append(source.wrap);const dice=el('div');body.append(dice);let die;const draw=()=>{dice.replaceChildren();die=choose('Dado de cada entrada',[['','Escolha campo de dado'],...itemFields(pkg,source.input.value).filter(f=>['die','number'].includes(f.type)).map(f=>[f.key,f.label+' · '+f.type])],state.dieField||'');die.input.addEventListener('change',()=>{state.dieField=die.input.value;notify?.();});dice.append(die.wrap);};source.input.addEventListener('change',()=>{state.sourceField=source.input.value;notify?.();draw();});draw();controls.push(op=>{if(!source.input.value||!die.input.value)throw new Error('Escolha coleção e dado de recuperação.');op.sourceField=source.input.value;op.dieField=die.input.value;});}
 if(['restoreCollection','setCollection'].includes(operation)){path('valueField','Valor recuperado de cada entrada',items(['number','die']));if(operation==='restoreCollection')path('maxField','Máximo de cada entrada',items(['number']));else scalar('value','Valor inteiro para cada entrada',{integer:true});const filter=choose('Quais entradas recuperar',[['all','Todas as entradas'],['selected','Somente entradas com valores escolhidos']],state.filterMode||'all');body.append(filter.wrap);const filters=el('div');body.append(filters);let filterField;state.filters??=[{type:'string',raw:''}];const draw=()=>{filters.replaceChildren();state.filterMode=filter.input.value;if(filter.input.value==='all')return;filterField=choose('Campo do filtro',[['','Escolha campo'],...items(['select','text','boolean','number','string'])],state.filterField||'');filters.append(filterField.wrap);filterField.input.addEventListener('change',()=>{state.filterField=filterField.input.value;notify?.();});state.filters.forEach((v,i)=>{const wrap=el('fieldset');wrap.append(el('legend','Valor aceito '+(i+1)));mountLiteral(wrap,{state:v,label:'Valor aceito '+(i+1),simple:true,notify});wrap.append(button('Remover valor aceito '+(i+1),()=>{state.filters.splice(i,1);draw();notify?.();}));filters.append(wrap);});filters.append(button('Acrescentar valor ao filtro',()=>{state.filters.push({type:'string',raw:''});draw();notify?.();}));};filter.input.addEventListener('change',()=>{draw();notify?.();});draw();controls.push(op=>{if(filter.input.value==='all')return;if(!filterField?.input.value||!state.filters.length)throw new Error('Escolha campo e valores do filtro.');op.filterField=filterField.input.value;op.filterValues=state.filters.map(v=>readLiteral(v,{simple:true}));});scalar('requireCurrentMin','Exigir saldo atual de pelo menos',{optional:true,integer:true});}
 if(['reduceNamedStates','clearNamedStates'].includes(operation)){const names=input('Nomes dos estados (separados por vírgula)',state.names||'');body.append(names.wrap);names.input.addEventListener('input',()=>{state.names=names.input.value;notify?.();});controls.push(op=>{op.names=names.input.value.split(',').map(n=>n.trim()).filter(Boolean);if(!op.names.length)throw new Error('Informe ao menos um nome de estado.');});path('gradeField','Dado graduado do estado',items(['die','number']),true);path('recoverableField','Marcação de estado recuperável',items(['boolean']),true);if(operation==='reduceNamedStates')scalar('steps','Quantidade de passos a reduzir',{integer:true});}
 if(recovery&&!['restoreCollection','setCollection'].includes(operation))scalar('requireCurrentMin','Exigir saldo atual de pelo menos',{optional:true,integer:true});const label=input('Descrição desta operação',state.label||'');body.append(label.wrap);label.input.addEventListener('input',()=>{state.label=label.input.value;notify?.();});read=()=>{if(!field.input.value)throw new Error('Escolha o dado alterado.');const op={type:operation,field:field.input.value};controls.forEach(fn=>fn(op));if(label.input.value.trim())op.label=label.input.value;return op;};};type.input.addEventListener('change',()=>{state.type=type.input.value;render();notify?.();});render();return ()=>read();}
export function mountActionRecipe(host,{pkg,state={},recovery=false,notify}){state.operations??=[{type:recovery?'restoreValue':'set'}];state.requirements??=[];const operations=el('div');host.append(el('h3',recovery?'Configurar recuperação':'Configurar ação'),el('p','Ações executam ao acionar o botão. Recuperações oferecem prévia e confirmação antes de alterar a amostra. Custos e decisões narrativas precisam ser declarados; edição direta não cobra evolução.','editor-note'),operations);let reads=[];const render=()=>{operations.replaceChildren();reads=state.operations.map((op,i)=>{const box=el('fieldset');box.append(el('legend','Operação '+(i+1)));const read=mountOperation(box,{pkg,state:op,recovery,index:i,notify});box.append(button('Remover operação '+(i+1),()=>{state.operations.splice(i,1);render();notify?.();}));operations.append(box);return read;});operations.append(button('Acrescentar operação',()=>{state.operations.push({type:recovery?'restoreValue':'set'});render();notify?.();}));};render();const note=input('Ajuda e decisões da mesa para esta ação',state.note||'');host.append(note.wrap);note.input.addEventListener('input',()=>{state.note=note.input.value;notify?.();});
 const requirements=el('div');if(!recovery){host.append(requirements);const draw=()=>{requirements.replaceChildren();state.requirements.forEach((r,i)=>{const box=el('fieldset');box.append(el('legend','Requisito '+(i+1)));const conditionHost=el('div');box.append(conditionHost);mountConditionBuilder(conditionHost,{pkg,path:['system','sheetActions',0,'requirements',i],value:r.base||{},state:r,onEdit:()=>notify?.(),onApply:()=>notify?.()});const message=input('Mensagem se requisito '+(i+1)+' falhar',r.message||'');box.append(message.wrap);message.input.addEventListener('input',()=>{r.message=message.input.value;notify?.();});box.append(button('Remover requisito '+(i+1),()=>{state.requirements.splice(i,1);draw();notify?.();}));requirements.append(box);});requirements.append(button('Acrescentar requisito',()=>{state.requirements.push({});draw();notify?.();}));};draw();}
 let readHealing;const healing=choose('Recuperação por dados',[['no','Sem dados de cura'],['yes','Dados limitados e resultado manual']],state.healingMode||'no');if(recovery){host.append(healing.wrap);const body=el('div');host.append(body);const draw=()=>{body.replaceChildren();state.healingMode=healing.input.value;readHealing=null;if(healing.input.value!=='yes')return;state.healing??={};const fields=[['field','Valor atual a curar'],['maxField','Máximo do valor curado'],['totalField','Total de dados de cura'],['usedField','Dados de cura usados'],['dieField','Dado da cura']];const controls=fields.map(([key,label])=>{const r=dataIndex(pkg).filter(r=>r.scope==='character'&&(key==='dieField'?r.type==='string':r.type==='number')),c=choose(label,[['','Escolha fonte'],...r.map(r=>[r.field,displayData(r)])],state.healing[key]||'');body.append(c.wrap);c.input.addEventListener('change',()=>{state.healing[key]=c.input.value;notify?.();});return [key,c.input];});const modifier=el('div');body.append(modifier);state.healing.modifier??={};const readModifier=mountRollSource(modifier,{pkg,state:state.healing.modifier,title:'Modificador da cura',onEdit:()=>notify?.()});const minimum=input('Mínimo de cura por dado',state.healing.minimum??'0');body.append(minimum.wrap);minimum.input.addEventListener('input',()=>{state.healing.minimum=minimum.input.value;notify?.();});readHealing=()=>{const h=Object.fromEntries(controls.map(([key,c])=>{if(!c.value)throw new Error('Escolha todas as fontes da cura.');return [key,c.value];}));h.modifier=readModifier();h.minimum=numberFromText(minimum.input.value,{integer:true});return h;};};healing.input.addEventListener('change',()=>{draw();notify?.();});draw();}
 return ({name,destination})=>{if(!reads.length&&!readHealing)throw new Error('Acrescente operação ou cura antes de incluir.');const action={operations:reads.map(read=>read())};if(note.input.value)action[recovery?'help':'note']=note.input.value;if(recovery&&readHealing)action.healing=readHealing();if(!recovery&&state.requirements.length)action.requirements=state.requirements.map(r=>({...conditionValue(r,r.base||{}),...(r.message?{message:r.message}:{})}));return (recovery?recoveryRecipePlan:actionRecipePlan)(pkg,{name,destination,action});};
}
