import {recipeControls} from './recipe-controls.js';
import {dataIndex,displayData,generatedKey} from './data-index.js';
import {itemFields} from './data-picker.js';
import {mountLiteral} from './literal-editor.js';
import {mountFormulaBuilder} from './formula-builder.js';
import {printFormula} from './formula-codec.js';
import {insertionPlan} from './composition-commands.js';
import {setValueCommands} from './form-commands.js';
import {validateFormula} from '../engine/formula.js';
import {el} from './authoring-dom.js';

export function poolRecipePlan(pkg,{name,destination,sources,resolution,opposition}){
 if(!sources?.length||sources.some(s=>!s.label?.trim()))throw new Error('Acrescente fontes e nomeie cada traço.');
 const plan=insertionPlan(pkg,{type:'poolBuilder',name,destination,prototype:{type:'poolBuilder',label:name,traitSources:sources.map((s,i)=>({...structuredClone(s),id:s.id||'fonte_'+(i+1)}))}});
 if(resolution){validateFormula(resolution.expression);const key=generatedKey(name+' dificuldade',Object.keys(pkg.system.formulas||{}));if(!pkg.system.formulas)plan.commands.unshift(...setValueCommands(pkg,['system','formulas'],{}));plan.commands.push(...setValueCommands(pkg,['system','formulas',key],resolution.expression),...setValueCommands(pkg,['system','resolution'],{...pkg.system.resolution,type:'d20-above-difficulty',difficultyFormula:key,criticalSuccessAt:resolution.criticalSuccessAt,criticalFailureAt:resolution.criticalFailureAt,note:resolution.note}));plan.dependencies.push('Alterar resolução compartilhada por Pool e técnicas: dificuldade pelo cálculo escolhido, d20 acima da dificuldade.');}
 else if(!pkg.system.formulas?.[pkg.system.resolution?.difficultyFormula||'difficulty'])throw new Error('Configure o cálculo de dificuldade para poder resolver o Pool.');
 if(opposition){const used=[];const passivePresets=opposition.map(row=>{if(!row.label?.trim()||!row.dice?.length||row.dice.some(d=>!Number.isInteger(d)||d<1))throw new Error('Nomeie oposições e informe dados positivos.');const id=generatedKey(row.label,used);used.push(id);return {...structuredClone(row),id};});plan.commands.push(...setValueCommands(pkg,['system','opposition'],{...pkg.system.opposition,passivePresets}));plan.dependencies.push('Substituir somente a lista de oposições passivas; demais metadados preservados.');}
 return plan;
}
export function mountPoolRecipe(host,{pkg,state={},notify}){
 const c=recipeControls(host,state,notify),rows=dataIndex(pkg),character=rows.filter(r=>r.scope==='character'),system=rows.filter(r=>r.scope==='system');
 const sources=c.rows('fonte do Pool','sources',[{label:'',kind:'constant',sides:''}],(r,row,i,box)=>{
  const label=r.text('Nome do traço no Pool '+(i+1),'label'),kind=r.select('Origem do traço no Pool '+(i+1),'kind',[['constant','Dado informado'],['system','Dado do sistema'],['field','Traço da ficha'],['entries','Traços de um mapa'],['characterCollection','Entradas de uma coleção'],['systemCollection','Catálogo vinculado à ficha']],'constant'),body=el('div');box.append(body);let read;
  const draw=()=>{body.replaceChildren();const b=recipeControls(body,row,notify);
   if(kind()==='constant'){const sides=b.number('Faces do traço no Pool '+(i+1),'sides','',{integer:true});read=()=>{const v=sides();if(v<1)throw new Error('Faces devem ser positivas.');return {kind:'constant',sides:v};};}
   else if(kind()==='system'){const source=b.select('Dado do sistema no Pool '+(i+1),'sidesFrom',[['','Escolha um dado'],...system.filter(d=>d.type==='number').map(d=>[d.field,displayData(d)])]);read=()=>({kind:'constant',sidesFrom:source()});}
   else if(['field','entries'].includes(kind())){const source=b.select('Dado da ficha no Pool '+(i+1),'field',[['','Escolha um dado'],...character.filter(d=>kind()==='entries'?d.type==='object'&&!d.resource:d.type==='number'||d.type==='object'&&!d.resource).map(d=>[d.field,displayData(d)])]);read=()=>({kind:kind(),field:source(),...(kind()==='entries'?{id:'fonte_'+(i+1)+':{key}',label:label()+' · {key}'}:{})});}
   else {
    const from=kind()==='systemCollection'?'system':'character',collection=b.select('Coleção do Pool '+(i+1),'collection',[['','Escolha uma coleção'],...(from==='system'?system:character).filter(d=>d.type==='collection').map(d=>[d.field,displayData(d)])]),detail=el('div');body.append(detail);let sides=()=>'',require=()=>'',exclude=()=>false,excludedValue=()=>undefined;
    const drawItems=()=>{detail.replaceChildren();const d=recipeControls(detail,row,notify),items=from==='character'?itemFields(pkg,collection()):[...new Set((system.find(s=>s.field===collection())?.value||[]).filter(v=>v&&typeof v==='object').flatMap(v=>Object.keys(v)))].map(key=>({key,label:key}));
     if(from==='system'){const map=d.select('Mapa de valores do catálogo no Pool '+(i+1),'map',[['','Escolha um mapa'],...character.filter(v=>v.type==='object'&&!v.resource).map(v=>[v.field,displayData(v)])]),key=d.select('Identidade do catálogo no Pool '+(i+1),'catalogKey',[['','Escolha o identificador'],...items.map(f=>[f.key,f.label])]);sides=()=>map()&&key()?map()+'.{'+key()+'}':'';}
     else sides=d.select('Dado de cada entrada no Pool '+(i+1),'valueField',[['','Escolha o dado'],...items.filter(f=>['die','number','object'].includes(f.type)).map(f=>[f.key,f.label])]);
     require=d.select('Incluir somente com campo preenchido no Pool '+(i+1),'require',[['','Sem filtro de preenchimento'],...items.map(f=>[f.key,f.label])]);
     const excluded=d.select('Excluir quando este campo for igual no Pool '+(i+1),'excludeField',[['','Sem exclusão'],...items.map(f=>[f.key,f.label])]);exclude=excluded;row.excludedValue??={};const literal=el('div');detail.append(literal);excludedValue=mountLiteral(literal,{state:row.excludedValue,label:'Valor que exclui a entrada '+(i+1),notify});
    };body.querySelector('select').addEventListener('change',drawItems);drawItems();read=()=>({from,collection:collection(),sides:sides(),...(require()?{require:require()}:{}),...(exclude()?{excludeWhen:{field:exclude(),equals:excludedValue()}}:{})});
   }
  };box.querySelector('[aria-label="Origem do traço no Pool '+(i+1)+'"]').addEventListener('change',draw);draw();return ()=>{const source=read();if(['field','sidesFrom','collection','sides'].some(k=>Object.hasOwn(source,k)&&source[k]===''))throw new Error('Escolha todas as fontes do traço.');return {label:label(),...source};};
 });
 const configure=c.select('Resolução compartilhada do Pool','resolutionMode',[[pkg.system.formulas?.[pkg.system.resolution?.difficultyFormula||'difficulty']?'keep':'','Usar resolução existente'],['new','Construir dificuldade e limiares']],pkg.system.formulas?.[pkg.system.resolution?.difficultyFormula||'difficulty']?'keep':'new'),resolution=el('div');host.append(resolution);state.resolution??={};const rc=recipeControls(resolution,state.resolution,notify),success=rc.number('Sucesso crítico até dificuldade','criticalSuccessAt','0'),failure=rc.number('Falha crítica a partir de dificuldade','criticalFailureAt','20'),note=rc.text('Decisões manuais da resolução','note'),formula=el('div');resolution.append(formula);state.formula??={};mountFormulaBuilder(formula,{pkg,expression:'0',state:state.formula,contextVariables:{actorWeight:0,opponentWeight:0},onEdit:()=>{state.formulaTouched=true;notify?.();},onApply:()=>{state.formulaTouched=true;notify?.();}});const show=()=>{resolution.hidden=configure()!=='new';};host.querySelector('[aria-label="Resolução compartilhada do Pool"]').addEventListener('change',show);show();
 const editOpposition=c.yes('Configurar oposições passivas','editOpposition'),op=el('div');host.append(op);const presets=c.rows('oposição passiva','opposition',[],(p,row,i)=>{const label=p.text('Nome da oposição '+(i+1),'label'),dice=p.rows('dado da oposição '+(i+1),'dice',[{sides:''}],(d,item,j)=>{const sides=d.number('Faces '+(j+1)+' da oposição '+(i+1),'sides','',{integer:true});return sides;});return ()=>({label:label(),dice:dice()});},op);const showOpposition=()=>{op.hidden=!editOpposition();};host.querySelector('[aria-label="Configurar oposições passivas"]').addEventListener('change',showOpposition);showOpposition();
 host.append(el('p','Pool usa Ápice + Base para Peso e os dados restantes para Potência. A resolução atual compara um d20 à dificuldade, com limiares críticos configuráveis. Alterar dificuldade ou oposição afeta todos os painéis que as compartilham.','editor-note'));
 return ({name,destination})=>{if(!configure())throw new Error('Escolha construir uma resolução.');if(configure()==='new'&&(!state.formulaTouched||state.formula.invalid))throw new Error('Monte e corrija o cálculo de dificuldade.');return poolRecipePlan(pkg,{name,destination,sources:sources(),...(configure()==='new'?{resolution:{expression:printFormula(state.formula.ast),criticalSuccessAt:success(),criticalFailureAt:failure(),note:note()}}:{}),...(editOpposition()?{opposition:presets()}:{})});};
}
