import {recipeControls,costTableControls} from './recipe-controls.js';
import {progressionRecipePlan} from './progression-plans.js';
import {dataIndex,displayData} from './data-index.js';
import {itemFields} from './data-picker.js';
import {mountFormulaBuilder} from './formula-builder.js';
import {printFormula} from './formula-codec.js';
import {el} from './authoring-dom.js';

export function mountProgressionRecipe(host,{pkg,type,state={},notify}){
 const c=recipeControls(host,state,notify),scale=pkg.system.dieScale||[4,6,8,10,12],dieOptions=scale.map(v=>[String(v),'d'+v]),fields=dataIndex(pkg).filter(r=>r.scope==='character');
 const collectionOptions=[['','Criar coleção com controles'],...fields.filter(r=>r.type==='collection').map(r=>[r.field,displayData(r)])];
 const itemPick=(controls,label,key,field,types,optional=false)=>controls.select(label,key,[['',optional?'Não usar':'Escolha o campo'],...itemFields(pkg,field).filter(f=>!types||types.includes(f.type)).map(f=>[f.key,f.label])]);
 let read;
 if(type==='repertoire'){
  const spec=c.select('Coleção de especializações','specializationsField',collectionOptions),tech=c.select('Coleção das técnicas conhecidas','techniquesField',collectionOptions),detail=el('div');host.append(detail);let grade=()=>'',link=()=>'';
  const draw=()=>{detail.replaceChildren();const d=recipeControls(detail,state,notify);grade=spec()?itemPick(d,'Grau de cada especialização','gradeField',spec(),['die','number']):()=>'';link=tech()?itemPick(d,'Vínculo da técnica com a especialização','linkField',tech(),['reference','text','string']):()=>'';};host.querySelectorAll('select').forEach(s=>s.addEventListener('change',draw));draw();
  const progression=c.rows('grau do repertório','progression',[{die:String(scale[0]),freeCount:'',grants:[{count:'',sides:String(scale[0])}]}],(r,row,i)=>{const die=r.select('Dado do grau '+(i+1),'die',dieOptions,String(scale[0])),free=r.number('Mínimo garantido no grau '+(i+1),'freeCount','',{integer:true}),grants=r.rows('distribuição do grau '+(i+1),'grants',[{count:'',sides:String(scale[0])}],(g,grant,j)=>{const count=g.number('Quantidade '+(j+1)+' no grau '+(i+1),'count','',{integer:true}),sides=g.select('Dado '+(j+1)+' no grau '+(i+1),'sides',dieOptions,String(scale[0]));return ()=>({count:count(),sides:Number(sides())});});return ()=>({die:Number(die()),freeCount:free(),grants:grants()});});
  host.append(el('p','A distribuição acompanha o repertório mínimo. A engine usa maxDie para o dado máximo e learningSource para separar outras origens. Os vínculos usam a identidade estável das entradas.','editor-note'));
  read=()=>{if(spec()&&!grade()||tech()&&!link())throw new Error('Escolha os campos da coleção existente.');return {specializationsField:spec(),techniquesField:tech(),gradeField:grade(),linkField:link(),progression:progression()};};
 } else {
  const presets=c.rows('qualidade','presets',[{label:'',points:'',maxDie:''}],(r,row,i)=>{const label=r.text('Nome da qualidade '+(i+1),'label'),points=r.number('Pontos da qualidade '+(i+1),'points','',{integer:true}),max=r.select('Teto inicial da qualidade '+(i+1),'maxDie',[['','Sem teto'],...dieOptions]);return ()=>({label:label(),points:points(),...(max()?{maxDie:Number(max())}:{})});});
  const adjustment=c.number('Ajuste inicial de pontos','adjustment','0'),awarded=c.number('Evolução recebida inicialmente','awarded','0');
  const sources=c.rows('fonte de pontos','sources',[{label:'',field:'',baseDie:String(scale[0])}],(r,row,i,box)=>{
   const label=r.text('Nome da fonte de pontos '+(i+1),'label'),field=r.select('Dados da fonte de pontos '+(i+1),'field',[...collectionOptions,...fields.filter(f=>f.type==='object'&&!f.resource).map(f=>[f.field,displayData(f)])]);
   const base=r.select('Dado base da fonte '+(i+1),'baseDie',[['0','Sem dado'],...dieOptions],String(scale[0])),creation=r.yes('Ignorar custo na criação da fonte '+(i+1),'skipCreation'),limit=r.yes('Aplicar teto da qualidade à fonte '+(i+1),'limitByQuality'),composite=r.yes('Permitir dados compostos na fonte '+(i+1),'allowComposite'),direct=r.yes('Custo de criação informado por entrada na fonte '+(i+1),'directCost');
   const detail=el('div');box.append(detail);let value=()=>'',cost=()=>'',evolution=()=>'',catalog=()=>'',labels=()=>'';
   const draw=()=>{detail.replaceChildren();const d=recipeControls(detail,row,notify),kind=fields.find(f=>f.field===field())?.type;if(kind==='collection'){value=itemPick(d,'Dado de cada entrada da fonte '+(i+1),'valueField',field(),['die','number']);evolution=itemPick(d,'Dado para evolução da fonte '+(i+1),'evolutionValueField',field(),['die','number'],true);if(direct())cost=itemPick(d,'Custo por entrada da fonte '+(i+1),'costField',field(),['number']);}else {value=()=>'';evolution=()=>'';cost=()=>'';}
    const systemRows=dataIndex(pkg).filter(f=>f.scope==='system'&&f.type==='collection');catalog=d.select('Catálogo de perícias da fonte '+(i+1),'catalogFrom',[['','Não usar'],...systemRows.map(f=>[f.field,displayData(f)])]);labels=d.select('Rótulos dos traços da fonte '+(i+1),'labelsFrom',[['','Não usar'],...systemRows.map(f=>[f.field,displayData(f)])]);};
   box.querySelectorAll('select').forEach(s=>s.addEventListener('change',draw));draw();const costs=el('div');box.append(costs);row.costs??={};const readCosts=costTableControls(costs,{scale,state:row.costs,notify,steps:true,label:'Custo da fonte '+(i+1)});
   return ()=>{const kind=fields.find(f=>f.field===field())?.type==='object'?'map':'list';if(field()&&kind==='list'&&!value())throw new Error('Escolha o dado da coleção de pontos.');if(field()&&direct()&&!cost())throw new Error('Escolha o custo de criação da coleção.');return {label:label(),field:field(),kind,baseDie:Number(base()),countCreation:!creation(),limitByQuality:limit(),allowComposite:composite(),directCost:direct(),costs:readCosts(),...(value()?{valueField:value()}:{}),...(cost()?{costField:cost()}:{}),...(evolution()?{evolutionValueField:evolution()}:{}),...(catalog()?{catalogFrom:catalog()}:{}),...(labels()?{labelsFrom:labels()}:{})};};
  });
  const modifiers=c.rows('modificador de pontos','modifiers',[],(r,row,i,box)=>{const label=r.text('Nome do modificador '+(i+1),'label'),field=r.select('Coleção do modificador '+(i+1),'field',collectionOptions),sign=r.select('Efeito do modificador '+(i+1),'sign',[['1','Acrescentar pontos'],['-1','Descontar pontos']],'1'),detail=el('div');box.append(detail);let value=()=>'';const draw=()=>{detail.replaceChildren();value=field()?itemPick(recipeControls(detail,row,notify),'Pontos de cada entrada do modificador '+(i+1),'valueField',field(),['number']):()=>'';};box.querySelectorAll('select').forEach(s=>s.addEventListener('change',draw));draw();return ()=>{if(field()&&!value())throw new Error('Escolha o valor do modificador.');return {label:label(),field:field(),sign:Number(sign()),valueField:value()};};});
  const post=c.yes('Oferecer custo por fórmula após ascensão','postEnabled'),body=el('div');host.append(body);state.postFormula??={};let mounted=false;
  const drawPost=()=>{body.hidden=!post();if(!post()||mounted)return;mounted=true;mountFormulaBuilder(body,{pkg,expression:'0',state:state.postFormula,contextVariables:{n:1},onEdit:()=>{state.postTouched=true;notify?.();},onApply:()=>{state.postTouched=true;notify?.();}});};host.querySelector('[aria-label="Oferecer custo por fórmula após ascensão"]').addEventListener('change',drawPost);drawPost();
  host.append(el('p','Informe os custos da campanha, inclusive zeros. A fórmula pós-ascensão recebe n, a quantidade de ascensões. Edição direta, fechamento de criação, evolução paga e narrativa continuam separados.','editor-note'));
  read=()=>{if(post()&&(!state.postTouched||state.postFormula.invalid))throw new Error('Monte e corrija a fórmula pós-ascensão.');return {presets:presets(),adjustment:adjustment(),awarded:awarded(),sources:sources(),modifiers:modifiers(),...(post()?{postAscension:printFormula(state.postFormula.ast)}:{})};};
 }
 return ({name,destination})=>progressionRecipePlan(pkg,{type,name,destination,config:{...read(),scale}});
}
