import {valueAt,object,destinations,structuralNodes} from './form-structure.js';
import {generatedKey} from './data-index.js';
import {setValueCommands} from './form-commands.js';
import {pointerFor} from './source-map.js';
import {calculationTargets} from '../validation/effects.js';
import {CHECK_UNITS} from '../validation/contracts.js';
const requireName=name=>{if(!String(name||'').trim())throw new Error('Informe o nome mostrado na ficha.');return name;};
function putMap(pkg,root,key,value){const map=pkg.system[root];if(map!==undefined&&!object(map))throw new Error('Repare '+root+' antes de criar a regra.');return [...(!map?setValueCommands(pkg,['system',root],{}):[]),...setValueCommands(pkg,['system',root,key],value)];}
function putArray(pkg,root,value){const array=pkg.system[root];if(array!==undefined&&!Array.isArray(array))throw new Error('Repare '+root+' antes de criar a regra.');return !array?setValueCommands(pkg,['system',root],[value]):[{type:'insertNode',path:['system',root],index:array.length,value}];}
function append(pkg,destination,component){if(!destinations(pkg,'component').some(d=>pointerFor(d.path)===pointerFor(destination)))throw new Error('Escolha um grupo válido.');return {command:{type:'insertNode',path:destination,index:valueAt(pkg,destination).length,value:component},selection:[...destination,valueAt(pkg,destination).length]};}
export function version2Plan(pkg,{system=false,layouts=[]}={}){const commands=[],notes=['Habilitar documentos versão 2 é explícito; não migra personagens instalados.'];if(pkg.schemaVersion<2)commands.push(...setValueCommands(pkg,['schemaVersion'],2));if(system&&pkg.system.schemaVersion<2)commands.push(...setValueCommands(pkg,['system','schemaVersion'],2));for(const li of layouts)if(pkg.layouts[li].schemaVersion<2)commands.push(...setValueCommands(pkg,['layouts',li,'schemaVersion'],2));return {commands,notes};}
export function checkRecipePlan(pkg,{name,destination,config,newData,buttonPath}){requireName(name);const key=generatedKey(name,Object.keys(pkg.system.checks||{})),rule=structuredClone(config);rule.sources=rule.sources.map((s,i)=>({...s,id:s.id||'source_'+(i+1)}));const commands=putMap(pkg,'checks',key,rule),dependencies=['Teste '+name+': '+rule.algorithm,'Decisões manuais: '+rule.note];if(newData)for(const data of Array.isArray(newData)?newData:[newData]){commands.unshift(...setValueCommands(pkg,['system','characterTemplate',data.field],data.value));dependencies.push('Novo dado: '+data.name);}const entry=append(pkg,destination,{type:'checkRoll',label:name,configFrom:'checks.'+key});commands.push(entry.command);if(buttonPath){const comp=valueAt(pkg,buttonPath),source=rule.sources.find(s=>comp.type==='computed'?s.formula===comp.formula:s.field===comp.field||s.collection===comp.field);if(!source)throw new Error('Escolha botão com a mesma fonte do teste.');const versions=version2Plan(pkg,{layouts:[buttonPath[1]]});commands.unshift(...versions.commands);commands.push(...setValueCommands(pkg,[...buttonPath,'roll'],{check:key,sourceId:source.id}));dependencies.push(...versions.notes);}return {commands,selection:entry.selection,dependencies,key};}
export function actionRecipePlan(pkg,{name,destination,action,historyField}){requireName(name);const key=generatedKey(name,(pkg.system.sheetActions||[]).map(a=>a.id)),commands=putArray(pkg,'sheetActions',{...structuredClone(action),id:key,label:name});const component={type:'actionGroup',label:name,actionsFrom:'sheetActions',...(historyField?{historyField}:{})},entry=append(pkg,destination,component);commands.push(entry.command);return {commands,selection:entry.selection,dependencies:['Ação '+name,'O painel compartilha a lista de ações do sistema; requisitos e operações são confirmados no ensaio.'],key};}
export function recoveryRecipePlan(pkg,{name,destination,action,historyField}){requireName(name);const key=generatedKey(name,(pkg.system.recoveryActions||[]).map(a=>a.id));historyField||=generatedKey(name+' registro',Object.keys(pkg.system.characterTemplate));const commands=putArray(pkg,'recoveryActions',{...structuredClone(action),id:key,label:name});const entry=append(pkg,destination,{type:'recoveryGroup',label:name,actionsFrom:'recoveryActions',historyField});commands.push(entry.command);return {commands,selection:entry.selection,dependencies:['Recuperação '+name,'Registro independente: '+historyField,'A mesa confirma recuperação, valores e condições.'],key};}
export function entryRollRecipePlan(pkg,{name,destination,config,collection,preference,newCollection}){requireName(name);const key=generatedKey(name,Object.keys(pkg.system.entryRolls||{})),commands=putMap(pkg,'entryRolls',key,structuredClone(config));let field=collection,schemas=structuralNodes(pkg).filter(n=>n.kind==='component'&&n.value?.field===field&&n.value?.itemSchema).map(n=>n.value.itemSchema);if(newCollection){field=generatedKey(name,Object.keys(pkg.system.characterTemplate));commands.unshift(...setValueCommands(pkg,['system','characterTemplate',field],[]));schemas=[{name:{type:'text',label:'Nome'}}];}if(!field)throw new Error('Escolha ou crie a coleção das entradas.');if(new Set(schemas.map(s=>JSON.stringify(s))).size>1)throw new Error('A coleção tem schemas diferentes; reutilize a apresentação desejada.');if(preference){if(Object.hasOwn(pkg.system.characterTemplate,preference.field))throw new Error('A preferência já existe; escolha a existente.');commands.unshift(...setValueCommands(pkg,['system','characterTemplate',preference.field],preference.value));}const entry=append(pkg,destination,{type:'list',label:name,field,itemSchema:structuredClone(schemas[0]||{name:{type:'text',label:'Nome'}}),entryAction:'roll',rollPreset:key});commands.push(entry.command);return {commands,selection:entry.selection,dependencies:['Rolagem compartilhada '+name,'Coleção '+field,...(config.resource?['Consumo opcional: recurso '+config.resource.field+'; nunca inferido pelo nome.']:['Sem consumo configurado.'])],key};}
export function effectRecipePlan(pkg,{name,destination,definition}){requireName(name);const key=generatedKey(name,(pkg.system.effectDefinitions||[]).map(d=>d.id)),def={...structuredClone(definition),id:key,label:name,revision:1,stacking:'unique'},versions=version2Plan(pkg,{system:true,layouts:pkg.layouts.map((_,i)=>i)}),commands=[...versions.commands,...putArray(pkg,'effectDefinitions',def)],dependencies=['Efeito numérico '+name,...versions.notes];let selection;for(const [li,layout]of pkg.layouts.entries()){const found=structuralNodes(pkg).some(n=>n.kind==='component'&&n.path[1]===li&&n.value?.type==='effectList');if(found)continue;const path=li===destination?.[1]?destination:['layouts',li,'tabs',0,'sections',0,'containers',0,'components'];const entry=append(pkg,path,{type:'effectList',label:'Efeitos'});commands.push(entry.command);selection??=entry.selection;dependencies.push('Painel Efeitos em '+(layout.name||layout.id));}return {commands,selection:selection||['system'],dependencies,key};}
export function effectTargetChoices(pkg){return [...[...calculationTargets(pkg)].map(key=>({kind:'calculation',key,label:'Cálculo: '+(structuralNodes(pkg).find(n=>n.value?.type==='computed'&&'computed.'+(n.value.overrideKey||n.value.formula)===key)?.title||key)})),...Object.entries(pkg.system.checks||{}).filter(([,c])=>CHECK_UNITS[c.algorithm]).map(([key,c])=>({kind:'checkModifier',key,unit:CHECK_UNITS[c.algorithm],label:'Teste: '+key+' · '+c.algorithm}))];}
export function copyRulePlan(pkg,path,name){requireName(name);const value=valueAt(pkg,path),parent=valueAt(pkg,path.slice(0,-1));if(Array.isArray(parent)){const copy=structuredClone(value);copy.id=generatedKey(name,parent.map(v=>v?.id));copy.label=name;if(path.includes('effectDefinitions'))copy.revision=1;return {commands:[{type:'insertNode',path:path.slice(0,-1),index:parent.length,value:copy}],path:[...path.slice(0,-1),parent.length],selection:['system'],dependencies:['Cópia independente da regra; dados referenciados continuam compartilhados.']};}if(!object(parent)||!object(value)&&!Array.isArray(value))throw new Error('Selecione uma definição de regra.');const key=generatedKey(name,Object.keys(parent));return {commands:setValueCommands(pkg,[...path.slice(0,-1),key],structuredClone(value)),path:[...path.slice(0,-1),key],key,selection:['system'],dependencies:['Cópia independente: '+name+'; os vínculos de dados permanecem.']};}
