import {recipeControls,costTableControls} from './recipe-controls.js';
import {dataIndex,displayData,generatedKey} from './data-index.js';
import {setValueCommands} from './form-commands.js';
import {destinations,valueAt} from './form-structure.js';
import {pointerFor} from './source-map.js';
import {el} from './authoring-dom.js';
import {itemFields} from './data-picker.js';

export const TECHNIQUE_TERMS={attribute:'Atributo escolhido',specialization:'Especialização escolhida',technique:'Dado da técnica',skill:'Perícia definida no modo',highestSpecialization:'Maior especialização',constant:'Dado de apoio'};
export function techniqueRecipePlan(pkg,{name,destination,config}){
 if(!String(name||'').trim())throw new Error('Informe o nome mostrado na ficha.');if(!destinations(pkg,'component').some(d=>pointerFor(d.path)===pointerFor(destination)))throw new Error('Escolha um grupo válido.');
 const scale=pkg.system.dieScale||config.scale;if(!Array.isArray(scale)||!scale.length)throw new Error('Configure a escala de dados.');
 const draft=structuredClone(pkg),commands=[],dependencies=[],companions=[];
 if(!pkg.system.dieScale){commands.push(...setValueCommands(pkg,['system','dieScale'],scale));dependencies.push('Escala compartilhada: '+scale.map(v=>'d'+v).join(', '));}
 const create=(scope,label,value)=>{const parent=scope==='character'?draft.system.characterTemplate:draft.system,key=generatedKey(label,Object.keys(parent));parent[key]=structuredClone(value);commands.push(...setValueCommands(pkg,scope==='character'?['system','characterTemplate',key]:['system',key],value));dependencies.push((scope==='character'?'Dado: ':'Regra: ')+label);return key;};
 const collection=(label,schema)=>{const field=create('character',label,[]);companions.push({type:'list',label,field,itemSchema:schema});return field;};
 const compatibleCollection=(field,requirements)=>{if(!field)return;const fields=itemFields(pkg,field);for(const [key,types]of Object.entries(requirements))if(!fields.some(f=>f.key===key&&types.includes(f.type)))throw new Error('A coleção '+field+' precisa do campo '+key+' compatível. Crie os dados guiados ou repare a coleção antes de incluir.');};
 compatibleCollection(config.specializationsField,{die:['die','number']});compatibleCollection(config.techniquesField,{maxDie:['die','number'],specializationId:['reference','text','string'],concentration:['boolean'],reverse:['boolean']});compatibleCollection(config.concentrationField,{techniqueId:['reference','text','string'],die:['die','number']});
 const rule={};
 if(config.attributesFrom){if(!config.attributesField)throw new Error('Escolha o mapa dos valores dos atributos.');rule.attributesFrom=config.attributesFrom;rule.attributesField=config.attributesField;}
 else {if(!config.attributes?.length||config.attributes.some(a=>!a.label?.trim()||!scale.includes(a.die)))throw new Error('Nomeie atributos e escolha dados da escala.');const used=[],attributes=config.attributes.map(a=>{const key=generatedKey(a.label,used);used.push(key);return {key,label:a.label};});rule.attributesFrom=create('system',name+' atributos',attributes);rule.attributesField=create('character',name+' valores de atributos',Object.fromEntries(attributes.map((a,i)=>[a.key,config.attributes[i].die])));attributes.forEach(a=>companions.push({type:'die',label:a.label,field:rule.attributesField+'.'+a.key}));}
 rule.specializationsField=config.specializationsField||collection(name+' especializações',{name:{type:'text',label:'Nome'},die:{type:'die',label:'Dado'}});
 rule.techniquesField=config.techniquesField||collection(name+' técnicas',{name:{type:'text',label:'Nome'},specializationId:{type:'reference',label:'Especialização',optionsFrom:'character.'+rule.specializationsField,valueField:'id',labelField:'name'},maxDie:{type:'die',label:'Dado máximo'},energyCost:{type:'number',label:'Custo específico',default:null},concentration:{type:'boolean',label:'Pode manter concentração'},reverse:{type:'boolean',label:'Pode reverter'}});
 if(!scale.includes(config.skillBaseDie))throw new Error('Escolha o dado base das perícias.');rule.skillBaseDie=config.skillBaseDie;
 rule.skillsField=config.skillsField||create('character',name+' perícias',{});
 rule.energyField=config.energyField;if(!rule.energyField){if(!Number.isFinite(config.energyCurrent)||!Number.isFinite(config.energyMax)||config.energyCurrent<0||config.energyMax<config.energyCurrent)throw new Error('Energia atual deve estar entre zero e máximo.');rule.energyField=create('character',name+' energia',{current:config.energyCurrent,max:config.energyMax});companions.push({type:'resource',label:'Energia',field:rule.energyField});}
 const costs={};for(const sides of scale){const cost=config.costs?.[sides];if(!Number.isFinite(cost)||cost<0)throw new Error('Informe cada custo de energia explicitamente, inclusive zero.');costs[sides]=cost;}rule.costsFrom=create('system',name+' custos de energia',costs);
 rule.concentrationField=config.concentrationField||collection(name+' concentração',{techniqueId:{type:'reference',label:'Técnica',optionsFrom:'character.'+rule.techniquesField,valueField:'id',labelField:'name'},die:{type:'die',label:'Dado mantido'}});
 rule.lastUseField=create('character',name+' último uso',null);
 const used=[];rule.modes=(config.modes||[]).map(m=>{if(!m.label?.trim()||!m.terms?.length||m.terms.some(t=>!Object.hasOwn(TECHNIQUE_TERMS,t)))throw new Error('Nomeie modos e selecione ao menos um termo do Pool.');if(m.terms.includes('constant')&&!scale.includes(m.constantDie))throw new Error('Escolha o dado de apoio da escala.');if(m.terms.includes('skill')&&!m.skill?.trim())throw new Error('Nomeie ou selecione a perícia usada no modo.');const id=generatedKey(m.label,used);used.push(id);return {...structuredClone(m),id};});if(!rule.modes.length)throw new Error('Crie ao menos um modo de uso.');
 if(!config.skillsField){const names=[...new Set(rule.modes.filter(m=>m.skill).map(m=>m.skill))];for(const skill of names){if(skill.includes('.')||['__proto__','constructor','prototype'].includes(skill))throw new Error('Use um nome de perícia sem ponto e sem palavras reservadas.');companions.push({type:'die',label:skill,field:rule.skillsField+'.'+skill});}
  const map=Object.fromEntries(names.map(skill=>[skill,config.skillBaseDie]));const command=commands.find(c=>pointerFor(c.path)===pointerFor(['system','characterTemplate',rule.skillsField]));command.value=map;}
 if(!pkg.system.formulas?.[pkg.system.resolution?.difficultyFormula||'difficulty'])dependencies.push('Antes de resolver resultado, configure a dificuldade compartilhada com a receita Pool. Usar e rolar continua disponível.');
 const configFrom=create('system',name+' configuração',rule),index=valueAt(pkg,destination).length;for(const [i,component]of [{type:'techniqueUse',label:name,configFrom},...companions].entries())commands.push({type:'insertNode',path:destination,index:index+i,value:component});
 dependencies.push('Custos são pagos ao Usar e rolar, inclusive em falha. Prévia continua isolada. Dados internos die, maxDie, specializationId e concentration são contratos desta família.');return {commands,selection:[...destination,index],dependencies};
}
export function mountTechniqueRecipe(host,{pkg,state={},notify}){
 const c=recipeControls(host,state,notify),scale=pkg.system.dieScale||[4,6,8,10,12],dice=scale.map(d=>[String(d),'d'+d]),index=dataIndex(pkg),character=index.filter(d=>d.scope==='character'),system=index.filter(d=>d.scope==='system');
 const pick=(label,key,rows)=>c.select(label,key,[['','Criar dados com controles'],...rows.map(r=>[r.field,displayData(r)])]);
 const attributesFrom=pick('Catálogo de atributos para técnicas','attributesFrom',system.filter(r=>r.type==='collection'&&r.value.every(v=>v&&typeof v.key==='string'))),attributesField=pick('Valores dos atributos para técnicas','attributesField',character.filter(r=>r.type==='object'&&!r.resource));
 const attributes=c.rows('atributo de técnicas','attributes',[{label:'',die:String(scale[0])}],(r,row,i)=>{const label=r.text('Nome do atributo de técnicas '+(i+1),'label'),die=r.select('Dado inicial do atributo '+(i+1),'die',dice,String(scale[0]));return ()=>({label:label(),die:Number(die())});});
 const specials=pick('Especializações usadas pelas técnicas','specializationsField',character.filter(r=>r.type==='collection')),techniques=pick('Técnicas aprendidas','techniquesField',character.filter(r=>r.type==='collection')),skills=pick('Mapa de perícias das técnicas','skillsField',character.filter(r=>r.type==='object'&&!r.resource)),base=c.select('Dado base de perícia para técnicas','skillBaseDie',dice,String(scale[0]));
 const energy=pick('Recurso de energia das técnicas','energyField',character.filter(r=>r.resource)),current=c.number('Energia atual inicial das técnicas','energyCurrent',''),maximum=c.number('Energia máxima inicial das técnicas','energyMax',''),concentration=pick('Instâncias de concentração','concentrationField',character.filter(r=>r.type==='collection'));
 state.costs??={};const costs=el('div');host.append(costs);const readCosts=costTableControls(costs,{scale,state:state.costs,notify,label:'Custo de energia'});
 const attributeChoices=()=>{const source=state.attributesFrom?valueAt(pkg,['system',...state.attributesFrom.replace(/^system\./,'').split('.')]):null;const used=[];return [['','Sem pré-seleção'],...(Array.isArray(source)?source.map(a=>[a.key,a.label||a.key]):(state.attributes||[]).filter(a=>a.label?.trim()).map(a=>{const key=generatedKey(a.label,used);used.push(key);return [key,a.label];}))];};
 const modes=c.rows('modo de técnica','modes',[{label:'',terms:[]}],(r,row,i,box)=>{const label=r.text('Nome do modo de técnica '+(i+1),'label'),terms=r.rows('termo do modo '+(i+1),'terms',[],(t,item,j)=>{const term=t.select('Termo '+(j+1)+' do modo '+(i+1),'term',Object.entries(TECHNIQUE_TERMS),'attribute');return term;});
  const defaultAttribute=r.select('Atributo pré-selecionado no modo '+(i+1),'defaultAttribute',attributeChoices);
  const booleans={};for(const [key,description]of [['requiresTechnique','Exigir técnica aprendida'],['requiresSpecialization','Exigir especialização'],['requiresConcentration','Exigir concentração ativa'],['reverseOnFailure','Oferecer reversão em falha'],['failureImpact','Informar impacto em falha'],['free','Sem custo de energia']])booleans[key]=r.yes(description+' no modo '+(i+1),key);
  const origin=r.select('Origem do dado da técnica no modo '+(i+1),'techniqueFrom',[['','Dado escolhido'],['specialization','Especialização com reduções']]),reductions=r.number('Reduções da especialização no modo '+(i+1),'reductionSteps','0',{integer:true}),energyFrom=r.select('Base de energia no modo '+(i+1),'energyFrom',[['','Dado escolhido'],['original','Dado máximo original'],['specialization','Especialização']]),constant=r.select('Dado de apoio no modo '+(i+1),'constantDie',dice,String(scale[0])),skill=r.text('Nome da perícia no modo '+(i+1),'skill'),note=r.text('Orientações da mesa no modo '+(i+1),'note');
  return ()=>{const reductionSteps=reductions();if(reductionSteps<0)throw new Error('Reduções devem ser não negativas.');return {label:label(),...(defaultAttribute()?{defaultAttribute:defaultAttribute()}:{}),terms:terms(),...Object.fromEntries(Object.entries(booleans).map(([k,read])=>[k,read()])),...(origin()?{techniqueFrom:origin()}:{}),reductionSteps,...(energyFrom()?{energyFrom:energyFrom()}:{}),constantDie:Number(constant()),...(skill()?{skill:skill()}:{}),note:note()};};
 });host.append(el('p','Esta família usa os campos internos existentes para técnicas, especializações e concentração. Escolher coleção existente exige campos compatíveis; a criação guiada prepara todos. A resolução final compartilha a dificuldade configurada em Pool.','editor-note'));
 return ({name,destination})=>techniqueRecipePlan(pkg,{name,destination,config:{scale,attributesFrom:attributesFrom(),attributesField:attributesField(),attributes:attributesFrom()?undefined:attributes(),specializationsField:specials(),techniquesField:techniques(),skillsField:skills(),skillBaseDie:Number(base()),energyField:energy(),...(energy()?{}:{energyCurrent:current(),energyMax:maximum()}),concentrationField:concentration(),costs:readCosts(),modes:modes()}});
}
