import {test} from 'node:test';
import assert from 'node:assert/strict';
import {capabilityCatalog} from '../../js/editor/capability-catalog.js';
import {COMPONENT_CONTRACTS,ITEM_FIELD_CONTRACTS} from '../../js/validation/contracts.js';
import {insertionPlan,movePlan,moveChoices} from '../../js/editor/composition-commands.js';
import {dataIndex,generatedKey} from '../../js/editor/data-index.js';
import {minimalPackage} from '../../js/editor/minimal-package.js';
import {EditorSession} from '../../js/editor/session.js';
import {structuralNodes} from '../../js/editor/form-structure.js';
const destination=['layouts',0,'tabs',0,'sections',0,'containers',0,'components'];
test('14A.1 inventário por propriedade, contexto, consumidor e validador',()=>{
 const rows=capabilityCatalog();for(const [type,c]of Object.entries(COMPONENT_CONTRACTS))for(const key of Object.keys(c.properties))assert.ok(rows.some(r=>r.context==='component:'+type&&r.property===key&&r.consumer&&r.validation&&r.control&&r.tests?.length),type+'.'+key);
 for(const [type,c]of Object.entries(ITEM_FIELD_CONTRACTS))for(const key of Object.keys(c))assert.ok(rows.some(r=>r.context==='item:'+type&&r.property===key));
 assert.equal(rows.find(r=>r.context==='component:number'&&r.property==='min').inert,true);
});
test('14A.1 inclusão recurso, coleção e cálculo é atômica e undo preserva bytes/extras',()=>{
 const pkg=minimalPackage('visual');pkg.extra={nil:null,zero:0,no:false,empty:'',array:[]};const text=JSON.stringify(pkg,null,3),session=new EditorSession({text});
 for(const opts of [{type:'resource',name:'Energia',hasInitial:true,initial:{current:0,max:10}},{type:'list',name:'Contatos'},{type:'computed',name:'Defesa',formula:'10 + score'}]){
  const plan=insertionPlan(session.validation.value,{destination,...opts});const before=session.text;session.operate(plan.commands);assert.equal(session.validation.status,'ready',JSON.stringify(session.validation.diagnostics));assert.deepEqual(session.validation.value.extra,pkg.extra);session.replay('undo');assert.equal(session.text,before);
 }
 assert.equal(session.text,text);
});
test('14A.1 dado existente, ausência, colisões, destinos e revisão atrasada',()=>{
 const pkg=minimalPackage('visual'),session=new EditorSession({text:JSON.stringify(pkg)});const plan=insertionPlan(pkg,{type:'number',name:'Base',existingField:'score',destination});assert.equal(plan.commands.length,1);
 assert.throws(()=>insertionPlan(pkg,{type:'resource',name:'Energia',existingField:'score',destination}));assert.throws(()=>insertionPlan(pkg,{type:'text',name:'x',destination:['layouts']}));
 session.operate(insertionPlan(pkg,{type:'text',name:'Nota',destination}).commands);assert.equal(Object.hasOwn(session.validation.value.system.characterTemplate,'nota'),false);assert.equal(generatedKey('Nota',['nota','nota_2']),'nota_3');assert.throws(()=>session.operate(plan.commands,{expectedRevision:0}));
 assert.ok(dataIndex(pkg).some(d=>d.resource&&d.label==='Vida'));assert.equal(pkg.system.characterTemplate.health.current,5);
});
test('14A.1 movimento de repeat preserva definição e recusa interpolação incompatível',()=>{
 const pkg=minimalPackage('visual'),groups=pkg.layouts[0].tabs[0].sections[0].containers;groups[0].repeat={source:'attributes'};groups[0].components[0].field='attributes.{key}';groups.push({layout:{type:'stack'},components:[{type:'text',field:'identity.name'}]});const node=structuralNodes(pkg).find(n=>n.kind==='component');assert.throws(()=>movePlan(pkg,node,['layouts',0,'tabs',0,'sections',0,'containers',1,'components'],0),/repetição/);assert.equal(moveChoices(pkg,node,destination).length,4);
});

import {editableVisualDocument} from '../../js/editor/form-structure.js';
import {nodeSchema} from '../../js/editor/form-metadata.js';
import {ruleSchemaAt} from '../../js/editor/capability-catalog.js';
test('14C.1 contexto de impressão/cabeçalho e reparo parseável não escrevem defaults',()=>{const pkg=minimalPackage('repair');pkg.system=null;const text=JSON.stringify(pkg,null,3),session=new EditorSession({text});assert.equal(editableVisualDocument(session).system,null);assert.equal(session.text,text);assert.ok(nodeSchema('layout').showHeader);for(const kind of ['section','container'])assert.deepEqual(nodeSchema(kind).print.properties.compact.properties.presentation.enum,['cards','inline']);assert.ok(!nodeSchema('component',{type:'number'}).print.properties.compact.properties.presentation);assert.deepEqual(nodeSchema('component',{type:'list',itemSchema:{}}).print.properties.compact.properties.presentation.enum,['table','records']);});
test('14C.1 regra customizada é interpretada pelo consumidor, extras não viram regras',()=>{const pkg=minimalPackage('custom');pkg.system.own={commands:[]};pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'actionGroup',actionsFrom:'own.commands'});assert.equal(ruleSchemaAt(pkg,['system','own','commands']).items.properties.operations.items.properties.type.type,'string');assert.equal(ruleSchemaAt(pkg,['system','own']),null);assert.equal(ruleSchemaAt(pkg,['system','extra']),null);});

import {createDataPlan,relinkDataPlan,addItemFieldPlan,relinkItemPlan,repeatGroupPlan} from '../../js/editor/data-commands.js';
import {experimentRows,humanValue} from '../../js/editor/experiment-report.js';
import {layoutPlan} from '../../js/editor/layout-manager.js';
import {readiness} from '../../js/editor/package-readiness.js';
test('14D.2 prontidão usa revisão, prévia e pendências da sessão existente',()=>{
 const session=new EditorSession({text:JSON.stringify(minimalPackage('readiness'))}),before=session.text;assert.equal(readiness(session).canExport,true);assert.equal(readiness(session).canApply,false);assert.equal(readiness(session,{previewCurrent:true}).canApply,true);session.ui.formPending={'/system/name':{raw:'pendente'}};assert.equal(readiness(session,{previewCurrent:true}).canExport,false);assert.equal(readiness(session,{previewCurrent:true}).canApply,false);assert.equal(session.text,before);
});
test('14D.1 layouts nomeados preservam identidade e dados, explicam fallback e mantêm efeitos',()=>{
 const pkg=minimalPackage('layouts'),session=new EditorSession({text:JSON.stringify(pkg,null,3)}),original=session.text,plan=layoutPlan(pkg,{action:'copy',source:0,name:'Mesa',mode:'table'});session.operate(plan.commands);assert.equal(session.validation.status,'ready');let next=session.validation.value;assert.deepEqual(next.system,pkg.system);assert.equal(next.layouts[1].mode,'table');assert.equal(next.layouts[1].id,'mesa');assert.equal(next.layouts[0].id,'default');session.operate(layoutPlan(next,{action:'up',index:1}).commands);next=session.validation.value;assert.equal(next.layouts[0].id,'mesa');const remove=layoutPlan(next,{action:'remove',index:0});assert.match(remove.notes.join(' '),/primeiro layout restante/);session.operate(remove.commands);assert.equal(session.validation.value.layouts[0].id,'default');assert.deepEqual(session.validation.value.system,pkg.system);session.replay('undo');session.replay('undo');session.replay('undo');assert.equal(session.text,original);assert.throws(()=>layoutPlan(pkg,{action:'remove',index:0}));
});
test('14C.5 relatório da amostra distingue sentinelas e não escreve no pacote',()=>{
 const pkg=minimalPackage('report');Object.assign(pkg.system.characterTemplate,{nil:null,no:false,zero:0,empty:'',list:[]});const before=JSON.stringify(pkg),character=structuredClone(pkg.system.characterTemplate);character.score=0;character.no=true;const rows=experimentRows(pkg,character);assert.equal(rows.find(r=>r.field==='score').current,0);assert.equal(rows.find(r=>r.field==='no').changed,true);assert.equal(humanValue(undefined),'Ausente');assert.equal(humanValue(null),'null explícito');assert.equal(humanValue(false),'Não');assert.equal(humanValue(0),'0');assert.equal(humanValue(''),'Texto vazio');assert.equal(JSON.stringify(pkg),before);
});
test('14C.2 religação contextual alcança schemas compartilhados, checks e operações sem alterar coleção alheia',()=>{
 const pkg=minimalPackage('relink-context'),components=pkg.layouts[0].tabs[0].sections[0].containers[0].components,path=['layouts',0,'tabs',0,'sections',0,'containers',0,'components',4];pkg.system.characterTemplate.contacts=[{id:'stable',name:'Ana',die:4,current:0,extra:{nil:null}}];pkg.system.characterTemplate.others=[{id:'other',name:'Bia',die:8}];
 components.push({type:'list',label:'Contatos',field:'contacts',itemSchema:{name:{type:'text'},die:{type:'die'},current:{type:'number'}}},{type:'table',label:'Mesmos contatos',field:'contacts',itemSchema:{die:{type:'die',help:'Dado'},name:{type:'text'}}},{type:'list',label:'Outros',field:'others',itemSchema:{die:{type:'die'},name:{type:'text'}}});
 pkg.system.checks={contacts:{algorithm:'explodingTrait',sources:[{id:'contact',label:'Contato',collection:'contacts',valueField:'die'}],note:'Consequências manuais.'}};
 pkg.system.recoveryActions=[{id:'recover',label:'Recuperar',operations:[{type:'restoreCollection',field:'contacts',valueField:'current',maxField:'die'}]}];pkg.system.entryRolls={contacts:{check:{expression:{value:'1d20'},modifier:{itemField:'die'}},effect:{expression:{value:'1d6'}},scale:{base:{value:4},min:1,max:12},resource:{field:'others',mode:'remaining',matchField:'die',valueField:'die',cost:{value:0}}}};
 components[4].entryAction='roll';components[4].rollPreset='contacts';
 const session=new EditorSession({text:JSON.stringify(pkg,null,3)}),original=session.text,plan=relinkItemPlan(pkg,[...path,'itemSchema','die'],'grau');session.operate(plan.commands);assert.equal(session.validation.status,'ready',JSON.stringify(session.validation.diagnostics));const next=session.validation.value;
 assert.deepEqual(next.system.characterTemplate.contacts,[{id:'stable',name:'Ana',grau:4,current:0,extra:{nil:null}}]);assert.deepEqual(next.layouts[0].tabs[0].sections[0].containers[0].components[5].itemSchema.grau,{type:'die',help:'Dado'});assert.equal(next.system.checks.contacts.sources[0].valueField,'grau');assert.equal(next.system.recoveryActions[0].operations[0].maxField,'grau');assert.equal(next.system.entryRolls.contacts.check.modifier.itemField,'grau');assert.equal(next.system.entryRolls.contacts.resource.valueField,'die');assert.deepEqual(next.system.characterTemplate.others,pkg.system.characterTemplate.others);session.replay('undo');assert.equal(session.text,original);
});
import {dataChoices} from '../../js/editor/data-picker.js';
import {resolveSource,expandComponents} from '../../js/engine/layout-components.js';
import {computedValue} from '../../js/engine/computed-values.js';
test('14C.2 dados por nome e religação de fontes/fórmula preservam sentinelas e extras',()=>{const pkg=minimalPackage('data');pkg.extra={field:'score',nil:null};const session=new EditorSession({text:JSON.stringify(pkg)});const plan=relinkDataPlan(pkg,['system','characterTemplate','score'],'agilidade');session.operate(plan.commands);const next=session.validation.value;assert.equal(next.system.characterTemplate.agilidade,2);assert.equal(next.layouts[0].tabs[0].sections[0].containers[0].components[1].field,'agilidade');assert.equal(computedValue({...next.layouts[0].tabs[0].sections[0].containers[0].components[3],system:next.system,character:next.system.characterTemplate}),3);assert.deepEqual(next.extra,pkg.extra);session.replay('undo');assert.deepEqual(session.validation.value,pkg);for(const [type,value]of [['number',0],['boolean',false],['string',''],['null',null]]){session.operate(createDataPlan(session.validation.value,{name:type,type,hasInitial:true,value}).commands);assert.equal(session.validation.value.system.characterTemplate[type],value);}});
test('14C.2 campos de coleção/referência e template conservam IDs e dados extras ao religar',()=>{const pkg=minimalPackage('items');const compPath=['layouts',0,'tabs',0,'sections',0,'containers',0,'components',4];pkg.system.characterTemplate.contacts=[{id:'stable',name:'Ana',extra:{nil:null}}];pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'list',label:'Contatos',field:'contacts',itemSchema:{name:{type:'text'}},summaryFields:['name']});const session=new EditorSession({text:JSON.stringify(pkg)});session.operate(addItemFieldPlan(pkg,compPath,{name:'Contato ligado',type:'reference',referenceCollection:'contacts'}).commands);assert.equal(session.validation.status,'ready');session.operate(relinkItemPlan(session.validation.value,[...compPath,'itemSchema','name'],'nome').commands);assert.deepEqual(session.validation.value.system.characterTemplate.contacts,[{id:'stable',nome:'Ana',extra:{nil:null}}]);assert.deepEqual(session.validation.value.layouts[0].tabs[0].sections[0].containers[0].components[4].summaryFields,['nome']);});
test('14C.2 catálogo/repeat é definição única e seleção distingue fontes de entrada',()=>{const pkg=minimalPackage('repeat');pkg.system.catalog=[{id:'a',name:'Agilidade'},{id:'b',name:'Força'}];const session=new EditorSession({text:JSON.stringify(pkg)}),plan=repeatGroupPlan(pkg,{name:'Atributos',source:'catalog',entries:pkg.system.catalog,destination:['layouts',0,'tabs',0,'sections',0,'containers'],type:'number'});session.operate(plan.commands);assert.equal(session.validation.status,'ready',JSON.stringify(session.validation.diagnostics));const group=session.validation.value.layouts[0].tabs[0].sections[0].containers[1];assert.equal(group.components.length,1);assert.deepEqual(expandComponents(group,session.validation.value.system).map(c=>c.field),['atributos.a','atributos.b']);assert.ok(dataChoices(session.validation.value,[...plan.selection,'repeat','source'],'source').some(([v])=>v==='catalog'));assert.equal(resolveSource(session.validation.value.system,'catalog').length,2);assert.throws(()=>repeatGroupPlan(pkg,{name:'x',source:'catalog',entries:[{id:'x'},{id:'x'}],destination:['layouts',0,'tabs',0,'sections',0,'containers']}));});

import {FORMULA_OPERATIONS,formulaNodeFor,replaceFormulaNode} from '../../js/editor/formula-builder.js';
import {printFormula,renameFormulaIdentifiers} from '../../js/editor/formula-codec.js';
import {validateFormula,evaluate,FORMULA_LIMITS} from '../../js/engine/formula.js';
import {diceText} from '../../js/editor/dice-expression-editor.js';
import {parseDiceExpression} from '../../js/engine/dice-expression.js';
import {conditionKind,conditionValue} from '../../js/editor/condition-builder.js';
test('14C.3 operações/funções preservam avaliação, precedência e limites do parser real',()=>{const examples=['1+2*3','(1+2)*3','8-3-2','8/(2+2)','8%3','-2+4','!false','2==2','2!=3','2<3','2<=2','3>2','3>=3','true&&false','false||true','floor(2.9)','ceil(2.1)','round(2.6)','abs(-3)','sqrt(9)','min(2,3,1)','max(2,3,1)','if(true,4,2)'];for(const expression of examples)assert.equal(evaluate(printFormula(validateFormula(expression))),evaluate(expression),expression);assert.equal(evaluate(printFormula(formulaNodeFor('call:if',validateFormula('sqrt(4)')))),0);const ast=validateFormula('10+score');const next=replaceFormulaNode(ast,['right'],{op:'identifier',name:'agility'});assert.equal(evaluate(printFormula(next),{data:{agility:3}}),13);assert.equal(printFormula(ast),'(10 + score)');for(const [operation]of FORMULA_OPERATIONS){const n=formulaNodeFor(operation);if(operation==='identifier')n.name='score';assert.doesNotThrow(()=>validateFormula(printFormula(n)),operation);}assert.throws(()=>evaluate('if(true,2,missing)'));assert.throws(()=>validateFormula('('.repeat(FORMULA_LIMITS.depth+1)+'0'+')'.repeat(FORMULA_LIMITS.depth+1)));assert.equal(evaluate(printFormula({op:'literal',value:1e-7})),1e-7);assert.equal(renameFormulaIdentifiers('score + score_extra','score','agility'),'(agility + score_extra)');});
test('14C.3 dados de rolagem distinguem vazio/zero, grupos e textos inválidos',()=>{const s={empty:false,groups:[{count:'2',sides:'6'},{count:1,sides:8}],modifier:'-2'};assert.deepEqual(parseDiceExpression(diceText(s)),parseDiceExpression('2d6 + 1d8 - 2'));assert.equal(diceText({empty:true,groups:[],modifier:0}),'');assert.equal(diceText({empty:false,groups:[],modifier:0}),'0');for(const state of [{...s,modifier:'abc'},{...s,groups:[{count:'1.5',sides:6}]},{...s,groups:[{count:101,sides:6}]},{...s,invalid:'texto pendente'}])assert.throws(()=>diceText(state));});
test('14C.3 condições são limitadas pelo consumidor e conservam extras e sentinelas',()=>{assert.equal(conditionKind(['x','disabledWhen']),'disabledWhen');assert.equal(conditionKind(['system','sheetActions',0,'requirements',0]),'requirement');assert.equal(conditionKind(['x','operations',0]),null);const base={field:'score',equals:2,extensions:{nil:null}};assert.deepEqual(conditionValue({field:'enabled',comparison:'equals',type:'boolean',raw:'false'},base),{field:'enabled',equals:false,extensions:{nil:null}});assert.deepEqual(conditionValue({field:'score',comparison:'both',type:'number',raw:'0',minimum:'0'}),{field:'score',equals:0,min:0});assert.deepEqual(conditionValue({field:'note',comparison:'equals',type:'string',raw:''}),{field:'note',equals:''});assert.deepEqual(conditionValue({field:'note',comparison:'equals',type:'null',raw:''}),{field:'note',equals:null});assert.throws(()=>conditionValue({field:'score',comparison:'min',minimum:'abc'}));assert.throws(()=>conditionValue({field:'',comparison:'equals',type:'boolean',raw:'true'}));});

import {createVariablePlan,renameVariablePlan} from '../../js/editor/variable-commands.js';
test('14C.3 variável renomeada copia fórmula compartilhada sem afetar outros consumidores',()=>{const pkg=minimalPackage('vars');const components=pkg.layouts[0].tabs[0].sections[0].containers[0].components;components[3].variables={score:{field:'score'}};components.push({...components[3],label:'Outro',overrideKey:'other',variables:{score:{value:9}}});pkg.system.formulas.total='score + 1';const session=new EditorSession({text:JSON.stringify(pkg)}),path=['layouts',0,'tabs',0,'sections',0,'containers',0,'components',3,'variables','score'];session.operate(renameVariablePlan(pkg,path,'agilidade').commands);assert.equal(session.validation.status,'ready',JSON.stringify(session.validation.diagnostics));const next=session.validation.value,first=next.layouts[0].tabs[0].sections[0].containers[0].components[3],other=next.layouts[0].tabs[0].sections[0].containers[0].components[4];assert.equal(computedValue({...first,character:next.system.characterTemplate,system:next.system}),3);assert.equal(computedValue({...other,character:next.system.characterTemplate,system:next.system}),10);assert.notEqual(first.formula,other.formula);assert.equal(first.overrideKey,'total');assert.equal(other.formula,'total');assert.equal(next.system.formulas.total,'score + 1');session.replay('undo');assert.deepEqual(session.validation.value,pkg);assert.throws(()=>createVariablePlan(pkg,path.slice(0,-1),{name:'',kind:'value',value:0}));assert.equal(renameFormulaIdentifiers('score + score.value','score','agility',{exact:true}),'(agility + score.value)');});
