import {test} from 'node:test';
import assert from 'node:assert/strict';
import {minimalPackage} from '../../js/editor/minimal-package.js';
import {EditorSession} from '../../js/editor/session.js';
import {CHECK_ALGORITHMS,RECOVERY_CONTRACT} from '../../js/validation/contracts.js';
import {ACTION_OPERATIONS} from '../../js/validation/actions.js';
import {checkRecipePlan,actionRecipePlan,recoveryRecipePlan,entryRollRecipePlan,effectRecipePlan} from '../../js/editor/rule-plans.js';
import {prepareCheck} from '../../js/engine/checks.js';
import {executeSheetAction} from '../../js/engine/assistance.js';
import {recoveryPlan,applyRecovery,recoveryDie} from '../../js/engine/recovery.js';
import {prepareEntryRoll} from '../../js/engine/entry-roll-preparation.js';
import {activateEffect,confirmEffectEvent} from '../../js/engine/effects.js';
import {computedValue} from '../../js/engine/computed-values.js';
import {parseDiceExpression} from '../../js/engine/dice-expression.js';
import {readRollSource} from '../../js/editor/roll-source-editor.js';
import {assistedRecipePlan} from '../../js/editor/assisted-plans.js';
import {inventoryTotals} from '../../js/engine/assistance.js';
import {applyEffectToGradedState} from '../../js/engine/graded-state.js';
import {progressionRecipePlan} from '../../js/editor/progression-plans.js';
import {pointBudget,closeCreation,evolutionTargets,stepCost} from '../../js/engine/point-budget.js';
import {repertoireStatus} from '../../js/engine/assistance.js';
import {poolRecipePlan} from '../../js/editor/pool-recipe.js';
import {setSystem} from '../../js/engine/system.js';
import {resolveAction} from '../../js/engine/resolution.js';
import {techniqueRecipePlan,TECHNIQUE_TERMS} from '../../js/editor/technique-recipe.js';
import {readFileSync} from 'node:fs';
import {dndRecipePlan,DND_STATS} from '../../js/editor/dnd-recipe.js';
import {copyRulePlan} from '../../js/editor/rule-plans.js';
import {prepareDocument} from '../../js/validation/documents.js';
const destination=['layouts',0,'tabs',0,'sections',0,'containers',0,'components'];
const apply=(pkg,plan)=>{const text=JSON.stringify(pkg,null,3),session=new EditorSession({text});session.operate(plan.commands);assert.equal(session.validation.status,'ready',JSON.stringify(session.validation.diagnostics));const next=session.validation.value;session.replay('undo');assert.equal(session.text,text);return next;};
const fixture=()=>{const pkg=minimalPackage('rules');pkg.extra={nil:null,empty:'',zero:0,no:false};pkg.system.dieScale=[4,6,8,10,12];pkg.system.characterTemplate.ready=true;pkg.system.characterTemplate.dice='1d6';pkg.system.characterTemplate.contacts=[{id:'stable',name:'Ana',die:4,current:0,max:3,recover:true,extra:{nil:null}},{id:'other',name:'Bia',die:6,current:0,max:2,recover:false}];pkg.system.characterTemplate.states=[{id:'state',name:'Exausto',sides:6,recoverable:true},{id:'kept',name:'Outro',sides:8,recoverable:false}];pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'list',label:'Contatos',field:'contacts',itemSchema:{name:{type:'text'},die:{type:'die'},current:{type:'number'},max:{type:'number'},recover:{type:'boolean'}}});return pkg;};

test('14C.4 módulos assistidos criam dependências compatíveis em uma operação reversível',()=>{
 const configs={slotTracker:{rows:[{level:1,used:0,max:3}],display:'remaining',newPreference:true},skillCatalog:{baseDie:4,categories:[{label:'Aventura',skills:['Nadar','Escalar']}],allowComposite:true},traitAllocation:{traits:[{label:'Agilidade'},{label:'Força'}],presets:[{label:'Equilibrado',dice:[6,6]}],initialDie:4},stateList:{recovery:true,overflow:true,overflowName:'Trauma',startDie:4,onFirst:[{field:'ready',value:false}]},inventorySummary:{strength:4,multiplier:5}};
 for(const [type,config]of Object.entries(configs)){
  const pkg=fixture(),before=structuredClone(pkg.system.characterTemplate),next=apply(pkg,assistedRecipePlan(pkg,{type,name:'Novo '+type,destination,config}));
  assert.deepEqual(pkg.system.characterTemplate,before);assert.deepEqual(next.extra,pkg.extra);assert.deepEqual(next.system.characterTemplate.contacts,pkg.system.characterTemplate.contacts);
  const component=next.layouts[0].tabs[0].sections[0].containers[0].components.find(c=>c.label==='Novo '+type);
  if(type==='slotTracker'){assert.deepEqual(next.system.characterTemplate[component.field],[{level:1,used:0,max:3}]);assert.equal(next.system.characterTemplate[component.consumeField],false);}
  if(type==='skillCatalog'){assert.equal(next.system[component.baseDieFrom],4);assert.deepEqual(next.system[component.categoriesFrom][0].skills,['Nadar','Escalar']);}
  if(type==='traitAllocation'){assert.deepEqual(next.system[component.presetsFrom][0].dice,[6,6]);assert.deepEqual(Object.values(next.system.characterTemplate[component.field]),[4,4]);}
  if(type==='stateList'){assert.equal(applyEffectToGradedState(12,12,next.system.dieScale).ascension,true);assert.deepEqual(component.overflow.onFirst,[{field:'ready',value:false}]);}
  if(type==='inventorySummary'){const character=structuredClone(next.system.characterTemplate);character[component.field].push({id:'one',weight:3,quantity:2,carried:true},{id:'two',weight:100,quantity:1,carried:false});assert.deepEqual(inventoryTotals(character,component),{weight:6,capacity:20,excess:0});}
 }
});
test('14C.4 receitas assistidas recusam inconsistências sem normalizar valores existentes',()=>{
 const pkg=fixture(),before=JSON.stringify(pkg),build=(type,config)=>assistedRecipePlan(pkg,{type,name:'Novo',destination,config});
 assert.throws(()=>build('slotTracker',{rows:[{level:1,used:4,max:3}]}));
 assert.throws(()=>build('skillCatalog',{baseDie:3,categories:[{label:'Geral',skills:['Nadar']}]}));
 assert.throws(()=>build('traitAllocation',{traits:[{label:'A'},{label:'B'}],presets:[{label:'Incompleto',dice:[4]}],initialDie:4}));
 assert.throws(()=>build('stateList',{overflow:true,overflowName:'Trauma',startDie:3}));
 assert.throws(()=>build('inventorySummary',{strength:-1,multiplier:5}));assert.equal(JSON.stringify(pkg),before);
});
test('14C.4 criação/evolução e repertório usam custos, vínculos e registros reais',()=>{
 const pkg=fixture(),costs={'0->4':1,'4->6':2,'6->8':3,'8->10':4,'10->12':5};
 let next=apply(pkg,progressionRecipePlan(pkg,{type:'pointBudget',name:'Evolução',destination,config:{presets:[{label:'Iniciante',points:10,maxDie:8}],adjustment:0,awarded:0,sources:[{label:'Talentos',baseDie:4,costs,allowComposite:true}],modifiers:[{label:'Vantagens',sign:-1}],postAscension:'n * 2'}}));
 let comp=next.layouts[0].tabs[0].sections[0].containers[0].components.find(c=>c.label==='Evolução'),config=next.system[comp.configFrom],character=structuredClone(next.system.characterTemplate);
 character[config.sources[0].field].push({id:'talent',name:'Nadar',die:6});character[config.modifiers[0].field].push({id:'mod',name:'Vantagem',points:1});
 assert.equal(pointBudget(character,next.system,config).creation.remaining,7);const saved=closeCreation(character,next.system,config);assert.equal(saved.spent,2);character[config.field].phase='play';character[config.field].creation=saved;character[config.sources[0].field][0].die=8;assert.equal(pointBudget(character,next.system,config).creation.spent,2);assert.equal(pointBudget(character,next.system,config).evolution.spent,0);assert.equal(evolutionTargets(character,next.system,config)[0].die,8);assert.equal(stepCost(8,10,next.system.dieScale,costs),4);
 next=apply(pkg,progressionRecipePlan(pkg,{type:'repertoire',name:'Repertório',destination,config:{progression:[{die:4,freeCount:1,grants:[{count:1,sides:6}]}]}}));comp=next.layouts[0].tabs[0].sections[0].containers[0].components.find(c=>c.label==='Repertório');config=next.system[comp.configFrom];character=structuredClone(next.system.characterTemplate);character[config.specializationsField].push({id:'special',name:'Magia',die:4});character[config.techniquesField].push({id:'tech',name:'Raio',maxDie:4,specializationId:'special',learningSource:'repertoire'});assert.deepEqual(repertoireStatus(character,next.system,config)[0].remaining,[]);assert.equal(repertoireStatus(character,next.system,config)[0].excess,0);
});
test('14C.4 Pool conserva fontes, filtros e configura a resolução existente com fórmula explícita',()=>{
 const pkg=fixture();pkg.system.extraResolution={zero:0};pkg.system.resolution={extra:{nil:null,no:false}};pkg.system.supportDie=6;pkg.system.characterTemplate.traits={agility:6};pkg.system.attributes=[{key:'agility',label:'Agilidade'}];
 const sources=[{kind:'constant',label:'Apoio',sides:4},{kind:'constant',label:'Sistema',sidesFrom:'supportDie'},{kind:'field',label:'Ficha',field:'score'},{kind:'entries',label:'Traços · {key}',field:'traits',id:'traits:{key}'},{from:'character',collection:'contacts',sides:'die',label:'Contatos',require:'recover',excludeWhen:{field:'name',equals:'Bia'}},{from:'system',collection:'attributes',sides:'traits.{key}',label:'Atributos'}];
 const next=apply(pkg,poolRecipePlan(pkg,{name:'Pool',destination,sources,resolution:{expression:'opponentWeight - actorWeight + 10',criticalSuccessAt:0,criticalFailureAt:20,note:'Mesa escolhe consequência.'},opposition:[{label:'Fraca',dice:[4,4]}]}));assert.deepEqual(next.system.resolution.extra,pkg.system.resolution.extra);setSystem(next.system);assert.equal(resolveAction(20,0).outcome,'criticalSuccess');assert.equal(resolveAction(0,20).outcome,'criticalFailure');setSystem(null);assert.deepEqual(next.layouts[0].tabs[0].sections[0].containers[0].components.at(-1).traitSources[4].excludeWhen,{field:'name',equals:'Bia'});
});
test('14C.4 técnicas preparam dados fixos e todos termos e modos atuais sem inferir custos',()=>{
 const pkg=fixture(),costs={4:0,6:1,8:2,10:3,12:4},modes=Object.keys(TECHNIQUE_TERMS).map(term=>({label:'Modo '+term,terms:[term],...(term==='constant'?{constantDie:4}:{}),...(term==='skill'?{skill:'Nadar'}:{}),energyFrom:'specialization',requiresTechnique:term==='technique',requiresConcentration:false,reverseOnFailure:true,failureImpact:true,free:false}));
 const next=apply(pkg,techniqueRecipePlan(pkg,{name:'Usar técnicas',destination,config:{attributes:[{label:'Agilidade',die:6}],skillBaseDie:4,energyCurrent:5,energyMax:10,costs,modes}})),comp=next.layouts[0].tabs[0].sections[0].containers[0].components.find(c=>c.type==='techniqueUse'),config=next.system[comp.configFrom];assert.equal(config.modes.length,6);assert.deepEqual(next.system[config.costsFrom],costs);assert.equal(next.system.characterTemplate[config.skillsField].Nadar,4);assert.deepEqual(next.system.characterTemplate[config.energyField],{current:5,max:10});assert.deepEqual(next.system.characterTemplate[config.concentrationField],[]);assert.deepEqual(next.system.characterTemplate.contacts,pkg.system.characterTemplate.contacts);
 assert.throws(()=>techniqueRecipePlan(pkg,{name:'Incompleto',destination,config:{attributes:[{label:'A',die:4}],skillBaseDie:4,energyCurrent:1,energyMax:2,costs:{4:0},modes:[{label:'Modo',terms:['constant'],constantDie:4}]}}));
 assert.throws(()=>techniqueRecipePlan(pkg,{name:'Coleção incompatível',destination,config:{specializationsField:'contacts',techniquesField:'contacts'}}));
});
test('14C.4 componentes D&D usam catálogos originais e derivados conhecidos sem criar mecânicas',()=>{
 const raw={kind:'rpg-system-package',schemaVersion:1,system:JSON.parse(readFileSync(new URL('../../data/systems/dnd2024.system.json',import.meta.url),'utf8')),layouts:[JSON.parse(readFileSync(new URL('../../data/systems/dnd2024.layout.json',import.meta.url),'utf8'))]};const prepared=prepareDocument(raw,{kind:'package'});assert.ok(prepared.document);const pkg=prepared.document;
 for(const [type,options]of [['dndAbility',{key:'str'}],['dndSkill',{key:'acrobatics'}],...Object.keys(DND_STATS).map(stat=>['dndDerived',{stat}])]){const next=apply(pkg,dndRecipePlan(pkg,{type,name:'Novo '+type,destination,...options}));assert.deepEqual(next.system.characterTemplate,pkg.system.characterTemplate);assert.deepEqual(next.system.abilities,pkg.system.abilities);}
 assert.throws(()=>dndRecipePlan(fixture(),{type:'dndDerived',name:'Derivado',destination,stat:'initiative'}));
});
test('14C.4 cópia nomeada de regra conserva extras e mantém original compartilhado',()=>{
 const pkg=fixture();pkg.system.myActions=[{id:'action',label:'Original',operations:[{type:'set',field:'ready',value:false}],extra:{nil:null}}];pkg.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'actionGroup',label:'Ações',actionsFrom:'myActions'});
 const plan=copyRulePlan(pkg,['system','myActions'],'Cópia independente'),next=apply(pkg,plan);assert.deepEqual(next.system.myActions,pkg.system.myActions);assert.deepEqual(next.system[plan.key],pkg.system.myActions);assert.deepEqual(next.system[plan.key][0].extra,{nil:null});
});
test('14C.4 receitas dos oito algoritmos e três fontes validam e executam engine real',()=>{for(const algorithm of CHECK_ALGORITHMS)for(const kind of ['field','collection','formula']){if(algorithm==='explodingDamage'&&kind==='formula')continue;const pkg=fixture();pkg.system.characterTemplate.testValue=algorithm==='explodingDamage'?'2d6 + 1':algorithm==='explodingTrait'?4:algorithm==='progress'?8:2;pkg.system.formulas.test='4';const source={id:'source_1',label:'Fonte',...(kind==='field'?{field:algorithm==='explodingDamage'?'dice':'testValue'}:kind==='collection'?{collection:'contacts',valueField:'die'}:{formula:'test'})};if(algorithm==='explodingDamage'&&kind==='collection'){source.valueField='expression';pkg.system.characterTemplate.contacts.forEach(c=>c.expression='1d6');}const next=apply(pkg,checkRecipePlan(pkg,{name:'Teste',destination,config:{algorithm,sources:[source],note:'Oposição, custos e consequências são decisões da mesa.'}}));const character=structuredClone(next.system.characterTemplate),id=kind==='collection'?JSON.stringify(['source_1','id','stable']):'source_1';const prepared=prepareCheck({config:next.system.checks.teste,character,system:next.system,checkId:'teste',sourceId:id,options:{target:4}});const result=prepared.execute(()=>2);assert.ok(Number.isFinite(result.total),algorithm+'/'+kind);assert.deepEqual(character,next.system.characterTemplate);assert.deepEqual(next.extra,pkg.extra);}});
test('14C.4 todas as operações de ação geradas preservam dados e executam somente o declarado',()=>{const operations={set:{field:'ready',value:false},add:{field:'score',amount:-1,min:0},restoreResource:{field:'health'},rollResource:{field:'health',sourceField:'contacts',dieField:'die'},reduceNamedStates:{field:'states',names:['Exausto'],gradeField:'sides',steps:1},clearNamedStates:{field:'states',names:['Exausto']},restoreCollection:{field:'contacts',valueField:'current',maxField:'max',filterField:'recover',filterValues:[true]},setCollection:{field:'contacts',valueField:'current',value:0,filterField:'recover',filterValues:[true]}};for(const type of ACTION_OPERATIONS){const pkg=fixture(),op={type,...operations[type]},next=apply(pkg,actionRecipePlan(pkg,{name:'Ação',destination,action:{requirements:[{field:'ready',equals:true}],operations:[op]}})),character=structuredClone(next.system.characterTemplate);executeSheetAction(character,next.system.sheetActions[0],next.system);if(type==='restoreResource')assert.equal(character.health.current,10);if(type==='restoreCollection'){assert.equal(character.contacts[0].current,3);assert.equal(character.contacts[1].current,0);assert.equal(character.contacts[0].id,'stable');assert.deepEqual(character.contacts[0].extra,{nil:null});}if(type==='add')assert.equal(character.score,1);if(type==='reduceNamedStates')assert.equal(character.states[0].sides,4);if(type==='clearNamedStates')assert.deepEqual(character.states,[pkg.system.characterTemplate.states[1]]);character.ready=false;const before=structuredClone(character);assert.throws(()=>executeSheetAction(character,next.system.sheetActions[0],next.system));assert.deepEqual(character,before);}});
test('14C.4 recuperações, filtros, dado/manual e conflito de baseline',()=>{const operations={restoreValue:{field:'health.current',maxField:'health.max'},set:{field:'ready',value:false},restoreCollection:{field:'contacts',valueField:'current',maxField:'max',filterField:'recover',filterValues:[true]},setCollection:{field:'contacts',valueField:'current',value:0}};for(const type of RECOVERY_CONTRACT.operations){const pkg=fixture(),next=apply(pkg,recoveryRecipePlan(pkg,{name:'Descanso',destination,action:{operations:[{type,...operations[type]}]}})),config=next.system.recoveryActions[0],character=structuredClone(next.system.characterTemplate),context={character,system:next.system},baseline=structuredClone(character);const plan=recoveryPlan(context,config);assert.deepEqual(character,baseline);applyRecovery(context,config,[],baseline);assert.ok(plan.effects.length||type==='setCollection');character.health.current=0;if(type==='restoreValue')assert.throws(()=>applyRecovery(context,config,[],baseline));}const pkg=fixture();Object.assign(pkg.system.characterTemplate,{healingTotal:2,healingUsed:0});const next=apply(pkg,recoveryRecipePlan(pkg,{name:'Curar',destination,action:{healing:{field:'health.current',maxField:'health.max',totalField:'healingTotal',usedField:'healingUsed',dieField:'dice',modifier:{value:0}},operations:[]}})),context={character:structuredClone(next.system.characterTemplate),system:next.system},config=next.system.recoveryActions[0];assert.equal(recoveryDie(context,config,'3'),3);applyRecovery(context,config,[3],structuredClone(context.character));assert.equal(context.character.health.current,8);assert.equal(context.character.healingUsed,1);assert.throws(()=>recoveryPlan(context,config,[1,1]));});
test('14C.4 rolagens e consumo opcional: zero, insuficiente e falha não debitam',()=>{const pkg=fixture(),config={check:{expression:{value:'1d20'},modifier:{field:'score'}},effect:{expression:{value:'2d6'}},scale:{base:{value:1},min:1,max:3,increment:{value:'1d6'}},resource:{field:'score',mode:'remaining',cost:{value:1},consumeField:'ready'}};const next=apply(pkg,entryRollRecipePlan(pkg,{name:'Técnicas',destination,config,collection:'contacts'})),character=structuredClone(next.system.characterTemplate),context={character,system:next.system,item:character.contacts[0],rollPreset:'tecnicas'};const before=structuredClone(character),roll=prepareEntryRoll({expression:parseDiceExpression('2d6'),resource:config.resource,context,consume:true},()=>2);assert.deepEqual(character,before);roll.payment.apply();assert.equal(character.score,1);assert.throws(()=>prepareEntryRoll({expression:{dice:[{count:101,sides:6}],modifier:0},resource:config.resource,context,consume:true},()=>2));assert.equal(character.score,1);const zero=prepareEntryRoll({expression:null,resource:{...config.resource,cost:{value:0}},context,consume:true});zero.payment.apply();assert.equal(character.score,1);character.score=0;assert.throws(()=>prepareEntryRoll({expression:null,resource:config.resource,context,consume:true}));assert.equal(character.score,0);assert.deepEqual(character.contacts[0].extra,{nil:null});});
test('14C.4 efeitos: v2 em todos layouts, +2 sem alterar base, evento e unidade',()=>{const pkg=fixture();pkg.layouts.push({...structuredClone(pkg.layouts[0]),id:'table',mode:'table'});const next=apply(pkg,effectRecipePlan(pkg,{name:'Proteção',destination,definition:{applicability:'always',group:'Defesa',duration:{type:'untilEvent',event:'endScene'},operations:[{type:'add',value:2,target:{kind:'calculation',key:'computed.total'}}]}}));assert.equal(next.schemaVersion,2);assert.equal(next.system.schemaVersion,2);for(const layout of next.layouts){assert.equal(layout.schemaVersion,2);assert.ok(layout.tabs[0].sections[0].containers[0].components.some(c=>c.type==='effectList'));}assert.equal(Object.hasOwn(next.system.characterTemplate,'activeEffects'),false);const character=structuredClone(next.system.characterTemplate),component=next.layouts[0].tabs[0].sections[0].containers[0].components[3];activateEffect(character,next.system,'protecao','instance');assert.equal(computedValue({...component,character,system:next.system}),5);assert.equal(character.score,2);assert.throws(()=>activateEffect(character,next.system,'protecao'));confirmEffectEvent(character,'endScene');assert.equal(computedValue({...component,character,system:next.system}),3);assert.equal(character.score,2);assert.deepEqual(next.extra,pkg.extra);});
test('14C.4 fontes e alternativas preservam extras, vazio/zero e exclusividade',()=>{assert.deepEqual(readRollSource({kind:'value',valueType:'number',raw:'0',fallbackMode:'keep'},{field:'score',extensions:{nil:null},fallback:''}),{value:0,extensions:{nil:null},fallback:''});assert.deepEqual(readRollSource({kind:'field',source:'score',fallbackMode:'remove'},{value:2,variables:{a:{value:1}},fallback:0}),{field:'score'});assert.throws(()=>readRollSource({kind:'value',valueType:'number',raw:'abc'}));assert.throws(()=>readRollSource({kind:'field',source:''}));});
