import test from 'node:test';
import assert from 'node:assert/strict';
import {minimalPackage} from '../../js/editor/minimal-package.js';
import {revisionProjection} from '../../js/editor/projection-cache.js';
import {structuralNodes} from '../../js/editor/form-structure.js';
import {dataIndex} from '../../js/editor/data-index.js';
import {ruleSchemaAt} from '../../js/editor/capability-catalog.js';
import {formulaContexts} from '../../js/editor/formula-contexts.js';
import {diceLiteralAt} from '../../js/editor/dice-literals.js';
import {relinkItemPlan} from '../../js/editor/data-commands.js';
import {dataChoices} from '../../js/editor/data-picker.js';
import {rollReadings} from '../../js/editor/experiment-report.js';
import {readRollSource} from '../../js/editor/roll-source-editor.js';
test('14 auditoria: cache só em documento de revisão, mutáveis continuam atuais',()=>{const p=minimalPackage('projection');const before=dataIndex(p);p.system.characterTemplate.newValue=false;assert.ok(dataIndex(p).some(r=>r.field==='newValue'));assert.notEqual(dataIndex(p),before);revisionProjection(p);assert.equal(dataIndex(p),dataIndex(p));assert.equal(structuralNodes(p),structuralNodes(p));const next=structuredClone(p);next.system.characterTemplate.newValue=0;revisionProjection(next);assert.equal(dataIndex(next).find(r=>r.field==='newValue').value,0);});
test('14 auditoria: contextos de cálculo distinguem leituras e identidade de ajuste',()=>{const p=minimalPackage('contexts'),cs=p.layouts[0].tabs[0].sections[0].containers[0].components;cs[3].variables={score:{value:0}};cs.push({...cs[3],label:'Segundo contexto',variables:{score:{value:9}}});assert.equal(formulaContexts(p,'total').length,2);cs.push({...cs[3],label:'Mesmo contexto'});assert.equal(formulaContexts(p,'total').length,2);});
test('14 auditoria: builder de dados é autorizado pelo consumidor, não pelo nome',()=>{const p=minimalPackage('dice-data');p.system.characterTemplate.damage='1d6';p.system.characterTemplate.note='1d6';p.system.checks={damage:{algorithm:'explodingDamage',sources:[{id:'d',label:'Dano',field:'damage'}]}};assert.equal(diceLiteralAt(p,['system','characterTemplate','damage']),true);assert.equal(diceLiteralAt(p,['system','characterTemplate','note']),false);});
test('14 auditoria: slots internos não são religados para chaves não consumidas',()=>{const p=minimalPackage('slots'),path=['layouts',0,'tabs',0,'sections',0,'containers',0,'components'];p.system.characterTemplate.slots=[];p.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'slotTracker',field:'slots',itemSchema:{used:{type:'number',label:'Usos'}}});assert.throws(()=>relinkItemPlan(p,[...path,4,'itemSchema','used'],'gastos'),/interno/);});
test('14 auditoria: técnica em caminho customizado seleciona atributos e perícias',()=>{const p=minimalPackage('tech-options');p.system.attributes=[{key:'agility',label:'Agilidade'}];p.system.characterTemplate.skills={'Primeiros socorros':6};p.system.customTechnique={attributesFrom:'attributes',skillsField:'skills',modes:[{label:'Modo',terms:['attribute']}]};p.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'techniqueUse',configFrom:'customTechnique'});const path=['system','customTechnique','modes',0];assert.equal(ruleSchemaAt(p,['system','customTechnique']).properties.modes.items.properties.defaultAttribute.editor,'attributeKey');assert.deepEqual(dataChoices(p,[...path,'defaultAttribute'],'defaultAttribute'),[['agility','Agilidade']]);assert.deepEqual(dataChoices(p,[...path,'skill'],'skill'),[['Primeiros socorros','Primeiros socorros']]);});
test('14 auditoria: relatório lê fonte real e contribuições do snapshot sem recomputar',()=>{const result={snapshot:{source:{label:'Agilidade',value:0},options:{wild:false,target:0},manualModifier:0,effects:{contributions:[{label:'Coringa',value:2,revision:1}]}}};assert.deepEqual(rollReadings(result),[{label:'Agilidade',value:'0'},{label:'Alvo ou oposição',value:'0'},{label:'Dado selvagem',value:'Não'},{label:'Modificador informado pela mesa',value:'0'},{label:'Efeito: Coringa',value:'2 · revisão 1'}]);});
test('14 auditoria: trocar fonte conserva fallback e extras sem normalização',()=>{for(const fallback of [null,0,false,'',[],{}])assert.deepEqual(readRollSource({kind:'field',source:'score',fallbackMode:'keep'},{value:1,fallback,extensions:{nil:null}}),{field:'score',fallback,extensions:{nil:null}});});
test('14 auditoria: escolha explícita de leituras substitui aliases antigos ao trocar fórmula',()=>{const state={kind:'formula',source:'new',formulaContext:{variables:{a:{value:0}}},fallbackMode:'keep'};assert.deepEqual(readRollSource(state,{formula:'old',variables:{a:{value:9}},overrideKey:'old',extensions:{nil:null}}),{formula:'new',variables:{a:{value:0}},extensions:{nil:null}});assert.doesNotThrow(()=>structuredClone(state));});
test('14 auditoria: dados de coleção aninhada seguem consumidor e alias de preset',()=>{const p=minimalPackage('nested-dice');p.system.characterTemplate.own={items:[{damage:'2d6'}]};p.system.entryRolls={hit:{effect:{expression:{itemField:'damage'}}}};p.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'list',field:'own.items',entryAction:'roll',rollConfigFrom:'hit'});assert.equal(diceLiteralAt(p,['system','characterTemplate','own','items',0,'damage']),true);assert.equal(ruleSchemaAt(p,['system','entryRolls','hit']).type,'object');p.system.customCheck={algorithm:'explodingDamage',sources:[{collection:'own.items',valueField:'damage'}]};p.layouts[0].tabs[0].sections[0].containers[0].components.push({type:'checkRoll',configFrom:'customCheck'});delete p.system.entryRolls;assert.equal(diceLiteralAt(p,['system','characterTemplate','own','items',0,'damage']),true);});

test('14 auditoria: contexto de rolagem usa a identidade literal do cálculo',()=>{const p=minimalPackage('override-context');p.layouts[0].tabs[0].sections[0].containers[0].components[3].overrideKey='scope';assert.equal(formulaContexts(p,'total',{family:'roll'})[0].overrideKey,'computed.scope');p.layouts[0].tabs[0].sections[0].containers[0].components[3].variables={trait:{rollField:'score'}};assert.equal(formulaContexts(p,'total').length,1);assert.equal(formulaContexts(p,'total',{family:'check'}).length,0);});

test('14 canvas: inserção de seção/caixas/campos usa somente operações do pacote',async()=>{const {canvasInsertionPlan}=await import('../../js/editor/canvas-insertion.js'),{applyOperations}=await import('../../js/editor/operations.js'),{prepareDocument}=await import('../../js/validation/documents.js');const pkg=minimalPackage('canvas');for(const type of ['text','resource','container-grid','section']){const destination=type==='section'?['layouts',0,'tabs',0,'sections']:type==='container-grid'?['layouts',0,'tabs',0,'sections',0,'containers']:['layouts',0,'tabs',0,'sections',0,'containers',0,'components'];const plan=canvasInsertionPlan(pkg,{type,destination,index:0}),next=JSON.parse(applyOperations(JSON.stringify(pkg),plan.commands));assert.equal(prepareDocument(next,{kind:'package'}).status,'ready');assert.deepEqual(pkg,minimalPackage('canvas'));}assert.equal(canvasInsertionPlan(pkg,{type:'checkRoll',destination:['layouts',0,'tabs',0,'sections',0,'containers',0,'components']}),null);});

test('14 autoria: criar dado ausente com nome repetido não compartilha vínculo implicitamente',async()=>{const {insertionPlan}=await import('../../js/editor/composition-commands.js'),{applyOperations}=await import('../../js/editor/operations.js');let p=minimalPackage('absent-identity'),destination=['layouts',0,'tabs',0,'sections',0,'containers',0,'components'];for(let i=0;i<2;i++)p=JSON.parse(applyOperations(JSON.stringify(p),insertionPlan(p,{type:'text',name:'Notas',destination}).commands));const fields=p.layouts[0].tabs[0].sections[0].containers[0].components.slice(-2).map(c=>c.field);assert.deepEqual(fields,['notas','notas_2']);assert.equal(Object.hasOwn(p.system.characterTemplate,'notas'),false);assert.equal(Object.hasOwn(p.system.characterTemplate,'notas_2'),false);});
